### PR TITLE
PQ exclusive locking backport in 5.2

### PR DESCRIPTION
**Pull request by colinsurprenant**
This backports the 5.3 PQ exclusive locking into 5.2, which also required backporting:
- pipeline reloading fixes to avoid double opened pipelines
- pipeline workers start to properly clean state upon errors
- all related specs

### CODE REVIEW

**Comment by colinsurprenant** [comment]
the build error is related to
```
Error Bundler::InstallError, retrying 1/10
An error occurred while installing rest-client (2.0.0), and Bundler cannot continue.
Make sure that `gem install rest-client -v '2.0.0'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```
not sure why.

**Comment by ph** [comment]
@colinsurprenant This was a Travis bundler cache issue with an old failing run bringing `rest-client`, cleaning the cache made this tests green again.

**Comment by colinsurprenant** [comment]
MAKE TRAVIS TESTS GREEN AGAIN :D 
Thanks @ph

**Comment by colinsurprenant** [comment]
thanks @jsvd

**Comment by colinsurprenant** [comment]
thanks @ph. 

Great, will go ahead and merge.

**Comment by colinsurprenant** [comment]
squashed and merged in 5.2 only

**Pull request merged**
