### PR TITLE
Add cgroup information to the api

### PR DESCRIPTION
**Pull request by ph**
When logstash is run under a linux container we will gather statistic about the cgroup and the
cpu usage. This information will should in the /_node/stats api and the result will look like this:

```
  "os" : {
    "cgroup" : {
      "cpuacct" : {
        "usage" : 789470280230,
        "control_group" : "/user.slice/user-1000.slice"
      },
      "cpu" : {
        "cpu_quota_micros" : -1,
        "control_group" : "/user.slice/user-1000.slice",
        "stat" : {
          "number_of_times_throttled" : 0,
          "time_throttled_nanos" : 0,
          "number_of_periods" : 0
        },
        "cfs_period_micros" : 100000
      }
    }
  }
```

Fixes: #6252

### CODE REVIEW

**Comment by ph** [comment]
I will take a look at the failling test

**Comment by ph** [comment]
should be fixed now.

**Comment by ph** [comment]
@jsvd this will also be need for the monitoring.

**Comment by jordansissel** [comment]
I tested this manually. Creating a new cgroup for myself:

```
% sudo cgcreate -t jls:jls -g cpu,cpuacct:/jls
% cgexec -g cpu:/jls bin/logstash -e '' --http.host 0.0.0.0
```

Looking good.

My next question is about the following example stat output:

```
  "os" : {
    "cgroup" : {
      "cpuacct" : {
        "usage" : 26969185690,
```

* There's no obvious unit for `usage`. Could we add one?
* Should `cpuacct` be `cpu,cpuacct` instead, since this is what Linux calls it?

**Comment by ph** [comment]
@jordansissel 

I've used the ES reference to return the same information, ES don't explicitly return a unit with the `usage`, I believe this is typo and it should be `usage_nanos` IMHO.

```
os.cgroup.cpuacct.usage (Linux only)
The total CPU time (in nanoseconds) consumed by all tasks in the same cgroup as the Elasticsearch process
```

https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html

**Comment by jordansissel** [comment]
+1 on calling it `usage_nanoseconds` or slightly worse `usage_nanos` -- I leave it up to you :)

**Comment by jordansissel** [comment]
LGTM

usage, usage_nanos, usage_nanoseconds -- I leave it up to you.

**Comment by ph** [comment]
I'll go with usage for now to keep in sync with ES, in the future we might want to have more description on the unit.

**Comment by jasontedor** [comment]
> I believe this is typo and it should be `usage_nanos` IMHO.

It is, I agree with you that it should have been called `usage_nanos` and I'm leaning towards changing it to this to be consistent with the other metrics that carry units.

**Comment by jasontedor** [comment]
It already is `usage_nanos` in the [code](https://github.com/elastic/elasticsearch/blame/43f71015a8d117265a54e01658302f9ad7903821/core/src/main/java/org/elasticsearch/monitor/os/OsStats.java#L399), this was just a doc bug; I pushed elastic/elasticsearch@41ffb008ad285735f8bc3c9b97b23c6589a17fef.

**Comment by ph** [comment]
@jason I will make a new PR so both are in sync.

**Comment by ph** [comment]
@jasontedor done in https://github.com/elastic/logstash/pull/6428 and merged! thanks for ping.

**Comment by jasontedor** [comment]
Thanks @ph.

**Pull request closed without merging**
