### PR TITLE
Remove unnecessary register when doing deep clone for codecs

### PR DESCRIPTION
**Pull request by purbon**
@guyboertje review?

### CODE REVIEW

**Comment by guyboertje** [comment]
LGTM and thanks @purbon

**Comment by purbon** [comment]
welcome! which branches should this be merged?

**Comment by jsvd** [comment]
may I suggest a test that shows this actually fixes a bug?

**Comment by purbon** [comment]
Sure,
   I would just check that register is call once when doing deep clone,
makes sense guy?

Is there any special problem this fix?

/purbon

**Comment by jsvd** [comment]
On a side note, I believe we could change: ` when Fixnum, Symbol, IO, TrueClass, FalseClass, NilClass` to just `when IO`, all others can be Marshal.dump/load

**Comment by purbon** [comment]
@jsvd I see you improvement as a perfect followup, good catch.

**Comment by guyboertje** [comment]
@purbon, @jsvd 
> Is there any special problem this fix?
> may I suggest a test that shows this actually fixes a bug?
There is no bug.  Some codec may not like register called twice. The `deep_clone` method needs to as fast as possible and registering a second time is a waste of cycles.

> On a side note, I believe we could change: when Fixnum, Symbol, IO, TrueClass, FalseClass, NilClass to just when IO, all others can be Marshal.dump/load

- Fixnum, Symbol can't be cloned or duped
- Values of true, false and nil can't be mutated as such
- IO can't be Marshalled/serialised and we probably need the original, e.g. logger
- Marshal load dump is much more expensive than dup or clone.

This is why I return the original for Fixnum, Symbol, IO, TrueClass, FalseClass, NilClass and only use Marshalling as a last resort.

Merge to master, 2.2 and 2.x

**Comment by purbon** [comment]
@guyboertje adding small test to check for this.

**Comment by jsvd** [comment]
+1 that this is not a bug. thanks for the enlightenment @guyboertje

**Pull request closed without merging**
