### PR TITLE
JRuby 9.0.3.0 upgrade

### PR DESCRIPTION
**Pull request by purbon**
This PR hold the necessary updates to include jruby 9.0.0.0 as a default engine for logstash.

Pending tasks:

###### (check with jruby-1.7.x (1.9 ruby code) and 9.0.0.0 (2.2.0 ruby code) )

- [x] make ```rake bootstrap``` and related calls (like ```rake test:install-core```) install gems in the right bundle directory, so the system can pick them up later.
- [x] make USE_RUBY=1 work as expected.

## State of the PR:

All works as expected for now, having the same behaviour as master. Keep in mind if you aim to use USE_RUBY=1 to run test, there is an known issue (also in master) #3701 where it does not locate gems properly. For the rest, this PR is in good health to be reviewed and merged if good!

## This to be aware when testing:

* Keep in mind there are two scenarios here, using as system ruby an engine of the ```jruby-1.7.x``` branch while having vendored the ```jruby-9.0.0.0``` one, or using as system ruby also the ```jruby-9.0.0.0```. Both should work when running the test.
* There is a known issue, #3701 of using USE_RUBY and rake (also in master).

### CODE REVIEW

**Comment by purbon** [comment]
bin/rspec works as expected to run the test, however rake test:core task fails with missing bundler.

**Comment by ph** [comment]
Okay did a bit of experiments on my side with this branch.
And this is a bit weird, if you add this line to your `bootstrap/bundler.rb`
```ruby
# near like 43
puts "DIRS: #{Gem::Specification.dirs}"
::Gem::Specification.find_by_name("bundler")
require "bundler"
LogStash::Bundler.patch!
```

and then you run  `rake test:install-core; rake test`
You  will get this warning:

```
/t/logstash git:pr/3654 ❯❯❯ rake test                                                                                                                                                                                                                    ⏎ ✱
DIRS: ["/private/tmp/logstash/vendor/bundle/jruby/2.2.0/specifications", "uri:classloader://specifications"]
rake aborted!
Could not find 'bundler' (>= 0) among 12 total gem(s)
Checked in 'GEM_PATH=/private/tmp/logstash/vendor/bundle/jruby/2.2.0', execute `gem env` for more information
/private/tmp/logstash/lib/bootstrap/bundler.rb:44:in `setup!'
/private/tmp/logstash/rakelib/test.rake:15:in `block in (root)'
org/jruby/RubyProc.java:308:in `call'
org/jruby/RubyArray.java:1560:in `each'
```

What we can see here is that`Gem::Specification.dirs` return the correct path but the `require` method still look into the gems directory of the jruby distribution located at `vendor/jruby/lib/ruby/gems/shared/specifications/default`

**Comment by ph** [comment]
`Could not find 'bundler' (>= 0) among 12 total gem(s)` this message confirm it because there is 12 specifications file in the default directory.

**Comment by ph** [comment]
I've tried to force a reset of the specification with no luck, `rake test` cannot find bundler in that context.
Not sure what to think here, since I did a diff of this PR and the master branch and the changes look minimal.

**Comment by ph** [comment]
If we compare the available specifications available when we run `rake test` from the master branch we get **78**, a lot bigger than **12**

I used this code for this.
```
puts "TOTAL SPECS: #{::Gem::Specification.to_a.size}"
```

**Comment by ph** [comment]
Also, the way I understand the rubygems code, this assigment should reset the specification database.

```
::Gem.paths = ENV['GEM_HOME'] = ENV['GEM_PATH'] = Environment.logstash_gem_home
```

**Comment by purbon** [comment]
The error I'm trying to solve here is:

```
Installation successful
╭─purbon@purbon-elastic  ~/work/logstash ‹jruby-1.7.20› ‹feature/jruby9k_update*› 
╰─$ rake test:core
rake aborted!
no such file to load -- bundler
org/jruby/RubyKernel.java:940:in `require'
/Users/purbon/work/logstash/lib/bootstrap/bundler.rb:43:in `setup!'
/Users/purbon/work/logstash/rakelib/test.rake:15:in `block in (root)'
org/jruby/RubyProc.java:308:in `call'
org/jruby/RubyArray.java:1560:in `each'
org/jruby/RubyArray.java:1560:in `each'
org/jruby/RubyArray.java:1560:in `each'
org/jruby/RubyKernel.java:958:in `load'
Tasks: TOP => test:core => test:setup
(See full trace by running task with --trace)
╭─purbon@purbon-elastic  ~/work/logstash ‹jruby-1.7.20› ‹feature/jruby9k_update*› 
╰─$ bin/rspec                                                                                                                  1 ↵
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 4.41 seconds (files took 1.68 seconds to load)
740 examples, 0 failures

Randomized with seed 29515
```

but if you use jruby9k as main ruby

```
╭─purbon@purbon-elastic  ~/work/logstash ‹jruby-9.0.0.0.rc2› ‹feature/jruby9k_update*› 
╰─$ rake test:core
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 7.56 seconds (files took 4.12 seconds to load)
718 examples, 0 failures

Randomized with seed 11768
```

suspects right now are ```rake``` because of the restart in place at https://github.com/elastic/logstash/blob/master/rakelib/z_rubycheck.rake ... 

Currently investigating ways to run rake with the vendored ruby directly.

**Comment by purbon** [comment]
Interesting fact, if using ```USE_RUBY=1``` with all the necessary commands, ``` rake test:core``` will fail.

```
USE_RUBY=1 rake bootstrap 
USE_RUBY=1 rake test:install-core
```

then  ``` USE_RUBY=1 rake test:core``` will fail with:

```
purbon-elastic% USE_RUBY=1 rake test:core        
rake aborted!
Bundler::GemNotFound: Could not find benchmark-ips-2.3.0 in any of the sources
/Users/purbon/work/logstash/lib/bootstrap/bundler.rb:53:in `setup!'
/Users/purbon/work/logstash/rakelib/test.rake:15:in `(root)'
Tasks: TOP => test:core => test:setup
```

using the shim introduced at ```bin/rake``` or ```bin/rspec``` works nice.

**Comment by purbon** [comment]
please jenkins, test this again.

**Comment by purbon** [comment]
please jenkins, test this again.

**Comment by purbon** [comment]
@jsvd @ph could you guys take a look here? thanks a lot!

**Comment by purbon** [comment]
benchmarks will come soon! :smile_cat:

**Comment by purbon** [comment]
# Running lsperfm (logstash master - JRuby 1.7.20)
```
name, start time,elapsed,events,avg tps,best tps,avg top 20% tps
simple line in/out,7.80,120.41,3206000,26626,35700.00,31560
simple line in/json out,8.50,120.46,3578000,29703,40700.00,35721
json codec in/out,8.37,120.06,2646000,22039,26800.00,25904
line in/json filter/json out,8.19,120.13,2302000,19163,24200.00,22039
apache in/json out,7.85,120.04,2801700,23340,37700.00,30878
apache in/grok codec/json out,12.52,120.04,980100,8165,12500.00,10182
syslog in/json out,11.73,120.50,244000,2025,2500.00,2434
```

**Comment by guyboertje** [comment]
My jruby 9000 improvements were seen on Java 8,  hmmm?

**Comment by purbon** [comment]
ok @guyboertje will run numbers again with jdk8.

**Comment by purbon** [comment]
More numbers this time with Oracle Java 8:

##### Linux 8Core - 31G RAM - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz

```Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [linux-amd64]```

___(Logstash jruby9k branch)___

name | start time | elapsed | events  | avg tps | best tps | avg top 20% tps
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
simple line in/json out | 3.37 | 120.16 | 7240000 | 60254 | 66500.00 | 65713
json codec in/out | 3.71 | 120.03 | 5260000 | 43822 | 53300.00 | 50191
line in/json filter/json out | 3.91 | 120.04 | 4296000 | 35788 | 46400.00 | 43686
apache in/json out | 3.40 | 120.04 | 6450840 | 53740 | 59300.00 | 58534
apache in/grok codec/json out | 3.20 | 120.07 | 2684880 | 22362 | 23500.00 | 23343
syslog in/json out | 3.65 | 120.12 | 608000 | 5061 | 5300.00 | 5269

**Comment by purbon** [comment]
More numbers, this time run with Oracle JDK 8, overall, and without taking a very close look, I think numbers with oracle-jdk8 correlate with openjdk7, is this an expected result? from comments by @guyboertje my expectation here would be that the jruby9k branch beats the master one if running jdk8.

Although by default everything looks like a bit faster using the 8 JDK.

**Comment by purbon** [comment]
Upgrading this to http://jruby.org/2015/09/02/jruby-9-0-1-0 soon!

**Comment by purbon** [comment]
Some performance numbers with the new jruby release.

simple line in/out,15.35,121.19,930000,7674,12100.00,10621
simple line in/json out,21.25,120.76,1108000,9175,14100.00,11956
json codec in/out,24.69,120.04,642000,5348,9800.00,7873
line in/json filter/json out,22.84,120.21,660000,5490,9200.00,8273
apache in/json out,21.08,120.07,2813580,23432,30200.00,27739
apache in/grok codec/json out,8.55,120.14,1401840,11669,13100.00,12669
syslog in/json out,9.71,120.25,376000,3127,3400.00,3400

**Comment by purbon** [comment]
Some performance numbers with the new jruby release.

##### Macbook Pro - 2,8 GHz Intel Core i5 8 GB 1600 MHz DDR3
```Java HotSpot(TM) 64-Bit Server VM 1.7.0_71-b14 +jit [darwin-x86_64]```

``` jruby 9.0.3.0```

name | start time | elapsed | events  | avg tps | best tps | avg top 20% tps
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
simple line in/out|9.88|120.40|2764000|22957|33700.00|28726
simple line in/json out|10.52|120.22|4476000|37233|59200.00|49156
json codec in/out|9.91|120.04|2666000|22209|28200.00|26017
line in/json filter/json out|11.54|120.13|2668000|22210|32800.00|30117
apache in/json out|10.17|120.04|2443320|20354|29600.00|26886
apache in/grok codec/json out|10.50|120.11|1972080|16419|19800.00|19169
syslog in/json out|11.68|120.36|592000|4919|5900.00|5739

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by suyograo** [comment]
Closing this for now. We can reopen when we are ready to move to 9k

**Comment by purbon** [comment]
I guess what we can do is keep an issue open with performance with this
releases, isn't? then we can keep an eye when we actually can move, or also
might be have LS with 9k, run in the benchmark site, what do you think?

**Pull request closed without merging**
