### PR TITLE
Removing reference of `fieldreference`

### PR DESCRIPTION
**Pull request by ph**
This module was replaced by `lib/logstash/util/accessor.rb`

### CODE REVIEW

**Comment by talevy** [comment]
LGTM

**Comment by colinsurprenant** [comment]
should we try to transpose the old fieldeval_spec.rb tests in the accessors specs?

**Comment by ph** [comment]
I'll check if we are not missing some tests in the accessors.

**Comment by jordansissel** [comment]
LGTM + @colinsurprenant's [comment](https://github.com/elastic/logstash/pull/3467#issuecomment-113983172)

**Comment by ph** [comment]
I've checked, we cover the test case in the new accessors class.

**Pull request closed without merging**
