### PR TITLE
Add Docker acceptance to exhaustive BK pipeline

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

This commit adds the Docker acceptance tests in the acceptance phase
of the exhaustive tests pipeline.
    
## How to test this PR locally

Example runs:

- https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/89 (the whole suite minus packaging)
- https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/52 (just the group added here)

## Related issues

- Built on top /depends on: https://github.com/elastic/logstash/pull/15699
- Relates: https://github.com/elastic/ingest-dev/issues/1722

### CODE REVIEW

**Review by roaksoax — APPROVED** [review]
lgtm!

**Comment by dliappis** [comment]
@logstashmachine backport 8.12

**Comment by dliappis** [comment]
@logstashmachine backport 8.11

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Pull request merged**
