### PR TITLE
Stop filterworker and outputworker from crashing

### PR DESCRIPTION
**Pull request by xebab**
When an exception is thrown during event processing, logstash may stop accepting data or crash altogether (cf. LOGSTASH-1353, LOGSTASH-1440 or LOGSTASH-1872).

I have commited two changes that make logstash continue working after encountering an exception. To test the patches, you can use the following configs.

For the filterworker case:

```
input {
  generator {
    lines => [
      "A%C3O",
      "foobar"
    ]
    count => 1
  }
}
filter {
  urldecode { }
  kv { }
}
output {
  stdout { }
}
```

For the outputworker case:

```
input {
  generator {
    lines => [
      "A%C3O",
      "foobar"
    ]
    count => 1
  }
}
filter {
  urldecode { }
}
output {
  stdout { codec => json {} }
}
```

Please consider including these patches in the next release. Thanks.

### CODE REVIEW

**Comment by thomdixon** [comment]
This seems to work quite well for us. Would be nice to see it merged. @xebab can you do their whole CLA thing?

**Comment by xebab** [comment]
Thanks @thomdixon for pointing out this CLA issue to me. I was not aware of that. I have just signed the stuff so I hope this can get merged now.

**Comment by purbon** [comment]
test this please

**Comment by purbon** [comment]
@xebab The code looks good, but can you also add some test in the pipeline_spec (https://github.com/elasticsearch/logstash/blob/master/spec/core/pipeline_spec.rb) that test this functionality?

To test that you can use mocks from rspec as described https://relishapp.com/rspec/rspec-mocks/docs

**Comment by purbon** [comment]
test this please

**Comment by purbon** [comment]
@xebab I was trying to test this PR and found there is no Rakefile, do you know why ? could you update the PR to be in sync with master?

**Comment by suyograo** [comment]
Closing this issue since the code has deviated quite a bit and we will not be able to add this feature now.

**Pull request closed without merging**
