### PR TITLE
Fix for chroot not getting supplemental groups

### PR DESCRIPTION
**Pull request by coolacid**
linux chroot doesn't get the supplemental groups before dropping privileges. As such, we need to pull it from /etc/group and tweak it so that we can send them to chroot. 

Original report came from @spuder on irc -- here is his GIST report: 

https://gist.github.com/spuder/a1c3c7d10ce129507858

Spuder tested this and reported it working. Should work on other systems that use sysv init.

### CODE REVIEW

**Comment by sdklein** [comment]
+1 for the solution. I tested this pull request on CentOS 7 and it worked as expected.

**Comment by franklinwise** [comment]
When is this getting merged?

**Comment by jhoff909** [comment]
Curious when this is going to get merged?  Like others, I can't imagine that most folks using logstash to read files aren't running into this and spending a lot of time either figuring it out or reading posts like the above...

**Comment by vasti** [comment]
Variable `HOME` is exported without setting value to it. There's `HOME=${LS_HOME}` on master.
I get error _No SINCEDB_DIR or HOME environment variable set, I don't know where to keep track of the files I'm watching. Either set HOME or SINCEDB_DIR in your environment, or set sincedb_path in in your Logstash config for the file input with path_ because of that.

**Comment by jordansissel** [comment]
I think we've had enough folks report that this patch works for them that I am ok to merge it.

**Pull request closed without merging**
