### PR TITLE
Support for UTF-16 and other multi-byte-character logfiles

### PR DESCRIPTION
**Pull request by erwindon**
When `config.support_escapes: true` is set in logstash.yaml, escape characters can be used in any string, most notably the string "delimiter" from input.file.
This works great for traditional logfiles under Windows/Mac/Unix.
But for modern logfiles, produced in a multibyte characterset, this facility is still insufficient.
e.g. under UTF-16LE the delimiter is actually "\r\0\n\0", but that format cannot be specified. I expect the same problems for the UTF-16BE, UTF-32BE, UTF-32LE, UTF-16, UTF-32, UCS-2BE, UCS-4BE or UCS-4LE character sets.

The suggested solution in this PR is simple:
Update [logstash-core/lib/logstash/config/string_escape.rb] to support "\0".

### CODE REVIEW

**Comment by karmi** [comment]
Hi @erwindon, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/logstash/pull/9702.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by erwindon** [comment]
@karmi, I have updated my Github profile with these addresses and confirmed them.

**Comment by erwindon** [comment]
done requested change

**Comment by Res260** [comment]
Any update on this PR? I stumbled upon the very same problem and for this reason I can’t import my data.
https://discuss.elastic.co/t/delimiter-field-behaving-weirdly-with-n-char-for-the-line-codec-with-utf-16/186341/12

**Review by yaauie — APPROVED** [review]

**Comment by erwindon** [comment]
@yaauie what can this PR break? none are mentioned here...

**Comment by yaauie** [comment]
I've merged this, so we certainly have a path forward for LS 8.

However, I would classify this as a breaking change, if a small edge-case: inputs that had the literal `\0` previously passed-through verbatim, and some users may be relying on this behavior.

As such, I am not directly back-porting this PR to the 7.x series. I have a local branch that changes the possible values for `config.support_escapes` to `disabled`, `minimal`, and `extended` (with aliases from `false => disabled` and `true => minimal`), which would allow a user to select a specific mode. I will get this checked in this week, once I get tests to green.

**Pull request merged**
