### PR TITLE
#7081 up Kafka IT version to 0.10.2.1

### PR DESCRIPTION
**Pull request by original-brownbear**
5x rebase of #7088

### CODE REVIEW

**Comment by suyograo** [comment]
@original-brownbear for 5.x we don't need to update to 0.10.2.1 since we are still supporting only the 0.10 version of Kafka. The new version will be shipped in 6.x. 

Is Kafka 0.10.2.1 client compatible with 0.10.0.0 broker? do you know?

**Comment by original-brownbear** [comment]
@suyograo yes it's compatible with all `0.10.x` :)

**Comment by suyograo** [comment]
Cool this should be good to merge when travis passes then. Ideally, we should test for both versions of Kafka here (0.10.0.0) and (0.10.2.0) but we can save that up for our new integration test changes

**Comment by original-brownbear** [comment]
@suyograo merging then :)

**Pull request closed without merging**
