### PR TITLE
Support ironbank docker build

### PR DESCRIPTION
**Pull request by kaisecheng**
## Release notes

[rn:skip]

## What does this PR do?

This commit adds a rake task to generate ironbank docker build context. 
Run `rake artifact:dockerfile_ironbank`. The output can be found in build/logstash-ironbank-$VERSION-docker-build-context.tar.gz

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- I have tested `make public-dockerfiles_full`, `make public-dockerfiles_oss`, `make public-dockerfiles_ubi8` and `rake artifact:dockerfile_ironbank` to generate build context and run `docker build -t` to build four images successfully

## How to test this PR locally

Run `rake artifact:dockerfile_ironbank` to generate `build/logstash-ironbank-$VERSION-docker-build-context.tar.gz`
The content of .gz should be the same as GitLab [repository](https://repo1.dso.mil/dsop/elastic/logstash/logstash)
The `sha512` of `logstash-$VERSION-linux-x86_64.tar.gz` in `hardening_manifest.yaml` should be empty

## Related issues

- Relates: https://github.com/elastic/ironbank/issues/33

### CODE REVIEW

**Comment by kaisecheng** [comment]
https://logstash-ci.elastic.co/view/All/job/elastic+logstash+8.2+multijob-docker-acceptance/24/

**Review by robbavey — CHANGES_REQUESTED** [review]
Great stuff! 

Can we update the base image to `8.6`, as per the latest, and a couple of minor suggestions

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by kaisecheng** [comment]
@logstashmachine backport 8.3

**Comment by kaisecheng** [comment]
@logstashmachine backport 7.17

**Pull request merged**
