### PR TITLE
change version to 2.2.0.dev

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Comment by purbon** [comment]
LGTM

**Comment by suyograo** [comment]
@jsvd We should remove the `dev` part too and just point it to next 2.x release, which is 2.2

**Comment by jsvd** [comment]
@suyograo to be consistent, 2.x branch should be always be 2.x.0.dev, and 2.2 (when we create it) should be 2.2.0

**Comment by suyograo** [comment]
Closing this, as this needs to be 2.3 now

**Pull request closed without merging**
