### PR TITLE
Update jackson to 2.15.2

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Review by andsel — COMMENTED** [review]
The CI in failing due to bundler clash version, I don't if something else has to be backported or this PR rebased?

**Comment by jsvd** [comment]
@andsel fix here https://github.com/elastic/logstash/pull/15149

**Review by mashhurs — APPROVED** [review]
LGTM!

**Comment by mashhurs** [comment]
Jenkins test this again

**Comment by jsvd** [comment]
closing as jackson 2.15.2 depends on snakeyaml 2.0, and 8.9 branch still uses jruby 9.3 that depends on snakeyaml 1.x

**Pull request closed without merging**
