### PR TITLE
Docs: Fix links in translation

### PR DESCRIPTION
**Pull request by nik9000**
Mostly just adds zero width spaces to the Japanese translation to make asciidoctor happy.

### CODE REVIEW

**Comment by nik9000** [comment]
@karenzone, like the last one, this should be pretty close to a noop.

**Comment by karenzone** [comment]
@nik9000 Is this for 5.4 and 5.3? Others?

**Comment by nik9000** [comment]
> @nik9000 Is this for 5.4 and 5.3? Others?

Just those two!

**Comment by nik9000** [comment]
@karenzone, could you run the magic backport tool for this one too?

**Comment by nik9000** [comment]
I figured out how!

**Pull request merged**
