### PR TITLE
 #4640 make Event#clone clone metadata as well

### LINKED ISSUE #4640: `LogStash::Event#clone` should also clone the `@metadata`
The ruby event implements a custom `#clone` method, the code return a newly created object using the `@data` instance variable as the initial hash. This has the side effect of not cloning the `@metadata`, some filter use the clone and will drop any associated `@metadata` when the event goes through the filter chain.

original issue: https://github.com/logstash-plugins/logstash-filter-dns/issues/17
https://github.com/logstash-plugins/logstash-filter-dns/blob/master/lib/logstash/filters/dns.rb#L68

### PR DESCRIPTION
**Pull request by original-brownbear**
Fixes #4640 

* Add cloned metadata to cloned data map
* Copy (and slightly adjust for 5.x) tests from https://github.com/elastic/logstash/pull/5656/files#diff-42cd4d2f6f981839921777c8e4a5ba2bR662

### CODE REVIEW

**Comment by original-brownbear** [comment]
@jsvd hmm damn I was gonna ask you the reverse, "should we backport this to 6.0?" :D 
My reasoning was that in #4640 this was seen as an outright "bug" and I'm just fixing a bug here. 
I don't think I know enough to make that call here though :(

**Comment by jsvd** [comment]
I'm ok with calling this a bug - the issue and this PR are indeed marked as `bug` - which means we should place the fix in 6.0 AND 5.6, so that a 5.6.1 will have it (if it's ever released)

**Comment by original-brownbear** [comment]
@jsvd alright then, (last chance :D)  I'll go ahead and merge + backport?

**Comment by jsvd** [comment]
yes please, LGTM (please add the other two version tags)

**Pull request closed without merging**
