### PR TITLE
bump version 1.5.0.rc3

### PR DESCRIPTION
**Pull request by colinsurprenant**
this is to merge in the 1.5 branch when ready to release RC3

### CODE REVIEW

**Comment by colinsurprenant** [comment]
this is to merge in the 1.5 branch when ready to release RC3

**Comment by wiibaa** [comment]
Any chance to find a solution in the version format for https://github.com/logstash-plugins/logstash-input-log4j/issues/5#issuecomment-79474870 ?

**Comment by purbon** [comment]
I agree somehow with @wiibaa, we might give it a try, or at less know why we're not using the "right" version scheme. According to http://semver.org/ the right version schema is X.Y.Z-IdentifierN, but not sure if this is a version schema where rubygems is going to be happy.

**Comment by suyograo** [comment]
@wiibaa @purbon agreed. We need to stick to `X.Y.Z-prerelease`. My bad for not following it

**Comment by purbon** [comment]
@colinsurprenant @suyograo do we want to use an snapshot label before we do the final RC3? @suyograo already proposed this in #2949 ... thoughts?

**Comment by colinsurprenant** [comment]
nope. Rubygems uses strict dot delimited notation. In fact, to avoid any sorting order problem if going over rc9 we should do 1.5.0.rc.3. 

This is different from semver which uses an hyphen to denote pre release versions.

**Comment by purbon** [comment]
From the issue @wiibaa reported #2937, he reports ruby-maven having issues with the way rubygems handles versions, so then the jars gets problematic somehow .... what do you think on this issue @colinsurprenant ?

**Comment by colinsurprenant** [comment]
I just commented on #2937, I don't think the problem is related to ruby-maven but simply to the fact that **pre-released* gem version will not get installed when fetching gemspec dependencies...

**Comment by colinsurprenant** [comment]
ok, resolution path found see https://github.com/elastic/logstash/issues/2937#issuecomment-90608786

**Comment by purbon** [comment]
I close this as in #2958 I included this code plus a number in the snapshot label, so we know the precedence in case of different snapshots releases.

**Pull request closed without merging**
