### PR TITLE
Fix showing deprecation warning of command line flags

### PR DESCRIPTION
**Pull request by kaisecheng**
This PR allows warning message from [clamp](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/patches/clamp.rb#L80) shows in log file. 
The reason of logger failed to log message is that logger is used before log4j setup. Putting log4j setup to an earlier stage, Runner#run, allows logger to function in clamp but this cause another problem of losing user config, `--path.log`, which is necessary for a proper log4j setup.

This PR proposes to store the deprecation message in memory and remove them once it shows to users.

Log should show
```
Sending Logstash logs to /Users/xxx/logstash/logs which is now configured via log4j2.properties
[2021-01-25T13:48:40,263][WARN ][logstash.runner          ] DEPRECATION WARNING: The flag ["--debug"] has been deprecated, please use "--log.level=debug" instead.
```

Fixed: https://github.com/elastic/logstash/issues/12587

### CODE REVIEW

**Comment by kaisecheng** [comment]
jenkins test this please

**Review by andsel — COMMENTED** [review]
I saw that https://github.com/elastic/logstash/blob/0bcb95c6b25638fa305d754bd221c63739467c08/logstash-core/spec/logstash/runner_spec.rb#L505-L509 test this deprecation logging but probably this worked because in unit test the logger is already set up, may we could do something similar with an integration test like in https://github.com/elastic/logstash/blob/master/qa/integration/specs/deprecation_log_spec.rb, which effective run a real Logstash instance?

**Comment by kaisecheng** [comment]
@andsel I have considered writing a test for deprecation message, but in the end, the deprecating option will be removed in one day or soon. The test case will be invalid along with the deprecation. Do you think we should have one and maintain it?

**Comment by andsel** [comment]
@kaisecheng with this in mind probably we don't need it for that specific deprecated flags, my concern was only related to grant we don't have regression on this part in future. Given your explanation I'm ok to skip the introduction of a test on this.

**Pull request merged**
