### PR TITLE
API: avoid starting webserver when `http.enabled=false`

### PR DESCRIPTION
**Pull request by yaauie**
In some workflows such as simple file manipulation, starting a webserver is
unnecessary overhead, and we should be able to avoid it.

Here we introduce a new parameter `http.enabled`, which defaults to `true` to
maintain the existing functionality.

Resolves: elastic/logstash#9408
Closes: elastic/logstash#11525

TODO:
 - [ ] ~when `http.enabled=false` and x-pack internal monitoring is configured, error or log helpfully~ _EDIT: the metrics input uses internal data structures directly, and does not need the API._

### CODE REVIEW

**Comment by yaauie** [comment]
I am unsure what behaviour we desire when `http.enabled=false` within a configuration that also includes monitoring configuration (which relies on the HTTP API); options I see are:
 - `ERROR`: prevent Logstash from starting
 - `WARN`: warn and do not start monitoring pipeline
 - `WARN`: warn, but allow monitoring pipeline to start attempting (and failing) to collect metrics
 - `SILENT`: allow monitoring pipeline to start attempting (and failing) to collect metrics

**Comment by colinsurprenant** [comment]
I would prefer 
`WARN`: warn and do not start monitoring pipeline
but
`ERROR`: prevent Logstash from starting
will probably avoid any kind of confusion, and the user will then have the choice to explicitly disable monitoring and then retry if he really turn off http.

**Comment by colinsurprenant** [comment]
Changes so far LGTM, Pending decision on the above discussion.

**Comment by jsvd** [comment]
With Logstash already having so many parameters and settings, can we discuss the need for this one? Looking at the initial issue, the argument is:

>  I guess that we don't want to start a webserver for simple file manipulation for instance, or local transformations.

What is the inconvenience that is being felt by having the webserver started in these scenarios?

**Comment by colinsurprenant** [comment]
@jsvd I haven't witnessed that request but I can see that for security reasons some users would prefer not to have any network ports open into LS if not needed?

**Comment by yaauie** [comment]
> What is the inconvenience that is being felt by having the webserver started in these scenarios?

I've actually had this issue pop up a couple of times from community members and customers at ElasticON tour stops, where people were looking for the opportunity to eliminate perceived overhead, especially in situations where they were running many short-lived Logstash processes to transform small already-complete sets of data. Even though Logstash is primarily designed around infinite streams of data (where ongoing monitoring and visibility is key), it is still used pretty heavily for one-off transforms.

As a side note, this functionality originated in an issue by a core logstash contributor tagged with "good first issue" and "enhancement", so when a solution came in from a first-time community contributor (#11525), I offered to help them drive it home.

**Comment by yaauie** [comment]
@colinsurprenant would you mind reviewing once more? We don't need to add a warning to x-pack internal monitoring, since it uses internal data structures instead of routing through the API and therefore doesn't need the webserver to be running.

**Pull request closed without merging**
