### PR TITLE
#7091 Dockerized kafka

### PR DESCRIPTION
**Pull request by original-brownbear**
Dockerized Kafka as step 1 for #7093 

Note:
* Using random ports is very tricky when it comes to Kafka and Zookeeper if we want to retain compatibility with OSX Docker unfortunately. This requires finding a free port for Zookeeper on the host machine first and then setting up Zookeeper and Kafka accordingly (we cannot simply bind zookeeper via Docker `--bind` as Kafka and the rspec tests on the host need to "see" Zookeeper at the same address).
  * Solutions that would work if we need it (I don't think we do right now, but we could use this if we ever had to)
     * Run Logstash in its own Docker container as well and make the tests interact with the filesystem and shell of that container => makes the networking 100% portable across standard Docker, OSX Docker and even Swarm

### CODE REVIEW

**Comment by suyograo** [comment]
+1, based on our zoom discussion with @andrewvc let's move forward with this approach.

**Comment by original-brownbear** [comment]
@suyograo @andrewvc now it's green :) Needed to hack via

```bash
yes | gem uninstall -q -i /home/travis/.rvm/gems/jruby-1.7.25@global bundler
```

:)

**Comment by original-brownbear** [comment]
@suyograo @andrewvc cleaned up the solution, see my edit to the PR description -> I don't think more sophisticated networking should be in step 1. This approach is the only one that I see working across OSX and Linux and that doesn't require a bunch of hacky code :)

**Comment by suyograo** [comment]
Code LGTM. Most other integration tests failed on the last run. I kicked off a build again, we need to see whats up.

**Comment by original-brownbear** [comment]
@suyograo failed again, strange I'm looking into it. Looks like I deleted some file that now messes up the teardown. Sec :)

**Comment by original-brownbear** [comment]
@suyograo I think I got it, tried to be a little drier than possible (the `settings.get("input")` didn't work in non Kafka specs -> fixed now).
At least I found two small issues while I was at it :)

**Comment by original-brownbear** [comment]
@suyograo all green, see https://github.com/elastic/logstash/pull/7093/commits/bb33cee7c38e71a8d2134cbe634c4fc147666a82 for changes I made now

**Comment by suyograo** [comment]
@original-brownbear squash and merge away :)

**Comment by suyograo** [comment]
@original-brownbear this should be backported to 5.x as well..

**Comment by original-brownbear** [comment]
@suyograo got it, put on the list for tomorrow :)

**Pull request closed without merging**
