### PR TITLE
refactored all gem/bundler code into logstash/bundler.rb and moved patches into logstash/patches

### PR DESCRIPTION
**Pull request by colinsurprenant**

### CODE REVIEW

**Comment by colinsurprenant** [comment]
@ph @jsvd  review please :) I'd like this cleanup to be merged so I can add the local `.gem` file installation support on top of it!

**Comment by jsvd** [comment]
I haven't run the drip code, but otherwise seems good and tests pass. I'll remove the 1.5.0 label since it hasn't been merged yet.
LGTM

**Comment by colinsurprenant** [comment]
@ph ?

**Comment by ph** [comment]
I've moved a few stuff also to the patch directory. I'll review this and make any necessary changes.

**Comment by purbon** [comment]
@colinsurprenant is there something preventing us to merge this? waiting @ph review?

**Comment by ph** [comment]
LGTM merge away

**Comment by colinsurprenant** [comment]
ok, lets rebase and :shipit:

**Comment by ph** [comment]
@colinsurprenant can you rebase it?

**Comment by colinsurprenant** [comment]
rebased. merging.

**Pull request merged**
