### PR TITLE
Fix 2.0 branch test by updating the Gemfile and the lock file

### LINKED ISSUE #3946: Default plugins integration test breaks in 2.0 branch
From: http://build-eu-00.elastic.co/view/LS%202.0/job/Logstash_Default_Plugins_20/228/console

```
...127.0.0.1 - - [21/Sep/2015:07:31:02 CEST] "HEAD /good HTTP/1.1" 200 0
- -> /good
.....................................................................................................................................................................................................................................................................................................................................................................

Failures:

  1) LogStash::Filters::GeoIP returned object identities should dup the objects
     Failure/Error: let(:geo_data) { plugin.get_geo_data_for_ip("8.8.8.8") }
     NoMethodError:
       undefined method `city' for nil:NilClass
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-1.1.1/lib/logstash/filters/geoip.rb:187:in `get_geo_data_for_ip'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-1.1.1/spec/filters/geoip_spec.rb:228:in `geo_data'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-1.1.1/spec/filters/geoip_spec.rb:237:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

### PR DESCRIPTION
**Pull request by purbon**
This fix #3946 by updating the Gemfile and the lock file to fetch the last released plugins.

Issues are explained at https://github.com/elastic/logstash/issues/3946#issuecomment-142888343

## Important

This PR should only be merged and tested with 2.0 branch.

### CODE REVIEW

**Comment by purbon** [comment]
@jsvd either you or @ph would be nice if you could review this, this fix the broken 2.0 test for now.

**Comment by ph** [comment]
LGTM, I have check the dependencies I know off and we are using the right snapshot and the right stud version.

**Comment by purbon** [comment]
cool, thanks @ph

**Comment by purbon** [comment]
Merged manually https://github.com/elastic/logstash/commit/7372c2ac3abcb8d8ab91d89ca7e25fcd018176d4

**Pull request closed without merging**
