### PR TITLE
Doc: Reset breaking changes and release notes for 9.0

### PR DESCRIPTION
**Pull request by karenzone**
### Release notes
[rn:skip] 

### Description
Removes 8.x series release notes from the 9.0 branch to clear the way for populating 9.0 with beta, rc, and 9.0.0 release notes as they become available.

Ideally, we'll remove 8.x release notes sooner rather than later so that we can cut out the wasted effort of forwardporting additional 8.x release notes and prevent inconsistent information experiences across product docs. 

### Previews
* https://logstash_bk_16603.docs-preview.app.elstc.co/guide/en/logstash/master/breaking-changes.html
* https://logstash_bk_16603.docs-preview.app.elstc.co/guide/en/logstash/master/releasenotes.html

### Related: 
* https://github.com/elastic/docs-projects/issues/257
* Follow up work: #16604

### CODE REVIEW

**Review by karenzone — COMMENTED** [review]
Note to self @karenzone: 
- Look at folding 6.3 bc into 6.0 topic
- How far back do we want to keep breaking changes?

**Comment by karenzone** [comment]
### Note to reviewers:
This PR follows the recommendation that we hold PRs to a smaller set of changes for ease of review.
There's more work to be done and I've started an issue to capture it: https://github.com/elastic/logstash/issues/16604

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by karenzone** [comment]
16524

**Pull request merged**
