### PR TITLE
Add support for using kibana dashboard import api

### PR DESCRIPTION
**Pull request by guyboertje**
- Add support for versioned folders below 'module'/configuration/kibana
- Rename cef to module_test_files/tester and simplify it.
- Remove skips on tests using above modules test files.
- In pipeline.rb, moved method default_logging_keys to the base class,
  it was being called from BasePipeline during a config-test.
- In modules_common, added a backtrace to LogStash::ConfigLoadingError
  for better debugging
- Improve layout when user_lines et al were empty in logstash_config

### CODE REVIEW

**Comment by guyboertje** [comment]
Not sure why the integrations tests failed.

**Comment by jsvd** [comment]
my first attempt at installing the arcsight module:

```
% bin/logstash --modules arcsight
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logs which is now configured via log4j2.properties
[2017-07-06T13:52:26,778][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2017-07-06T13:52:27,257][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-07-06T13:52:27,838][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>LogStash::ConfigLoadingError, :message=>"Failed to parse the module configuration: [[401] ]", :backtrace=>["/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:319:in `perform_request'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/elasticsearch_client.rb:64:in `head'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/elasticsearch_client.rb:34:in `can_connect?'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/elasticsearch_client.rb:114:in `can_connect?'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/modules_common.rb:54:in `block in pipeline_configs'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/modules_common.rb:38:in `pipeline_configs'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/source/modules.rb:16:in `pipeline_configs'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/source_loader.rb:59:in `block in fetch'", "org/jruby/RubyArray.java:2481:in `collect'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/source_loader.rb:58:in `fetch'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:147:in `converge_state_and_update'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
[2017-07-06T13:52:27,844][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fetch the configuration, message: Failed to parse the module configuration: [[401] ]", :backtrace=>["/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:154:in `converge_state_and_update'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
```

This is because I had not set credentials properly.

I edited `config/logstash.yml` like described in https://github.com/elastic/x-pack-logstash/blob/master/modules/README.md#logstashyml, replacing netflow with arcsight and setting the user `elastic` and its password but I still get 401.
I tried with `logstash_system` but it didn't work.
Also, minor detail, the yaml example is not correctly indented, you can't just copy paste and change values.

I still am unable to start logstash with the modules. Looking at tcpdump, I see:

```
HEAD /_80815d1b18b84b5832550aaa98825482c617aee9edc3d980b531e11e29a48d45 HTTP/1.1
Connection: Keep-Alive
Content-Type: application/json
Host: localhost:9200
User-Agent: Manticore 0.6.1
Accept-Encoding: gzip,deflate

HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="security" charset="UTF-8"
content-type: application/json; charset=UTF-8
content-length: 499
```

So the credentials aren't being included in the request. My config/logstash.yml looks like:

```
modules:
  - name: arcsight
    var.output.elasticsearch.host: "localhost"
    var.output.elasticsearch.user: "elastic"
    var.output.elasticsearch.password: "elastic"
    var.input.tcp.port: 5606
```

**Comment by jsvd** [comment]
kibana also reports:

```
 log   [13:11:16.382] [error][client][connection] Error: 140736236336064:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1493:SSL alert number 46
140736236336064:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1216:
```

I'm pretty sure I'm doing something wrong here, but I'm finding the documentation + error messages not very helpful.

**Comment by jsvd** [comment]
testing with an elasticsearch and kibana that don't have x-pack installed I get:

```
% bin/logstash
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logs which is now configured via log4j2.properties
[2017-07-06T16:14:27,800][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2017-07-06T16:14:28,179][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-07-06T16:14:28,792][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>I18n::MissingInterpolationArgument, :message=>"missing interpolation argument :elasticsearch_hosts in \"Failed to import module configurations to Elasticsearch and/or Kibana. Module: %{module_name} has Elasticsearch hosts: %{elasticsearch_hosts} and Kibana hosts: %{kibana_hosts}\" ({:module_name=>\"arcsight\", :kibana_hosts=>\"[\\\"localhost:5601\\\"]\"} given)", :backtrace=>["/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n/config.rb:74:in `block in missing_interpolation_argument_handler'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n/interpolate/ruby.rb:29:in `block in interpolate_hash'", "org/jruby/RubyString.java:2537:in `gsub'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n/interpolate/ruby.rb:21:in `interpolate_hash'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n/interpolate/ruby.rb:17:in `interpolate'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n/backend/base.rb:153:in `interpolate'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n/backend/base.rb:41:in `translate'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n.rb:157:in `block in translate'", "org/jruby/RubyKernel.java:1120:in `catch'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/i18n-0.6.9/lib/i18n.rb:153:in `translate'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/modules_common.rb:77:in `block in pipeline_configs'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/modules_common.rb:38:in `pipeline_configs'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/source/modules.rb:16:in `pipeline_configs'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/source_loader.rb:59:in `block in fetch'", "org/jruby/RubyArray.java:2481:in `collect'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/config/source_loader.rb:58:in `fetch'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:147:in `converge_state_and_update'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
[2017-07-06T16:14:28,800][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fetch the configuration, message: missing interpolation argument :elasticsearch_hosts in \"Failed to import module configurations to Elasticsearch and/or Kibana. Module: %{module_name} has Elasticsearch hosts: %{elasticsearch_hosts} and Kibana hosts: %{kibana_hosts}\" ({:module_name=>\"arcsight\", :kibana_hosts=>\"[\\\"localhost:5601\\\"]\"} given)", :backtrace=>["/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:154:in `converge_state_and_update'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/Users/joaoduarte/projects/elastic/logstash/build/logstash-6.0.0-alpha3-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
```

with config/logstash.yml

```
modules:
  - name: arcsight
    var.output.elasticsearch.host: "localhost"
    var.input.tcp.port: 5606
```

**Comment by jsvd** [comment]
for reference, I'm using the following shas:
elasticsearch 0170e0e8d3fa210a539737c91251dbdd520bb458 (specific commit since latest master does not work with latest kibana master [context here](https://github.com/elastic/elasticsearch/pull/25375))
kibana 411593c738333c114bcf38d7be1108bc6ea849f0 (master)
x-pack-kibana d289508faa247e4988e25a208a635cac13b7d3ed (master)
x-logstash-pack 101f943ff7f11d6fece908891867c5de36d8a50d (master)
logstash c1e9f72bbb4c6847d8bf146ec17f83657e849903 (this PR)

**Comment by suyograo** [comment]
@jsvd I was able to get the modules working with the following steps:
1. Install Kibana 6.0.0-alpha3 snapshot from https://snapshots.elastic.co/downloads/kibana/kibana-6.0.0-alpha3-SNAPSHOT-darwin-x86_64.tar.gz
2. Install ES snapshot from  https://snapshots.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-alpha3-SNAPSHOT.tar.gz
3. Install x-pack *only* on LS with this PR.

After that, I did:

```
bin/logstash --modules arcsight -Marcsight.var.inputs=tcp
```

The default for this module is a Kafka input, so for local testing you can use tcp input which listens on port 5000 by default.

I then checked 

```
sudo lsof -PiTCP -sTCP:LISTEN
```

to see if the port is open, and it was.

Also, navigating to Kibana shows that the dashboard and viz are loaded.

**Comment by suyograo** [comment]
I'm trying now with x-pack on ES and Kibana (with security enabled)

**Comment by suyograo** [comment]
@jsvd Added some commits to enable auth in Kibana. SSL is a different story. I think we should first optimize for x-pack on LS case and then deal with auth in Kibana.

**Comment by suyograo** [comment]
Tried with `bin/logstash --modules arcsight -Marcsight.var.inputs=tcp -Marcsight.var.kibana.username=elastic -Marcsight.var.kibana.password=foo`

**Comment by jsvd** [comment]
I pushed commit 0d724d3 that adds support for authentication in es and kibana. this means that if a logstash module wants to talk with es and kibana and authentication is enabled through x-pack security or other means, the module will work.

Example usage will be: 
```
bin/logstash --modules testmodule \
 -Mtestmodule.var.kibana.username=kibana_user \
 -Mtestmodule.var.kibana.password=kibana_password \
 -Mtestmodule.var.output.elasticsearch.user=elasticsearch_user \
 -Mtestmodule.var.output.elasticsearch.password=elasticsearch_password
```

**Comment by jsvd** [comment]
Current failure scenarios and feedback:

#### Wrong ES credentials:

```
[2017-07-07T18:46:31,121][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>LogStash::ConfigLoadingError, :message=>"Failed to parse the module configuration: [[401] ]", :backtrace=>["/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'", "/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:319:in `perform_request'", "/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'", "/tmp/elastic/logstash/logstash-core/lib/logstash/elasticsearch_client.rb:71:in `head'", "/tmp/elastic/logstash/logstash-core/lib/logstash/elasticsearch_client.rb:41:in `can_connect?'", "/tmp/elastic/logstash/logstash-core/lib/logstash/elasticsearch_client.rb:121:in `can_connect?'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/modules_common.rb:54:in `block in pipeline_configs'", "org/jruby/RubyArray.java:1734:in `each'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/modules_common.rb:38:in `pipeline_configs'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/source/modules.rb:16:in `pipeline_configs'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/source_loader.rb:59:in `block in fetch'", "org/jruby/RubyArray.java:2481:in `collect'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/source_loader.rb:58:in `fetch'", "/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:147:in `converge_state_and_update'", "/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/tmp/elastic/logstash/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
[2017-07-07T18:46:31,125][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fetch the configuration, message: Failed to parse the module configuration: [[401] ]", :backtrace=>["/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:154:in `converge_state_and_update'", "/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/tmp/elastic/logstash/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
```

#### wrong kibana credentials:

```
[2017-07-07T18:48:08,373][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>LogStash::ConfigLoadingError, :message=>"Failed to parse the module configuration: [Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: [B@4a8fe79e; line: 1, column: 2]]", :backtrace=>["/tmp/elastic/logstash/logstash-core/lib/logstash/json.rb:41:in `jruby_load'", "/tmp/elastic/logstash/logstash-core/lib/logstash/modules/kibana_client.rb:15:in `initialize'", "/tmp/elastic/logstash/logstash-core/lib/logstash/modules/kibana_client.rb:90:in `safely'", "/tmp/elastic/logstash/logstash-core/lib/logstash/modules/kibana_client.rb:66:in `get'", "/tmp/elastic/logstash/logstash-core/lib/logstash/modules/kibana_client.rb:43:in `initialize'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/modules_common.rb:53:in `block in pipeline_configs'", "org/jruby/RubyArray.java:1734:in `each'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/modules_common.rb:38:in `pipeline_configs'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/source/modules.rb:16:in `pipeline_configs'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/source_loader.rb:59:in `block in fetch'", "org/jruby/RubyArray.java:2481:in `collect'", "/tmp/elastic/logstash/logstash-core/lib/logstash/config/source_loader.rb:58:in `fetch'", "/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:147:in `converge_state_and_update'", "/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/tmp/elastic/logstash/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
[2017-07-07T18:48:08,387][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fetch the configuration, message: Failed to parse the module configuration: [Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: [B@4a8fe79e; line: 1, column: 2]]", :backtrace=>["/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:154:in `converge_state_and_update'", "/tmp/elastic/logstash/logstash-core/lib/logstash/agent.rb:89:in `execute'", "/tmp/elastic/logstash/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/tmp/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
```

**Comment by jsvd** [comment]
Out of scope for this PR and feature, but there should be a way to validate the settings in the modules. setting an option like `-Mtestmodule.var.output.elasticsearch.username=elastic` looks correct but essentially causes the username to not be set, giving you errors about crendentials, since the username setting is `testmodule.var.output.elasticsearch.user` and not `testmodule.var.output.elasticsearch.username`

**Comment by suyograo** [comment]
Tested on my side as well. Merging on behalf of Guy.

**Comment by suyograo** [comment]
@jsvd tried a manual cherry-pick to 5.x, but it is non-trivial :) Since you understand the loader stuff, can you do a backport to 5.x?

**Pull request merged**
