### PR TITLE
Update 2.2 branch with Gemfile and .lock file

### PR DESCRIPTION
**Pull request by suyograo**

### CODE REVIEW

**Comment by jsvd** [comment]
since 2 days ago many plugins have been updated:

```
12c12
< logstash-codec-multiline (2.0.4)
---
> logstash-codec-multiline (2.0.5)
16c16
< logstash-codec-rubydebug (2.0.4)
---
> logstash-codec-rubydebug (2.0.5)
21c21
< logstash-filter-date (2.0.2)
---
> logstash-filter-date (2.1.1)
57c57
< logstash-input-log4j (2.0.4)
---
> logstash-input-log4j (2.0.5)
75c75
< logstash-output-elasticsearch (2.3.0)
---
> logstash-output-elasticsearch (2.3.1)
78c78
< logstash-output-file (2.2.1)
---
> logstash-output-file (2.2.2)
83c83
< logstash-output-http (2.0.5)
---
> logstash-output-http (2.1.0)
96c96
< logstash-output-s3 (2.0.3)
---
> logstash-output-s3 (2.0.4)
```

not sure if any of these warrants an update of the lock file

**Comment by jsvd** [comment]
at least logstash-filter-date make sense to update since it includes the new year's bugfix

**Comment by suyograo** [comment]
@jsvd I just wanted to get a first pass in to create a new lock file so we can start creating CI jobs. I was waiting for file input changes to be published, so i can do a second pass. Subsequent updates will be straightforward.

**Comment by jsvd** [comment]
LGTM

**Comment by suyograo** [comment]
merged via 17b0a9d565afb97ae516237b5fc457f38dfa2de9

**Pull request closed without merging**
