### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by suyograo** [comment]
@jsoref thanks for this! Before we start reviewing, can you please perform step 2 of https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by jsoref** [comment]
@suyograo: I've submitted the cla...

**Comment by suyograo** [comment]
LGTM, all tests pass. @jsoref thank you for this.

**Comment by suyograo** [comment]
@jsoref our of curiosity, did you use an IDE for this to spellcheck?

**Comment by jsoref** [comment]
No. It's a series of shell scripts.
One script finds files that might be interesting and pipes them into another script.
That script converts tokens into words (splitting FooBar into Foo Bar, etc.) and takes a those tokens,  excludes words if they're in a dictionary, and then sorts them and groups them by word family.
The last step is manual: deciding if I know it's a word or grepping to decide if it's correct or misspelled and the replacement.

**Pull request merged**
