### PR TITLE
Acknowledgement bus

### PR DESCRIPTION
**Pull request by rv2673**
Merge request with possible implementation solving: https://github.com/elastic/logstash/issues/8514

* I created a bus where at the end of the workerloop the events in the inflight batch are acknowledged based on the presence of an acknowledgetoken in the event. That token(which contains a plugin generated id) is/can be added on event creation.
* Plugins can register themselves(which gives them a token generator). When they add token to an event they get notified when it reaches the end of a pipeline.
*  It should even work with cross pipeline communication and the original input plugin is notified of the "clone" when crossing pipeline boundries so the plugin knows it might need to wait for another acknowledge to have the event fully processed.
* For plugins that clone an event in a pipeline(like the clone plugin) there is no need for notification, since the original event(that we want to have acknowledged) always reaches the end of the pipeline(though might be cancelled).
* It works with both the memory and persisted queues
* The token can only be added on event creation so filter plugins cannot modify the event(they can cancel the event but it will reach the end of the pipeline) and therefore will still have token at the end of the loop.
* It should be backwards compatible and can opted in by plugins

I didn't go the route of a new queueless type, since an acknowledgable plugin then would force all pipelines(in the case of cross pipeline communication) to all have that queue type. Nor did I integrate it with the current acked queue since it was extremely hard to get a global reference to something like an acknowledgebus to propagate down to the concrete queue implementations and this would create more coupling.

*Open ideas/questions*:
Possible extension idea which I haven't worked out(but might good idea in case of persisted queue). To add expiration to the acknowledgement token. So if deserialized/read from queue from (persisted) queue but is expired we could immediately cancel the event since it most likely will be retried. 

*TODOS*:
Add more testing

### CODE REVIEW

**Comment by logstashmachine** [comment]
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

**Comment by rv2673** [comment]
>  Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
What does the title field in the signature mean?

**Comment by yaauie** [comment]
> What does the title field in the signature mean?

IIRC, It's just a job title, and can be anything describing what you do and who you do it for ("Individual Contributor" works, if you don't feel like disclosing your employer's title for you).

**Comment by rv2673** [comment]
@yaauie Thanks for clearing that up for me, it got me very confused.

**Pull request closed without merging**
