### PR TITLE
relocate logstash-core/api/ into logstash-core/lib/logstash/api/

### LINKED ISSUE #4574: Move the `logstash-core/lib/api` to `logstash-core/lib/logstash/api`
To be more consistent with the current architecture of logstash it should be move to `logstash-core/lib/logstash/api`

### PR DESCRIPTION
**Pull request by purbon**
Fixes #4574

### CODE REVIEW

**Comment by purbon** [comment]
@ph quick review on this? easy to be merge and keep working on other changes.

**Comment by ph** [comment]
Can we merge https://github.com/elastic/logstash/pull/4602 before, I would like to reduce the conflict in that branch :(

**Comment by purbon** [comment]
@ph I have no issue, some will need to pay the pain of merging .... happy to iron pending issues with you. Also good to merge if we open issues for pending questions.

**Comment by ph** [comment]
LGTM

**Pull request closed without merging**
