### PR TITLE
Update logging.asciidoc

### PR DESCRIPTION
**Pull request by anupamsingh24**

### CODE REVIEW

**Comment by anupamsingh24** [comment]
just corrected a typo in the website.

**Comment by jakelandis** [comment]
@anupamsingh24 - thanks for the PR

 I will get it merged if can you please sign https://www.elastic.co/contributor-agreement

**Comment by anupamsingh24** [comment]
@jakelandis - I have signed the contributor agreement. :)

**Comment by jakelandis** [comment]
@anupamsingh24 - thanks for the contribution !

**Pull request closed without merging**
