### PR TITLE
Fix link to mongodb output example plugin

### PR DESCRIPTION
**Pull request by michaelneale**
Plugins have been moved to their own org now.

### CODE REVIEW

**Comment by michaelneale** [comment]
I have signed the CLA form for this.

**Comment by purbon** [comment]
LGTM

@untergeek does this file and the related documentation still makes sense now that we have the new doc?

**Comment by untergeek** [comment]
No.  These old docs are pretty much safe to ignore at this point.

**Comment by purbon** [comment]
@untergeek good, thanks for the clarification.

**Comment by purbon** [comment]
@michaelneale we recently moved into a new documentation system as you can see with all the ascii docs inside the docs directory. As @untergeek said, there are now other parts of the documentation where this knowledge is tracked, starting by the ones in docs/asciidoc/static/contributing-to-logstash.asciidoc.

So I would close this PR as this files are going to be removed anyway. Is this ok for you?

**Comment by michaelneale** [comment]
Looks good to me.

**Pull request closed without merging**
