### PR TITLE
bump master version to 6.0.0-alpha3

### PR DESCRIPTION
**Pull request by suyograo**

### CODE REVIEW

**Comment by jordansissel** [comment]
Checking master for alpha2 presence:


* [x] versions.yml
* [ ] Gemfile.jruby-1.9.lock
* [ ] README.md
* [ ] docs/static/releasenotes.asciidoc
* [ ] docs/index.asciidoc
* [ ] Gemfile.lock
* [x] logstash-core/lib/logstash-core/version.rb
* [x] logstash-core/lib/logstash/version.rb
* [x] logstash-core-plugin-api/logstash-core-plugin-api.gemspec

What about docs, readme, and Gemfile lock changes?

**Comment by jordansissel** [comment]
if I check out this pr and look for alpha2 mentions:

```
⓿ pork(~/projects/logstash) pull/7343
% ack -l '6.0.0.alpha2'
Gemfile.jruby-1.9.lock
README.md
docs/static/releasenotes.asciidoc
docs/index.asciidoc
Gemfile.lock
```

**Comment by suyograo** [comment]
@jordansissel updated to include the README and docs. `Gemfile*` are created at runtime, we don't check them in for master.

**Comment by ph** [comment]
Could we make the doc generator use variable and versions.yml?

**Comment by jordansissel** [comment]
@suyograo LGTM

**Pull request merged**
