### PR TITLE
Turn off any jar-dependencies lookup when running install command with --local

### PR DESCRIPTION
**Pull request by ph**
Fixes: #6386

### CODE REVIEW

**Comment by jsvd** [comment]
```
jsvd@jsvd-VirtualBox:/tmp/test$ ls
6410.patch  logstash-5.1.1.tar.gz  logstash-filter-dissect-1.0.8.gem  logstash-filter-elapsed-4.0.0.gem
jsvd@jsvd-VirtualBox:/tmp/test$ tar -zxf logstash-5.1.1.tar.gz 
jsvd@jsvd-VirtualBox:/tmp/test$ cd logstash-5.1.1/
jsvd@jsvd-VirtualBox:/tmp/test/logstash-5.1.1$ patch -p1 <../6410.patch 
patching file lib/pluginmanager/install.rb
jsvd@jsvd-VirtualBox:/tmp/test/logstash-5.1.1$ bin/logstash-plugin install --local ../logstash-filter-elapsed-4.0.0.gem 
Validating ../logstash-filter-elapsed-4.0.0.gem
Installing logstash-filter-elapsed
Plugin not found, aborting
ERROR: Installation Aborted, message: Could not find arr-pm-0.0.10 in any of the sources
```

**Comment by ph** [comment]
I believe you are missing a commit in your 5.1.1 artifact https://github.com/elastic/logstash/commit/2a281730c177b6bb4a4610cdb15f159224cbf1f9

I've tested with a new artifact made from the master branch and it did work (I have tested it with the env variable)

```
✘ph@sashimi/tmp/pack-unpack/logstash-6.0.0-alpha1-SNAPSHOT JARS_SKIP="true" bin/logstash-plugin install ~/Downloads/logstash-filter-elapsed-4.0.0.gem                                                                                                                                                                     ⏎
Validating /Users/ph/Downloads/logstash-filter-elapsed-4.0.0.gem
Installing logstash-filter-elapsed
Installation successful

``

**Comment by jsvd** [comment]
I confirm that with both https://github.com/elastic/logstash/commit/2a281730c177b6bb4a4610cdb15f159224cbf1f9 and this patch the problem does not occur 👍

**Comment by ph** [comment]
The failling test seems to be unrelated.

**Comment by ph** [comment]
@jsvd Should I merge that?

**Comment by jsvd** [comment]
LGTM

**Comment by ph** [comment]
backported in 5.0 with 8ba2d7ad03540392170739e708210efddf444209

**Pull request closed without merging**
