### PR TITLE
Remove Travis builds (they have been replaced by Jenkins)

### PR DESCRIPTION
**Pull request by jakelandis**
Fixes: #8079

### CODE REVIEW

**Comment by jordansissel** [comment]
LGTM -- my 'test' was to checking that travis did not report any status on this commit.

**Comment by suyograo** [comment]
LGTM

**Comment by jakelandis** [comment]
6.0 backport

Jake Landis merged this into the following branches!

Branch | Commits
-------|--------
6.0 | a5f9c9b7b0cc9f5682072edf9d5874235bdf8bb0

**Comment by jakelandis** [comment]
5.6 backport 

Jake Landis merged this into the following branches!

Branch | Commits
-------|--------
5.6 | c3b3041c057ea4838118def8ffbca39cd146c631

**Comment by jakelandis** [comment]
5.5 backport

Jake Landis merged this into the following branches!

Branch | Commits
-------|--------
5.5 | 473f097f379b3c453ce1146a7b40d73e2a44734f

**Pull request closed without merging**
