### PR TITLE
Secret Store: Ability to set and use secret data from an encrypted data store

### PR DESCRIPTION
**Pull request by jakelandis**
Fixes #8657

Part 1: API and JavaKeyStore implementation (#8657)

Introduces the API to read/write/delete sensitive data from a secure store and includes a Java KeyStore implementation. Note - this commit does NOT integrate with the Logstash configuration or settings.

Part 2: Secret Store: SecretStoreFactory, SecureConfig, Obfuscation and X-JVM support (#8659)

*  Secret Store: SecretStoreFactory, SecureConfig, Obfuscation and X-JVM support

* Introduce a SecretStoreFactory to allow runtime definition of SecretStore implementation.
* Introduce a SecureConfig to allow simple configuration of different SecretStore implementaiton.
* Introduce random default password plus obfuscation. Best attempt at security through obscurity.
* Corrections / better support for x-JVM modification.

Part 3: Secret Store: SecretStore, SecretStoreFactory, JavaKeystore - refacactor (#8745)

* Adds more CRUD like operations for SecretStore API
* SecretStoreFactory Mirror API's CRUD operations
* Adds 'exists' to API to allow command line warning 'Overwrite ?'
* Minor readabiliy

Part 4: Integrate secret store with Logstash core (#8905)

This change introduces the command line tooling and hooks needed to allow Logstash to use the secret store. This change hooks into the same logic that the does the environment variable substitution. The commnad line mirrors the Elasticsearch command line, and is implemented primarily in Java.

### CODE REVIEW

**Comment by jakelandis** [comment]
Looking into the 3 test failures... (doesn't fail from IntelliJ :(  )

**Comment by jakelandis** [comment]
@jordansissel - I fixed the failing tests, a bug w/r/t to the explicitly setting the path.settings, and other minor things on this PR (on separate commits). 

This should be good to review now.  (will squash the extra commits before merge).

**Comment by jordansissel** [comment]
I reviewed https://github.com/elastic/logstash/commit/135819a90cf46df966b69a55f5d8f2233be82076 and https://github.com/elastic/logstash/commit/8bb47d93694572c7001fad30e230ad8c26fa2070 👍

**Comment by jordansissel** [comment]
LGTM

**Comment by jakelandis** [comment]
@jordansissel - thanks!

**Pull request closed without merging**
