### PR TITLE
Revert "Make SafeURI 9k compatible by using java.net.URI internally"

### PR DESCRIPTION
**Pull request by original-brownbear**
This reverts commit 280722ea70e3ddca96204d44cd14bb37d789fc7e.

Reverted https://github.com/elastic/logstash/pull/7236 here to fix https://github.com/elastic/logstash/issues/7304.

I'll try to find an fix for #7304 that incorporates #7236 , this would be the backup plan I guess + illustration of the issue

### CODE REVIEW

**Comment by original-brownbear** [comment]
@andrewvc I think I need you here. To me, it looks like the error that the fix you made causes (https://github.com/elastic/logstash/issues/7304#issuecomment-306137264) is a result of the type change of the `:uri` field in `SafeURI`.

I guess we could fix this in the ES Output plugin, but don't we have to be on the lookout for breaking other plugins as well? (this goes beyond my experience with the Logstash ecosystem so far :()

**Comment by original-brownbear** [comment]
@jsvd feel free to chime in as well :) (maybe you know more having been the reviewer on that PR)

**Comment by original-brownbear** [comment]
link https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/604 => I guess we consciously opted for the breaking change? :)

**Comment by jsvd** [comment]
The breaking change makes sense, the complication comes from the patch going into 5.x too because we're migrating 5.5 to ruby 9k, not just 6.x.

We can deal with this in the elasticsearch output by introducing logstash-core version restrictions like  `>= 5.5` or bumping the logstash-core-plugin-api version which describes the contract compatibility between logstash core and the plugins.

**Comment by andrewvc** [comment]
@original-brownbear yes, it was a conscious choice. Once https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/604 is merged we should be good :)

See the discussion here https://github.com/elastic/logstash/pull/7236#issuecomment-305264340

**Comment by original-brownbear** [comment]
@andrewvc @jsvd ah nice thanks for the input :) Though the PR you ( @andrewvc ) link is already merged isn't it? Is it just not released?

**Pull request closed without merging**
