### PR TITLE
Change SubstitutionVariables.replace_placeholders `refine` argument to optional

### PR DESCRIPTION
**Pull request by edmocosta**
## Release notes

[rn:skip]

## What does this PR do?

The `LogStash::Util::SubstitutionVariables#replace_placeholders` was recently [changed](https://github.com/elastic/logstash/pull/16375), and starting from Logstash `8.15.1` it requires a new argument (`refine`).
Considering plugins might be using this method internally (e.g: [logstash-input-azure_event_hubs](https://github.com/logstash-plugins/logstash-input-azure_event_hubs)), we should make the new argument optional, so existing usages won't break due this change.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Related issues

- Relates https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues/91

### CODE REVIEW

**Review by jsvd — APPROVED** [review]
LGTM, let's wait for https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/761 to finish before merging

**Review by mashhurs — APPROVED** [review]
lgtm as well.

**Comment by mashhurs** [comment]
@logstashmachine backport 8.15

**Comment by mashhurs** [comment]
@logstashmachine backport 8.x

**Pull request merged**
