### PR TITLE
Bump JrJackson gem to 0.2.9 to fix RubyBasicObject bug

### PR DESCRIPTION
**Pull request by andrewvc**
JrJackson cannot encode objects inheriting from RubyBasicObject, which is blocking a fix for https://github.com/logstash-plugins/logstash-input-twitter/issues/15

### CODE REVIEW

**Comment by andrewvc** [comment]
After discussing with @colinsurprenant and others we're delaying this merge to release 1.5.3. JrJackson has seen a lot of changes since 0.2.8 which was released over a year ago.

**Comment by jordansissel** [comment]
Code LGTM

**Comment by jordansissel** [comment]
+1 on waiting until 1.5.2 is out to merge this.

**Comment by jordansissel** [comment]
1.5.2 is released. Merging.

**Comment by jordansissel** [comment]
@andrewvc can you rebase this against master? It's not merging for me with Jarvis (`git am` is failing)

**Comment by andrewvc** [comment]
@jordansissel rebased!

**Pull request merged**
