### PR TITLE
Add beta tag to pipeline viewer docs

### PR DESCRIPTION
**Pull request by matschaffer**
# Release notes

[rn:skip]

## What does this PR do?

Adds a beta tag to 

## Why is it important/What is the impact to the user?

@joshdover called out that it wasn't marked as beta in the docs despite being beta in the kibana UI code.

This addresses that descrepancy.

## Checklist

- ~~My code follows the style guidelines of this project~~
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have made corresponding changes to the documentation~~
- ~~I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~I have added tests that prove my fix is effective or that my feature works~~

## How to test this PR locally

No idea, but expecting CI will handle a doc build.

## Related issues

Internal

### CODE REVIEW

**Comment by matschaffer** [comment]
vim also removed some trailing whitespace. If that's a problem let me know and I can reduce the diff to just the beta tag addition.

**Comment by matschaffer** [comment]
The failure here is `Test Monitoring API can configure logging` (https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-1/3647//console so doesn't seem like it'd be related to my change.

**Comment by matschaffer** [comment]
cc @ravikesarwani incase we should contact anyone regarding beta status. The code includes a beta marker but not sure if we have a more authoritative source of what parts of stack monitoring are considered beta.

**Review by karenzone — APPROVED** [review]
LGTM! Thanks for making this fix, @matschaffer

**Comment by matschaffer** [comment]
yay! thanks @karenzone !

**Pull request merged**
