### PR TITLE
update jruby to 9.2.9.0

### PR DESCRIPTION
**Pull request by jsvd**
Release notes: https://www.jruby.org/2019/10/30/jruby-9-2-9-0.html

### CODE REVIEW

**Comment by jsvd** [comment]
@colinsurprenant can you check here if we're good with removing the dns patch as you were quite involved in that (https://github.com/jruby/jruby/pull/5722)?

**Comment by colinsurprenant** [comment]
@jsvd indeed, we can now remove that patch in code and the dns filter starting with 9.2.9.0. Will provide PRs for both.

**Comment by colinsurprenant** [comment]
created #11330 to remove patch in core.

**Comment by colinsurprenant** [comment]
Also created logstash-plugins/logstash-filter-dns#58 for the dns filter.

**Pull request closed without merging**
