### PR TITLE
:logstash-core module Gradle utils

### PR DESCRIPTION
**Pull request by andsel**
Sometimes it's a need to run a single spec test with Gradle task `rubyTests`.
This PR adds the `singleRubyTest` Gradle task to module `:logstash-core` that accepts a Gradle's property selecting the spec to execute.

Example:
```
./gradlew :logstash-core:singleRubyTest \
 -PrubySingleSpec=logstash-core/spec/logstash/api/commands/default_metadata_spec.rb
```

### CODE REVIEW

**Comment by jsvd** [comment]
For reference, this can be achieved by telling gradle to run the ruby tests and rspec settings can be passed through environment variables. So in this case you can do:

```
SPEC_OPTS="-fd -P logstash-core/spec/logstash/api/commands/default_metadata_spec.rb" ./gradlew :logstash-core:rubyTests --tests org.logstash.RSpecTests
```

**Comment by andsel** [comment]
@jsvd thanks I missed that, do you think this new task is repeating stuff and is useless?

**Comment by jsvd** [comment]
Overall I'd avoid adding more code as this can already be accomplished, but I can be convinced otherwise :)
Maybe we should document better how SPEC_OPTS and `--test` to influence what is run?

**Comment by andsel** [comment]
I agree with you about DRY. The README.md is a good place to document the usage of SPEC_OPTS to run single (or subsets of) specs? If yes I close this PR and create another one document it

**Comment by jsvd** [comment]
indeed README is a good place! there's already a section on running specs: https://github.com/elastic/logstash/blob/master/README.md#core-tests

**Comment by andsel** [comment]
PR to document in README #11536

**Pull request closed without merging**
