### PR TITLE
Expose duration of the Filter+Output part of the pipeline

### PR DESCRIPTION
**Pull request by ph**
This PR will expose the time spend of a batch in the filter + output

Ouput:
http://localhost:9600/_node/stats/pipeline
```
events: {
	duration_in_millis: 18364,
	in: 309325,
	filtered: 309325,
	out: 309325
},

```

Fixes: #5731

### CODE REVIEW

**Comment by ph** [comment]
related to https://github.com/elastic/logstash/issues/5732

**Comment by jsvd** [comment]
can we also include the options of the plugins in the returned document?
Not having that makes it hard to understand which plugin is which.

Example config:

```
input { generator {} }
filter {
  sleep { time => 0.001 }
  sleep { time => 0.1 }
}
output {
  stdout { codec => rubydebug }
}
```

Example output from the api:

```
% curl http://localhost:9600/_node/stats/pipeline?pretty
{
  "host" : "Joaos-MBP.lan",
  "version" : "5.0.0-alpha6",
  "http_address" : "127.0.0.1:9600",
  "pipeline" : {
    "events" : {
      "in" : 499
    },
    "plugins" : {
      "inputs" : [ ],
      "filters" : [ {
        "id" : "sleep_dfba6bb025d8a44ab098bba4f4ec752dedbbb57f-2",
        "events" : {
          "duration_in_millis" : 515,
          "in" : 340,
          "out" : 340
        },
        "name" : "sleep"
      }, {
        "id" : "sleep_dfba6bb025d8a44ab098bba4f4ec752dedbbb57f-3",
        "events" : {
          "duration_in_millis" : 34378,
          "in" : 340,
          "out" : 336
        },
        "name" : "sleep"
      } ],
      "outputs" : [ {
        "id" : "dfba6bb025d8a44ab098bba4f4ec752dedbbb57f-4",
        "name" : "dfba6bb025d8a44ab098bba4f4ec752dedbbb57f-4"
      } ]
    }
  }
}%                                                
```

**Comment by ph** [comment]
@jsvd We have 2 reference for `duration_in_millis` in our  API, one is calculating the time spend in the filter/output filter and the other one is for the work done in all the `filters + output`. This one should be at the pipeline level.

But, In your output I do not see it, which is strange.

Concerning adding the config in the output I am not sure we should do that, we may leak unwanted details. There is a issue to provide more meaningful ids.

**Comment by ph** [comment]
One of the commit in master seems to have broken the name for the output, creating an issue for that.

```
      "outputs" : [ {
        "id" : "dfba6bb025d8a44ab098bba4f4ec752dedbbb57f-4",
        "name" : "dfba6bb025d8a44ab098bba4f4ec752dedbbb57f-4"
      } ]
```

**Comment by ph** [comment]
@jsvd I don't have the same output as your with this PR, I used the `null` output instead of the stdout. The stdout was giving me the `workers_not_supported` error.

```
{
  "host" : "sashimi",
  "version" : "5.0.0-alpha6",
  "http_address" : "127.0.0.1:9600",
  "pipeline" : {
    "events" : {
      "duration_in_millis" : 156004,
      "in" : 1997,
      "filtered" : 1497,
      "out" : 1497
    },
    "plugins" : {
      "inputs" : [ ],
      "filters" : [ {
        "id" : "sleep_510eb569aee937aacd3650e004af8325c08d496e-2",
        "events" : {
          "duration_in_millis" : 2634,
          "in" : 1849,
          "out" : 1849
        },
        "name" : "sleep"
      }, {
        "id" : "sleep_510eb569aee937aacd3650e004af8325c08d496e-3",
        "events" : {
          "duration_in_millis" : 188403,
          "in" : 1849,
          "out" : 1845
        },
        "name" : "sleep"
      } ],
      "outputs" : [ {
        "id" : "510eb569aee937aacd3650e004af8325c08d496e-4",
        "events" : {
          "in" : 1497,
          "out" : 1497
        },
        "name" : "510eb569aee937aacd3650e004af8325c08d496e-4"
      } ]
    }
  }
}
```

**Comment by jsvd** [comment]
LGTM, please link the issue of the wrong id/name of output to this PR

**Comment by ph** [comment]
https://github.com/elastic/logstash/issues/5799 is Issue concerning the wrong name for the output, I created https://github.com/elastic/logstash/pull/5800 to fix it and added test for the output/filter in the `pipeline_spec`

**Pull request closed without merging**
