### PR TITLE
Update to default plugins

### LINKED ISSUE #5644: Add aggregate filter to core bundle
The aggregate filter is getting more popular and has some interesting [use cases](https://github.com/logstash-plugins/logstash-filter-aggregate#logstash-filter-aggregate-documentation). Let's bundle this in the core LS package.

### PR DESCRIPTION
**Pull request by suyograo**
Removed xmpp-output, lumberjack input (since it is going EOL this November)

Added filter-aggregate

Fixes #5644

### CODE REVIEW

**Comment by acchen97** [comment]
Will follow-up with you on this Friday.

**Comment by acchen97** [comment]
@suyograo as discussed today:

**Add to default**
- logstash-codec-avro
- logstash-filter-aggregate

**Remove from default**
- logstash-filter-clone
- logstash-input-exec
- logstash-input-imap
- logstash-input-irc
- logstash-input-lumberjack
- logstash-input-pipe
- logstash-input-unix
- logstash-input-xmpp
- logstash-input-zeromq
- logstash-output-cloudwatch
- logstash-output-exec
- logstash-output-hipchat
- logstash-output-irc
- logstash-output-pagerduty
- logstash-output-pipe
- logstash-output-sns
- logstash-output-sqs
- logstash-output-statsd
- logstash-output-xmpp
- logstash-output-zeromq

**Add support for**
- logstash-filter-throttle

**Remove support for**
- logstash-filter-metrics
- logstash-input-eventlog
- logstash-output-elasticsearch_java

**Comment by acchen97** [comment]
uuid filter and log4j input were removed from default, can we add them back since they're supported plugins?

Also, these were in the remove list, but weren't removed. I'm OK keeping them in default if you are.
- logstash-filter-clone
- logstash-input-exec
- logstash-input-zeromq
- logstash-output-exec
- logstash-output-hipchat
- logstash-output-pagerduty
- logstash-output-sns
- logstash-output-zeromq

**Comment by suyograo** [comment]
@acchen97 I don't see any of these plugins in default list: 

logstash-input-zeromq
logstash-output-exec
logstash-output-hipchat
logstash-output-sns
logstash-output-zeromq

I kept logstash-output-pagerduty since we use it in our trainings

**Comment by acchen97** [comment]
LGTM

**Pull request closed without merging**
