### PR TITLE
Doc: Add ecs and datastream requirement for intg filter

### PR DESCRIPTION
**Pull request by karenzone**
Related: https://github.com/elastic/logstash-filter-elastic_integration/issues/151

### CODE REVIEW

**Comment by karenzone** [comment]
Screen Shot 2024-06-28 at 6 35 39 PM

**Review by mashhurs — APPROVED** [review]
LGTM!

**Comment by karenzone** [comment]
10467

**Comment by karenzone** [comment]
@logstashmachine backport 8.14

**Pull request merged**
