### PR TITLE
[DOC] Clarify behavior in case of PQ full & isolator pattern

### PR DESCRIPTION
**Pull request by lucabelluccini**
I am not sure the wording is correct, but I would like to add a clarification of the behavior of PQ isolator pattern if PQ get full.
It should be backported as this is not version specific.

### CODE REVIEW

**Comment by andsel** [comment]
I ask @karenzone  to give a quick eye, to me the seems good

**Comment by karenzone** [comment]
@lucabelluccini  Thanks for this clarification.  It's a nice addition to the docs.

We appreciate all you do to help us improve our docs.  You are a frequent contributor, and so it's probably time to share this tip.  When you see something in the docs that can be improved, please switch over to `master` before you create the PR. I just replace the version with `master` in the URL and refresh.

As always, we appreciate your help and your commitment to making our docs better. <3

**Comment by lucabelluccini** [comment]
Hello @karenzone , I've started to double-check I do my modifications on the `master` branch (I've done some on the Kibana repo recently). I'll do next time, sorry about the mess.

**Comment by karenzone** [comment]
@lucabelluccini, this was not a mess at all.  We appreciate the contribution.
You're becoming a power user, and I thought this ProTip might be helpful.  :-)

**Pull request closed without merging**
