### PR TITLE
Pin webrick to compatible version

### LINKED ISSUE #8845: Pin webrick to fix rake test:install-core
Webrick 1.4.0 , released yesterday requires Ruby version ">= 2.5.0dev " and fails when trying to install development dependencies for plugins. 

We need to pin this to version(s) prior to 1.4.0.

### PR DESCRIPTION
**Pull request by jakelandis**
Fixes #8845

### CODE REVIEW

**Comment by jakelandis** [comment]
still need to back patch to 6.0 and 5.6 ...

**Comment by jakelandis** [comment]
via https://github.com/elastic/logstash/pull/8850


Branch | Commits
-- | --
5.6 | f9ec829

**Comment by jakelandis** [comment]
via https://github.com/elastic/logstash/pull/8851


Branch | Commits
-- | --
6.0 | 046b44c

**Comment by jsvd** [comment]
@jakelandis It seems 1.4.0 was a bugged gem, we can revert this now for branches >= 6.0 as webrick 1.4.1 and above now depend on ruby 2.3.0 instead:

```
% rvm use jruby-1.7.27
Using ~/.rvm/gems/jruby-1.7.27
% gem install webrick -v "1.4.0"
Fetching: webrick-1.4.0.gem (100%)
ERROR:  Error installing webrick:
	webrick requires Ruby version >= 2.5.0dev.
% gem install webrick -v "1.4.1"
Fetching: webrick-1.4.1.gem (100%)
ERROR:  Error installing webrick:
	webrick requires Ruby version >= 2.3.0.
% gem install webrick -v "1.4.2"
Fetching: webrick-1.4.2.gem (100%)
ERROR:  Error installing webrick:
	webrick requires Ruby version >= 2.3.0.
```

**Pull request closed without merging**
