### PR TITLE
allow the rabbitmq routing key to be populated from the event

### PR DESCRIPTION
**Pull request by addisonj**
The jruby implementation of the rabbitmq plugin currently doesn't do string interpolation on the routing key.

The ruby (bunny) implementation does and the tutorial on rabbitmq (http://logstash.net/docs/1.4.0/tutorials/just-enough-rabbitmq-for-logstash) indicates the same.

This PR fixes that. There may be a more elegant want to do this, but this seemed pretty straight forward. I also am not sure how this works in terms of thread safety. 

This may not be the right answer, but being able to interpolate fields in the routing key is a very nifty little feature.

### CODE REVIEW

**Comment by suyograo** [comment]
@addisonj can you please perform step 2 of https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by addisonj** [comment]
Signed and done,

Let me know if you need anything else.

**Comment by suyograo** [comment]
@addisonj thanks much. one more request. Can you move this PR to its new location https://github.com/logstash-plugins/logstash-output-rabbitmq ?

I tried to move it automatically via API, but was unsuccessful.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins (and grok patterns) to individual repositories. Can you move this pull request to https://github.com/logstash-plugins/logstash-output-rabbitmq?

This sequence of steps _may_ help you do this migration:

1. Fork this repository
2. Clone your fork

  ```shell
  git clone https://github.com/addisonj/logstash.git
  ```

3. Create a branch:

  ```shell
  git checkout -b my-branch-name
  ```

4. Apply the patches from this PR into your branch:

  ```shell
  curl -s https://github.com/elastic/logstash/pull/1202.patch | git am
  ```

  This should take your commits from this PR and commit them to your new local branch.

5. Push!

  ```shell
  git push origin my-branch-name
  ```

6. Open a new PR against https://github.com/logstash-plugins/logstash-output-rabbitmq

**Comment by addisonj** [comment]
I just took a look at the new code and it looks like the functionality is already there, so no need to have this applied

**Pull request closed without merging**
