### PR TITLE
String Interpolation skip the last character

### LINKED ISSUE #3931: Field Expression Causes Last Character to be removed
If a field expression is used in an add_field property at the end of a string, the last character will be dropped in the output i.e. it occupies upto position N-2 in the string, where N is the length of the string indexed from 0.

For example,

mutate {
    	add_field => { "Intel-Foundation" => "|%{fAffiliate}|" }
  	}

In this case, the the final pipe character will be dropped.  This can be solved by adding a character to the end of the string thus moving the expression termination point to N-3 e.g. 

mutate {
    	add_field => { "Intel-Foundation" => "|%{fAffiliate}| " }
  	}

### PR DESCRIPTION
**Pull request by ph**
This PR fix a problem when doing the interpolation with a string that
did not end with a fieldref but with a character. The interpolation was
ignoring the last character.

Example:
```
"%{type}|" => "syslog"
```

Fixes #3931

### CODE REVIEW

**Comment by jordansissel** [comment]
Code looks good; didn't run the tests, but the new test case covers the bug fix.

**Comment by guyboertje** [comment]
@ph - do you remember why you had the `if position < template.size - 1` in the first place?

**Comment by ph** [comment]
To the time machine.

@guyboertjein at the beginning I didn't have a StaticNode class and the parsing was done differently and was pretty much the same as logstash 1.4.2. I gave another look at it this morning and I found a missing test case that I just added.

**Comment by guyboertje** [comment]
@ph - that is the ticket! I suspected asking that question would result in something good :-)

LGTM

**Pull request closed without merging**
