### PR TITLE
much needed README refresh

### PR DESCRIPTION
**Pull request by colinsurprenant**
- updated urls
- updated need help links
- revamped Developing, Testing and Building sections.
- added links to plugins development

these instructions are compatible with PR #3111

### CODE REVIEW

**Comment by suyograo** [comment]
minor comment -- mention that `bin/logstash rspec` was removed in favor or `bin/rspec`. Also does `bin/logstash irb` still work with #3111?

**Comment by colinsurprenant** [comment]
@suyograo added a note on `bin/logstash rspec`. let me know if that's good. Yes, `bin/logstash irb` still works but see my idea about this in #3148

**Comment by ph** [comment]
LGTM

**Comment by suyograo** [comment]
LGTM

**Comment by colinsurprenant** [comment]
:shipit:

**Pull request closed without merging**
