### PR TITLE
Only log pipeline info on converge if actions were taken.

### PR DESCRIPTION
**Pull request by jakelandis**

### CODE REVIEW

**Comment by jakelandis** [comment]
jenkins test this please

**Comment by original-brownbear** [comment]
@jakelandis this seems to break the smoke test?

**Comment by jakelandis** [comment]
Jenkins test this please

@original-brownbear , 🤔 not sure how this could break that.

**Comment by jakelandis** [comment]
@original-brownbear - it looks like the 6.x tests haven't built to success since this PR was merged: https://github.com/elastic/logstash/pull/9398

**Comment by original-brownbear** [comment]
@jakelandis try rebasing on `master` now that #9411 is in :)

**Comment by original-brownbear** [comment]
@jakelandis ok https://github.com/elastic/logstash/pull/9412 in, now we should actually be good I hope

**Comment by original-brownbear** [comment]
@jakelandis green + LGTM :)

**Comment by jakelandis** [comment]
@original-brownbear - thanks!

**Pull request closed without merging**
