### PR TITLE
Fix flushing with ordered execution

### PR DESCRIPTION
**Pull request by robbavey**
When running a pipeline with ordered execution, flushes on the pipeline
were no longer being called when compute is called with an empty batch, causing
issues with the aggregate filter, for example, not being able to push events on
timeout.

This commit checks if the batch is empty, and if so, calls compute with an empty
batch to ensure that flush is called.

Relates to #12158

### CODE REVIEW

**Comment by robbavey** [comment]
jenkins test this please

**Comment by colinsurprenant** [comment]
👀

**Comment by robbavey** [comment]
jenkins test this please

**Comment by colinsurprenant** [comment]
Thanks a lot @robbavey for this, since you are away for a few days I decided to reboot this PR in #12204 with a small modification to check if a flush is required.

**Pull request closed without merging**
