### PR TITLE
Avoids unnecessary thread sync of PQ notFull state

### PR DESCRIPTION
**Pull request by kaisecheng**
Fixed: #6801

## Release notes

Improve persistent queue full state handling
## What does this PR do?

The definition of full is 
(1) the byte size of queue >= `queue.max_bytes` and/or
(2) the number of unread event >= `queue.max_events`

Prior to the change, when PQ is full, workers wake up writer thread in every read.
if queue is full due to the number of unread, it is right to wake up write thread.
But if queue is full due to byte size, without removing a fully acked page, the queue is still full. 
[notFull.signalAll()](https://github.com/elastic/logstash/blob/8.2/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L652-L654) cause unnecessary thread sync.

This commit changes the condition of sending notFull signal. 
Send the signal in readPageBatch() if queue is full by the number of unread.

Another [notFull.signalAll()](https://github.com/elastic/logstash/blob/8.2/logstash-core/src/main/java/org/logstash/ackedqueue/Queue.java#L712-L715) happens when the tailPage is fully acked and can be deleted. We can check if queue is full due to byte size before delete the tailPage and signal notFull. Adding additional size checking in every ack() seems redundant as most of the time, queue is limited by size not the number of unread. Therefore, no change in ack().

## Why is it important/What is the impact to the user?

This change improves persistent queue read/write performance.
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by andsel — APPROVED** [review]
LGTM

The code change does what it claims, but I wonder how we can measure that's effectively improvement. 
Wake up writers blocked on `notFull` only when they can effectively satisfy the condition of `!isMaxBytesReached()`, means have more CPU cycles to do other stuff, but have no simple idea on how we could find something that measure this.

**Comment by kaisecheng** [comment]
I haven't measured it. This improvement is valid for queues that stay in full state for a long time (back pressure). Depending on the page size and event size, waking up writer unnecessarily in every read could be a lot of waste.

**Comment by kaisecheng** [comment]
@logstashmachine backport 8.2

**Comment by kaisecheng** [comment]
@logstashmachine backport 7.17

**Pull request merged**
