### PR TITLE
Change how we set the max heap size

### LINKED ISSUE #3134: support consistent env variables between the Linux and Windows startup scripts
the supported environment variables are not consistent between Linux and Windows. 

for example, in Linux we use `LS_HEAP_SIZE` while on it's `LS_MIN_MEM` and `LS_MAX_MEM`. 

I don't know what the history is for this but I think we should make them consistent as much as possible.

### PR DESCRIPTION
**Pull request by ph**
This PR change the name of the variable to set to change the maximum
heap size on window to `LS_HEAP_SIZE` this replace the LS_MIN_MEM and
LS_MAX_MEM option.

Also We change the default size of the heap from 500m to 1g

Fixes #3134

### CODE REVIEW

**Comment by untergeek** [comment]
I don't have a windows box to test it on, but LGTM™ code-wise.

**Comment by jordansissel** [comment]
Didn't test, but code LGTM

**Comment by jsvd** [comment]
why change bump the default to 1g on this PR? I'd suggest making this 500mb as linux is https://github.com/elastic/logstash/blob/master/bin/logstash.lib.sh#L6

**Comment by ph** [comment]
@jsvd I was also intrigued by why we had a different settings on windows, but I think to reduce the memory on windows from 1gb to 500mb would be a bit confusing for people. Since we want to give 1gb in 2.1 I though I would normalize both to the upper bound which is 1gb

**Comment by ph** [comment]
@jsvd it wasn't a global change see https://github.com/elastic/logstash/pull/4085/files#diff-623067f911d57d55649dacff126510fdL26 windows used 1gb as their default for some time

**Comment by jsvd** [comment]
LGTM

**Pull request closed without merging**
