### PR TITLE
add custom clamp appender to fix path.plugin

### LINKED ISSUE #8799: command line -p broken
when launching logstash using `-p` option to specify an alternate `path.plugins` it crashes. I noticed this on master, not sure how far back this has been broken. 

The workaround is to use the `path.plugins:` option in `logstash.yml`.

```
$ bin/logstash -p tmp/ -f tmp/syslog.conf
NameError: `@path.plugins' is not allowable as an instance variable name
         instance_variable_get at org/jruby/RubyKernel.java:2023
                           get at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:21
                       _append at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:41
  block in define_appender_for at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/attribute/declaration.rb:41
                          take at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:57
                 parse_options at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:32
                         parse at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:52
                           run at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:66
                           run at /Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/runner.rb:214
                           run at /Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
                        <main> at /Users/colin/dev/src/elasticsearch/logstash/lib/bootstrap/environment.rb:67
```

### PR DESCRIPTION
**Pull request by jsvd**
the path.plugin setting is a multi valued option, clamp uses
an implicit appender method for adding values to an array.
because we patch Clamp to use LogStash::SETTINGS underneath,
we must tune both reading/writing and appending values.
This last wasn't being customized, so this path redefines the
append_method method to add an element to a setting's value

fixes #8799

### CODE REVIEW

**Comment by original-brownbear** [comment]
@jsvd seems this is breaking specs right? :( 

I'm seeing this for the Ruby tests run:

```sh
   (LogStash::Agent (class)).new(*(any args))
12:25:36                 expected: 1 time with any arguments
12:25:36                 received: 0 times with any arguments
12:25:36           # ./logstash-core/spec/logstash/runner_spec.rb:247:in `block in (root)'
12:25:36           # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
12:25:36           # ./lib/bootstrap/rspec.rb:13:in `<main>'
12:25:36 
12:25:36       17) LogStash::Runner pipeline settings when :path.data is defined by the user should set data paths
12:25:36           Failure/Error:
12:25:36             expect(LogStash::Agent).to receive(:new) do |settings|
12:25:36               expect(settings.get("path.data")).to eq(test_data_path)
12:25:36               expect(settings.get("path.queue")).to eq(test_queue_path)
12:25:36               expect(settings.get("path.dead_letter_queue")).to eq(test_dlq_path)
12:25:36             end
12:25:36           
12:25:36             (LogStash::Agent (class)).new(*(any args))
12:25:36                 expected: 1 time with any arguments
12:25:36                 received: 0 times with any arguments
12:25:36           # ./logstash-core/spec/logstash/runner_spec.rb:166:in `block in (root)'
12:25:36           # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
12:25:36           # ./lib/bootstrap/rspec.rb:13:in `<main>'
```

**Comment by jsvd** [comment]
Sorry for wasting your time, I only checked the test passed, not the whole suite.

This is turning out to be a bit of a tumble through the rabbit hole. The `--modules` setting isn't registered on the SETTINGS object like all others causing the appender patch introduced here to raise an exception when the flag is used.

I'm experimenting with two options:

1) guarding the append option against non existing settings
2) registering the missing option and ensuring it doesn't conflict with existing behaviour

**Comment by original-brownbear** [comment]
@jsvd I don't think those tests were deleted. I upgraded the clamp version the other day, maybe that fixed it randomly?

**Comment by jsvd** [comment]
For what it's worth I have tested manually both starting the netflow module and also using -p with a custom .rb plugin, both worked correctly.

**Comment by original-brownbear** [comment]
@jsvd I can't find anything wrong with this from the code either and the last change to the spec that was failing before was in Aug. 2017 => LGTM :)

**Comment by jsvd** [comment]
jenkins test this please

**Comment by jsvd** [comment]
jenkins test this please

**Pull request closed without merging**
