### PR TITLE
version 1.5.0.rc3.snapshot1 bump

### LINKED ISSUE #2949: Publish logstash-core SNAPSHOT version
As part of testing for #2928 we need to publish a new version for logstash-core gem. Lets publish a snapshot version before we are ready for a RC3 version

The version should be 1.5.0-rc3.snapshot

### PR DESCRIPTION
**Pull request by purbon**
First snapshot released for testing 1.5.0.rc3.

Closes #2949

### CODE REVIEW

**Comment by colinsurprenant** [comment]
LGTM

**Comment by colinsurprenant** [comment]
per our discussion with @suyograo and @ph yesterday, the `LOGSTASH_VERSION ` has to be `1.5.0-rc3.snapshot1` - with a dash - so that hte package name when generated uses the dash convention like in semver. 

BUT  in the gemspec, we need to gsub the dash for a dot, so that the Rubygem version has only dots.

**Comment by purbon** [comment]
updated, sorry ... I really thought this change was to make ruby-maven happy, but I agree we should have all product named with the same convention.

**Comment by colinsurprenant** [comment]
LGTM :)

**Comment by colinsurprenant** [comment]
:shipit:

**Comment by purbon** [comment]
I close this manually as Jarvis did not properly closed it

**Pull request closed without merging**
