### PR TITLE
Fix broken link to image on docs

### PR DESCRIPTION
**Pull request by cleydyr**
## What does this PR do?
Fix broken link to image in 7.17 docs.

### CODE REVIEW

**Comment by kaisecheng** [comment]
7.17 image isn't broken. Feel free to reopen the issue if you see something wrong

**Comment by cleydyr** [comment]
Hey, @kaisecheng .

Here are the steps to reproduce:
1. Go to https://www.elastic.co/guide/en/logstash/7.17/monitoring-internal-collection-legacy.html#configure-internal-collectors-legacy
2. In step 6, there's an image that illustrates the monitoring section. (That image is shown correctly)
3. Click on that image to get see it in original size

Expected: the link points to the image in original size and the reader can see it.
Current: the link is broken and clicking on the image sends the user to a 404 page

As the changes imply, if the link were 

https://www.elastic.co/guide/en/logstash/7.17/images/monitoring-ui.png

instead of

https://www.elastic.co/guide/en/logstash/7.17/monitoring/images/monitoring-ui.png

then the image would open correctly.

Thank you :)

**Comment by kaisecheng** [comment]
@cleydyr My bad! sorry to close it. 
Your fix is valid. Thank you so much for submitting the PR. I can see the same issue happening in the `main` branch. Could you make a new PR target to `main`, so I can backport the fix to `8.3` and `7.17`?

**Comment by cleydyr** [comment]
Closing in favor of https://github.com/elastic/logstash/pull/14343

**Pull request closed without merging**
