### PR TITLE
pin major versions of default plugins in Gemfile

### PR DESCRIPTION
**Pull request by jsvd**
implements https://github.com/elastic/logstash/issues/5534

### CODE REVIEW

**Comment by suyograo** [comment]
LGTM, did not test

**Comment by suyograo** [comment]
I'd like @ph to check this out as well.

**Comment by ph** [comment]
The list look sane to me, I've checked the most weird one like the SNS (v4) and the input rabbitmq (v5), The choice of dependency `~> MAJOR` is correct and will pick up the all the minor and release version of the plugins.

I will do a bit of testing with the update scenario.

**Comment by ph** [comment]
I've tested the update scenario using the `logstash-filter-qatest` to make sure that the update still works with defining the plugins like that and everything is fine.

I've created #5543 to make sure we change the code in the update to skip the core gems from the message, I think it will confuse people.

rake artifact:all, rake bootstrap, rake test:install-core, rake test:core command **works**.

LGTM

**Comment by ph** [comment]
As a side note, this should make the unified build process faster since it skip the `logstash-plugin install`

**Comment by jsvd** [comment]
until we decide on https://github.com/elastic/logstash/issues/5533 we should only merge this to 5.0, correct?
Thanks for the review @ph

**Comment by ph** [comment]
Concerning #5533, I think we could still merge this in master or we can merge it later.

Merging it right will make things a tad slower until we implement a solution for it. So its a matter of how much pain we want to have :)

**Comment by suyograo** [comment]
+1 on merging it to master as well as 5.0. See https://github.com/elastic/logstash/issues/5533#issuecomment-228106684

**Comment by jsvd** [comment]
as for merging this to master, should we merge as is? I'm don't see the benefit of having master restrain the major version of the plugins.
Since it's "bleeding edge" it should pick whatever is latest, no?

**Comment by suyograo** [comment]
@jsvd makes sense to leave master without constraints..

**Pull request closed without merging**
