### PR TITLE
Switch branch slector from major.minor to read the current branch name

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

[rn:skip]

## What does this PR do?

Switches the selection of --branch name from deducting from release version to read from directly from git.
In this way the snapshots built from `main` are 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by roaksoax — APPROVED** [review]
LGTM!

**Comment by roaksoax** [comment]
+1

**Comment by andsel** [comment]
@logstashmachine backport 8.5

**Comment by andsel** [comment]
@logstashmachine backport 7.17

**Pull request merged**
