### PR TITLE
Remove extra preposition from configuration.asciidoc

### PR DESCRIPTION
**Pull request by vassilevsky**

### CODE REVIEW

**Comment by untergeek** [comment]
@vassilevsky Thanks for catching and correcting this.  

Could you please sign our [Contributor Licence Agreement](http://www.elasticsearch.org/contributor-agreement/) so I can merge this?

**Comment by vassilevsky** [comment]
What goes into the last field of the individual agreement? It has no label.

**Comment by untergeek** [comment]
The 4 fields I see are:

* Signature
* Email
* Title (Enter your job title)
* Github Username

Is there another field beyond this?

**Comment by vassilevsky** [comment]
This is what I see:
fields
Thanks for the info. I have signed it!

**Comment by untergeek** [comment]
Confirmed.

**Pull request closed without merging**
