### PR TITLE
Add some javadocs comments to the classes

### PR DESCRIPTION
**Pull request by andsel**
clean backport of #12516 to branch `7.x`

(cherry picked from commit 9a63ec2705e4c44a7ba561b609042f29920170cf)

### CODE REVIEW

**Comment by kaisecheng** [comment]
ci red due to maven server issue. This PR removes comments only and a legacy class, LGTM

**Comment by andsel** [comment]
Jenkins test this please

**Comment by kaisecheng** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Review by kaisecheng — APPROVED** [review]
LGTM. The red CI is not from here which only remove the comment

**Pull request merged**
