### PR TITLE
Reduce the visibility of the Pipeline

### PR DESCRIPTION
**Pull request by ph**
With the upcoming changes of the #6281 I want to reduce the visibility of the pipeline as much as possible to the outside world.

- Make sure we don't use any reference to the thread to check if a pipeline is running or not and only rely on the `#running?` method.
- use the private method to mark as much as possible the method that doesn't need to be exposed, this is a start I would also like to hide some of the `attr_reader` methods but this would require more refactoring.
- Set the name of the pipeline thread only once in the agent instead of the `Pipeline#run`.
- Remove the type check on pipeline and instead rely on duck typing.

The tests require https://github.com/elastic/logstash-devutils/pull/65 to make the `#sample` method work.

Ref: #6493

### CODE REVIEW

**Comment by ph** [comment]
Just a note, I've deviced to use explicit calls to `private :<method_name>` instead of moving code around to change the visibility, this way I make the PR less green.

**Comment by ph** [comment]
Test is falling because we need a new version of devutils. .. https://github.com/elastic/logstash-devutils/pull/65

**Comment by jsvd** [comment]
I've been trying to run core specs with this branch and pr 65 of devutils, but the specs keep hanging

**Comment by jsvd** [comment]
@ph can you rebase please? also https://github.com/elastic/logstash-devutils/pull/65 is good to merge. I suggest release the new devutils so we can see green here

**Comment by jsvd** [comment]
I'm seeing green in the specs now, I think with a rebase we can merge this

note: this will conflict with https://github.com/elastic/logstash/pull/6631

**Comment by ph** [comment]
I will rebase this PR asap, with all the changes with the pipeline its not easy.

**Comment by ph** [comment]
I think its just easier to do a new PR with all the changes that went into agent/pipeline :(

**Pull request closed without merging**
