### PR TITLE
Fix single element lists in config

### PR DESCRIPTION
**Pull request by bodgit**
Currently if you try and use a list containing a single element like `['foo']` in the configuration file(s), Logstash interprets that as access to a field literally called `'foo'` in an event, (including the quotes). By updating the `selector_element` pattern in the grammar to not match either `'` or `"` in field names Logstash now correctly interprets this as a list.

I updated the `in` & `not in` operator tests to cover this.

Fixes [LOGSTASH-2201](https://logstash.jira.com/browse/LOGSTASH-2201).

### CODE REVIEW

**Comment by oscherler** [comment]
It’s not an enhancement, it’s a bug fix. A bug that is still present two years later.

**Comment by jordansissel** [comment]
@oscherler I agree it's a bug. The proposed fix feels like the right one, but it gives me great regret in having chosen the same syntax markers `[]` for both list and field reference syntax in Logstash. With this patch, the fact that `[foo]` and `["foo"]` mean completely different things is a very hard thing for me to explain when I think about documenting it or teaching others about the differences in these two very similar-looking configurations.

You should be able to work around this bug by having `if "foo" in ["item1"]` (which doesn't work today) and make your list having two items, one of which would never occur, such as `["element1", "laksjdflkajwoetiuaoidjtalskdjtalwijet"]` -- it feels like a silly workaround, but that's an option for now.

**Comment by oscherler** [comment]
Another workaround is to put the same item twice: `if "foo" in ["item1", "item1"]`.

I understand your concern, but I’m not shocked by the similarity between `[foo]` and `["foo"]`. To be honest, the first time I saw an `if`, I thought of the brackets as how they’re used in shell scripting: `if [$foo -ne 0]`, and I was confused for half a second that the rest of the condition was not inside.

Another thing I tried before I found this issue was to try to replicate Python’s syntax for single-element tuples, `('foo',)` like this: `if "foo" in ["item1",]`. I don’t know if it would be more or less confusing than `["foo"]`.

**Comment by talevy** [comment]
Closing due to inactivity and the strong likely-hood that we will not be modifying the config language any time soon. Happy to re-open if this changes

**Comment by bodgit** [comment]
> Closing due to inactivity

Only inactivity on your part. Sad that this has sat for 2.5 years with no action, it could have been merged and any fallout would be a distant memory by now.

**Comment by jordansissel** [comment]
@bodgit I understand your frustrations. We are a very small team and modifications to the grammar have, historically, been extremely turbulent with negative impact to users. We'll work to address this when we can.

**Comment by talevy** [comment]
@blodgit, you're absolutely right to be frustrated, but as @jordansissel mentioned, there has and still is a lot of discussions around the direction of the config language, and it has largely been static as to not blow any existing production configs up.

This PR will not be ignored during these discussions. In fact, it will be used as a resource to guide future direction we decide for LS 5.x and 6.0. Thank you!

**Comment by bodgit** [comment]
The only area this would've broken AFAICT was if someone was relying on having literal quote characters in their field names. Chances are if you're doing this you're likely to get burnt when you try and pass those fields on to upstream systems.

**Comment by fjiang423** [comment]
2017 this bug still not fixed

**Comment by fifman** [comment]
This is still a problem in Logstash oss 6.2.4. It's really strange this simple bug exists for so many years

**Pull request closed without merging**
