### PR TITLE
Fix typo in proxy_support.rb

### PR DESCRIPTION
**Pull request by cmilhaupt**
Fixed a typo I noticed when running into problems configuring logstash.

### CODE REVIEW

**Comment by yaauie** [comment]
@cmilhaupt thanks for the grammar fix 😄

In order for us to be able to legally accept your contribution, we'll need you to sign the [Contributor License Agreement](https://www.elastic.co/contributor-agreement).

**Comment by cmilhaupt** [comment]
Signed!

**Comment by yaauie** [comment]
jenkins test this please

**Comment by roaksoax** [comment]
jenkins test this please

**Pull request closed without merging**
