### PR TITLE
logstash-core version bump

### PR DESCRIPTION
**Pull request by purbon**
logstash-core version 1.5.1 bump, so we start doing test for the upcoming release.

### CODE REVIEW

**Comment by purbon** [comment]
@jsvd can you take a look to this?

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
@suyograo can you review this?

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
