### PR TITLE
Update build.gradle - update snakeyaml

### PR DESCRIPTION
**Pull request by Pamir**
Update Snakeyaml,
container vulnerabilities

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by logstashmachine** [comment]
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

**Comment by jsvd** [comment]
@jenkins test this please

**Comment by deepakLabs** [comment]
Maybe the jenkins job is failing due to this particular issue.
https://github.com/elastic/logstash/issues/14831
Please check

**Comment by deepakLabs** [comment]
@jsvd @roaksoax @jordansissel @original-brownbear @fetep @robbavey @ph @suyograo @danhermann 
Can you please look into it.

**Comment by deepakLabs** [comment]
@jsvd @roaksoax @jordansissel @original-brownbear @fetep @robbavey @ph @suyograo @danhermann
Can you please look into it.

**Comment by jsvd** [comment]
@deepakLabs please don't spam notifications on multiple people, many not working on Logstash. Closer to the weekend it is normal that there won't be progress on an issue, if there is a reason for urgency please state reasons, or email security@elastic.co if the concern is security related.

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by jsvd** [comment]
@logstashmachine backport 8.6

**Pull request merged**
