### PR TITLE
Bump JrJackson gem to 0.2.9 to fix RubyBasicObject bug

### PR DESCRIPTION
**Pull request by andrewvc**

### CODE REVIEW

**Comment by suyograo** [comment]
LGTM

**Comment by suyograo** [comment]
same as https://github.com/elastic/logstash/pull/3517. merging to 1.5

**Comment by suyograo** [comment]
Merged https://github.com/elastic/logstash/commit/2e21b006e942804d7022b64123766e1225a13163

**Comment by andrewvc** [comment]
Thanks for merging this @suyograo

**Pull request closed without merging**
