### PR TITLE
make worker thread names visbile to OS, fixes #9968

### LINKED ISSUE #9968: Operation system  worker thread names
Currently all filter/output worker threads appear with name `[#{pipeline_id}]-pipeline-manager`.

(This is longer than the 15chars normally visible in OS.)

This behaviour contradicts the [documentation](https://www.elastic.co/guide/en/logstash/6.4/tuning-logstash.html#_notes_on_pipeline_configuration_and_performance)
`and pipeline workers show up as [base]>workerN, where N is an integer.`

I believe the fix is simple and you just need to use `Util.set_thread_name` in `start_workers` in [java_pipeline.rb](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/java_pipeline.rb#L220) and [pipeline.rb](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/pipeline.rb#L287)

### PR DESCRIPTION
**Pull request by IrlJidel**
Make worker filter/output threadnames visible in operation system tools like top/ps etc

### CODE REVIEW

**Comment by yaauie** [comment]
Jenkins test this please

**Comment by yaauie** [comment]
@IrlJidel good catch!

I expect CI to complete normally; when it does, we'll merge to `master` and backport to `6.x` and `6.4`.

**Comment by IrlJidel** [comment]
@yaauie Thanks - has 6.4.1 bus already left the station?

**Comment by yaauie** [comment]
6.4.1 is in-flight, but there is a blocker with the PQ that will require another release candidate. I can't really justify making this PR a blocker in its own right, but can attempt to get it in before the other release candidate is built.

**Pull request closed without merging**
