### PR TITLE
Update Reflections library to work with Java 11

### LINKED ISSUE #10945: Java plugins included in Logstash core do not work with Java 11
With Java 11, classes in Logstash core with `@LogstashPlugin` annotations are not properly identified causing any attempt to use a Java plugin included in Logstash core such as `java_stdin` to fail. This is likely a result of changes to the Java classloader between Java 8 and Java 11.

### PR DESCRIPTION
**Pull request by danhermann**
Also removes previously "vendored" code since the Guava dependency versions are now compatible.

Fixes #10945.

### CODE REVIEW

**Comment by jsvd** [comment]
giphy

Regarding CI, the two failures on pq-1 are strangely consistent (wrong level of logging), but seem unrelated to this change, can you confirm the failures still occur without it?

**Comment by danhermann** [comment]
Jenkins, test this please

**Comment by danhermann** [comment]
Jenkins, test this please

**Comment by yaauie** [comment]
LGTM 👍🏼

**Comment by danhermann** [comment]
Thanks, @jsvd and @yaauie!

**Pull request closed without merging**
