### PR TITLE
Fix the metrics API when used from artifacts and small changes in webserver class. 

### LINKED ISSUE #4679: feature/metrics is not working with latest commits
```
suyog@machine:~/ws/elastic/logstash (feature/metrics)$ bin/logstash -e 'input { stdin {} } output { stdout {} }'
Settings: Default pipeline workers: 8
Logstash startup completed
{:debug=>nil, :http_host=>nil, :http_port=>nil}
No application configured, nothing to run {:level=>:error}
```

Environment:
```
suyog@machine:~/ws/elastic/logstash (feature/metrics)$ ruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 +jit [darwin-x86_64]
suyog@machine:~/ws/elastic/logstash (feature/metrics)$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

Cleaned up `build/ vendor/ .bundle` and tried again. Same result

With `--debug`

```
Settings: Default pipeline workers: 8
Starting pipeline {:id=>"main", :pipeline_workers=>8, :batch_size=>125, :batch_delay=>5, :max_inflight=>1000, :level=>:info, :file=>"logstash/pipeline.rb", :line=>"222", :method=>"start_workers"}
Pipeline started {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"170", :method=>"run"}
Logstash startup completed
{:debug=>true, :http_host=>nil, :http_port=>nil}
=== puma start: 2016-02-11 23:38:06 -0800 === {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
Puma starting in single mode... {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
* Version 2.16.0 (jruby 1.9.3), codename: Midwinter Nights Trance {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
* Min threads: 0, max threads: 16 {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
* Environment: development {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"47", :method=>"log"}
No application configured, nothing to run {:level=>:error, :file=>"logstash/webserver.rb", :line=>"51", :method=>"error"}
```

### PR DESCRIPTION
**Pull request by purbon**
Fixes #4679

//cc @jsvd @ph thoughts?

### CODE REVIEW

**Comment by jsvd** [comment]
Code LGTM, however sometimes I get the same failed test as jenkins:

```
% rake test:core
Using Accessor#strict_set for specs
/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/api/init.ru:1 warning: already initialized constant ROOT
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Plugin foo version 9.0.0.0 does not exist
........................................................................................................................ERROR: Configuration reloading also requires passing a configuration path with '-f yourlogstash.conf'
...............................................Updating dummy
...........................................................................................................................................................................................................Validating dummy
.....................................F......................................

Failures:

  1) JVM stats LogStash::Api::HotThreadsCommand#schema return hot threads information
     Failure/Error: expect(report.to_s).not_to be_empty
       Double "agent" received unexpected message :uptime with (no args)
     # ./logstash-core/lib/logstash/api/lib/app/command.rb:22:in `uptime'
     # ./logstash-core/lib/logstash/api/lib/app/commands/stats/hotthreads_command.rb:112:in `cpu_time_as_percent'
     # ./logstash-core/lib/logstash/api/lib/app/commands/stats/hotthreads_command.rb:54:in `to_hash'
     # ./logstash-core/lib/logstash/api/lib/app/commands/stats/hotthreads_command.rb:78:in `each'
     # ./logstash-core/lib/logstash/api/lib/app/commands/stats/hotthreads_command.rb:73:in `each'
     # ./logstash-core/lib/logstash/api/lib/app/commands/stats/hotthreads_command.rb:52:in `to_hash'
     # ./logstash-core/lib/logstash/api/lib/app/commands/stats/hotthreads_command.rb:35:in `to_s'
     # ./logstash-core/spec/api/lib/commands/jvm_spec.rb:21:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'

Finished in 25.24 seconds (files took 3.7 seconds to load)
1645 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/api/lib/commands/jvm_spec.rb:20 # JVM stats LogStash::Api::HotThreadsCommand#schema return hot threads information

Randomized with seed 872
```

And also now I always see the message at startup:

```
/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/api/init.ru:1 warning: already initialized constant ROOT
```

**Comment by jsvd** [comment]
NOTE: the message only appears when running tests, not when running bin/logstash

bin/logstash -e "" --http-port=33333 --http-host=0.0.0.0
Settings: Default pipeline workers: 4
Logstash startup completed

**Comment by purbon** [comment]
This might be because of the line that require app/init.ru from the
spec_helper.rb.

**Comment by ph** [comment]
@purbon I will fix the failing test, since its blocking another PR.

**Comment by purbon** [comment]
Please, go ahead.

**Comment by ph** [comment]
LGTM

**Comment by ph** [comment]
I have created https://github.com/elastic/logstash/issues/4686 and merged this one,

**Pull request closed without merging**
