### PR TITLE
Fixed links and formatting

### PR DESCRIPTION
**Pull request by dedemorton**
Clint made some changes to the static files in logstash-docs to correct some links. This PR gets those changes into the logstash repo.

### CODE REVIEW

**Comment by suyograo** [comment]
LGTM

**Comment by dedemorton** [comment]
@suyograo I've pushed another commit because I noticed that there were a bunch of changes missing from master. It maybe doesn't matter since the files in 5.0 are correct, but on the off chance that someone looks at this content in master, I think it's good to have the latest/greatest. Cherry-picking was a little messy, so I just copied the contents from 5.0. Let me know if that's not Ok, and I can track down all the commits and cherry-pick.

**Comment by dedemorton** [comment]
This should be merged into master only. To avoid merge weirdness, I've created a separate PR that we can merge into 5.0/5.x.

**Comment by suyograo** [comment]
@dedemorton sounds good!

**Pull request closed without merging**
