### PR TITLE
Remove Debian 10 from CI

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

This commit removes Debian 10 (Buster) which is EOL since July 1 2024[^1] from CI.

## Related issues

Relates https://github.com/elastic/ingest-dev/issues/2872

[^1]: https://wiki.debian.org/LTS

### CODE REVIEW

**Comment by dliappis** [comment]
@jsvd / @flexitrev bump, could you please take a look?

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by dliappis** [comment]
@logstashmachine backport 8.15

**Comment by dliappis** [comment]
@logstashmachine backport 8.14

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Comment by dliappis** [comment]
Backports had to be created manually, due to conflicts for:

- `8.14`: https://github.com/elastic/logstash/pull/16328
- `7.17`: https://github.com/elastic/logstash/pull/16329

**Pull request merged**
