### PR TITLE
bump log4j version to 2.15.0

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Review by cob16 — APPROVED** [review]

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by prupert** [comment]
Will this also be backported to 6.8?

**Comment by guhan94** [comment]
Hi, any timeline on when `7.16.1` would be available to download ?

**Comment by prupert** [comment]
> Will this also be backported to 6.8?

Merged in https://github.com/elastic/logstash/pull/13500

**Comment by jyoti-khairnar** [comment]
Hello, 
When will 7.16.1 release be available to download?
Thanks

**Comment by mdennehy** [comment]
Hi folks, do we have any idea when 6.8.21 will release please? Thanks

**Pull request merged**
