### PR TITLE
regenerate webserver test certificates

### PR DESCRIPTION
**Pull request by jsvd**
```
./qa/integration/fixtures/webserver_certs [main]
❯ openssl x509 -in ./generated/server_from_intermediate.chain.crt -text -inform pem | grep "Not After"  
            Not After : Jul 15 18:27:28 2024 GMT

./qa/integration/fixtures/webserver_certs [main]
❯ git co regenerated_webserver_certs
Switched to branch 'regenerated_webserver_certs'

./qa/integration/fixtures/webserver_certs [regenerated_webserver_certs]
❯ openssl x509 -in ./generated/server_from_intermediate.chain.crt -text -inform pem | grep "Not After"
            Not After : Apr 12 15:35:03 2027 GMT
```

### CODE REVIEW

**Review by dliappis — APPROVED** [review]
The IT tests in PR checks are passing, so from me it's LGTM, but just to be 100% sure, I also triggered an exhaustive build with this PR https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/634 -- I suggest we merge after it gets green.

**Comment by jsvd** [comment]
Thank you, the exhaustive test is green, merging.

**Comment by jsvd** [comment]
@logstashmachine backport 8.15

**Comment by jsvd** [comment]
@logstashmachine backport 7.17

**Comment by jsvd** [comment]
@logstashmachine backport 8.14

**Pull request merged**
