### PR TITLE
JAVAFICATION: Move PluginFactory to Java

### PR DESCRIPTION
**Pull request by original-brownbear**
This reverts commit 219ebae452129e4ce581017b500c0ce7f01e3324.

The reason that initially made above revert necessary was that `logstash/plugins/registry` wasn't properly included when calling `Plugin.lookup`.
The moving of the plugin factory to Java necessitated breaking up a circular dependency here that caused this to come up in the first place.

Resolved by adding the `require "logstash/plugins/registry"` call to `Plugin.lookup`.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@andrewvc there we go, just one line changed from the initial version :) Should be fine now.

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by andrewvc** [comment]
Have you tried running the ES output tests against it? We should do that to be sure we haven't broken plugin land again.

**Comment by original-brownbear** [comment]
@andrewvc now I did :D all green:

```sh
➜  logstash-output-elasticsearch git:(master) LOGSTASH_PATH="/Users/brownbear/src/logstash" LOGSTASH_SOURCE="1" bundle exec rspec spec 
Sending Logstash logs to null which is now configured via log4j2.properties
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}

Randomized with seed 34344
........................................Generating a 2048 bit RSA private key
..+++
.....................................................................................................................+++
writing new private key to 'lumberjack.key'
-----
WARNING: You're overriding a previous stub implementation of `new`. Called from /Users/brownbear/src/logstash-output-elasticsearch/spec/unit/outputs/elasticsearch_ssl_spec.rb:75:in `block in (root)'.. Called from /Users/brownbear/src/logstash-output-elasticsearch/spec/unit/outputs/elasticsearch_ssl_spec.rb:75:in `block in (root)'.
.....................................................................................

Finished in 2 minutes 19.2 seconds (files took 4.03 seconds to load)
125 examples, 0 failures

Randomized with seed 34344
```

**Comment by original-brownbear** [comment]
good to go here given it's a one liner and plugin tests are green now :)?

**Comment by andrewvc** [comment]
LGTM

**Comment by original-brownbear** [comment]
@andrewvc thanks!

**Pull request closed without merging**
