### PR TITLE
 #8889 backport to 6.0 and 5.6

### PR DESCRIPTION
**Pull request by original-brownbear**
Backport of #8889

### CODE REVIEW

**Comment by original-brownbear** [comment]
@jsvd can't do that without pretty significant productive code changes :( I think this is trivial enough so that the risk of changing the production code (would have to port the changed way we bootstrap thhe Ruby classes in `6.1+` :() far outweighs the gain from the tests right?

**Comment by jsvd** [comment]
I see..one suggestion is to move the test up a layer and test the clone/dup operations [on the ruby class](https://github.com/elastic/logstash/blob/6.0/logstash-core/spec/logstash/timestamp_spec.rb), wdyt?

**Comment by original-brownbear** [comment]
@jsvd sure we can do that :) will add it here then

**Comment by original-brownbear** [comment]
Ruby specs added :)

**Comment by original-brownbear** [comment]
Tests failure is unrelated merging

**Comment by original-brownbear** [comment]
`5.6` needs separate backport ...

**Pull request closed without merging**
