### PR TITLE
remove the secondary pipeline

### PR DESCRIPTION
**Pull request by ph**

### CODE REVIEW

**Comment by ph** [comment]
This should remove the manticore and timeouts errors that you have experienced.

**Comment by purbon** [comment]
@ph why do we remove it for now? could we just add a flag and output everything for now to ```output/null```? then as soon as we introduce the settings we can enable proper shipping. what do you think?

**Comment by ph** [comment]
I prefer to remove until we have settings in place, things will certainly changes with that in place.

**Comment by purbon** [comment]
LGTM

**Pull request closed without merging**
