### PR TITLE
MINOR: Optimized map merge in org.logstash.Util#mapMerge

### PR DESCRIPTION
**Pull request by original-brownbear**
Saw the todo and took care of it as best as possible without larger changes:

* removed todo :P
* reusing sort buffer (saves creating a new `ArrayList<>` on the target also)
* avoid redundant map lookups
* size lists correctly when instantiating
* fixes JRuby error that shows with the newly added test, it fails with the following in `master`
```java
java.lang.IllegalArgumentException: Missing Ruby class handling for full class name=java.util.ArrayList, simple name=ArrayList

|tat org.logstash.Javafier.deep(Javafier.java:29)
|tat org.logstash.Event.getField(Event.java:147)
|tat org.logstash.EventTest.testAppendLists(EventTest.java:213)
|tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|tat java.lang.reflect.Method.invoke(Method.java:498)
|tat org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
|tat org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
|tat org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
|tat org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
|tat org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
|tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
|tat org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
|tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
|tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
|tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
|tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
|tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
|tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)
|tat org.junit.runner.JUnitCore.run(JUnitCore.java:137)
|tat com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
|tat com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
|tat com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
|tat com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### CODE REVIEW

**Comment by guyboertje** [comment]
@original-brownbear 
In your opinion, do the tests cover this code?

**Comment by original-brownbear** [comment]
@guyboertje hmm I couldn't find tests for the `List` meets `List` case ... let me check.

**Comment by original-brownbear** [comment]
@guyboertje so funny story :D I just pushed a tets for the array concat case ... it only works in this version. `master` is broken here.

**Comment by original-brownbear** [comment]
@guyboertje either way test added :)

**Pull request closed without merging**
