### PR TITLE
Add apache and elastic license headers to ruby and java files

### PR DESCRIPTION
**Pull request by jsvd**
This change was done using a script inlined below.
Manual corrections where needed in some files that had shebangs and/or started with code comments.

To the reviewer: this PR sets the foundation for keeping our code correctly identified regarding the license. After this is done a second phase will be to create a CI job that ensures the headers are present in new and existing files.

```ruby
HEADERS = {
  "apache" => {
    "java" => IO.read("apache2-license-header-java.txt"),
    "ruby" => IO.read("apache2-license-header-ruby.txt")
  },
  "elastic" => {
    "java" => IO.read("elastic-license-header-java.txt"),
    "ruby" => IO.read("elastic-license-header-ruby.txt")
  }
}

def fetch_header_for(file)
  license = file.match(/^x-pack/) ? "elastic" : "apache"
  return HEADERS[license]["ruby"] if file.match(".*Rakefile$")
  lang = case File.extname(file)
         when ".java" then "java"
         when ".rb", ".erb", ".rake" then "ruby"
         else nil
         end
  HEADERS[license][lang]
end

def find_header_range(array)
  index = array.find_index {|x| x.match("^[^#]") }
  index || 0
end

def fix_header_in(file)
  file_content = IO.read(file)
  array = file_content.split("\n")
  index = find_header_range(array)
  contents_without_headers = array[index..-1]
  license = fetch_header_for(file)
  return unless license
  content = ([license] + contents_without_headers).join("\n")
  content << "\n" if file_content[-1] == "\n"
  IO.write(file, content)
rescue => e
  puts "error with #{file}: (#{e.class}) #{e.message}"
end

Dir.glob("**/*.java").each { |file| fix_header_in(file) }
Dir.glob("**/*.rb").each { |file| fix_header_in(file) }
Dir.glob("**/Rakefile").each { |file| fix_header_in(file) }
Dir.glob("**/*.erb").each { |file| fix_header_in(file) }
Dir.glob("**/*.rake").each { |file| fix_header_in(file) }
```

[EDIT] this pr also takes the opportunity to remove any encodig magic comment, since we don't support ruby 1.9/jruby 1.7.x anymore

### CODE REVIEW

**Comment by andsel** [comment]
@jsvd for `Rakefiles` we do the license check, but for `*.gradle` we need or not to do the same check?

**Comment by jsvd** [comment]
good point Andrea, added!

**Comment by andsel** [comment]
LGTM

**Comment by jsvd** [comment]
backported to 7.x 1fc169b7f

**Pull request merged**
