### PR TITLE
Split java/ruby unit test steps on Windows

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

As a follow up to #15861 this commit splits the current unit tests step for the Windows JDK matrix pipeline to two that run Java and Ruby unit tests separately.

## How to test this PR locally

Test runs in Buildkite:

- Windows: https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/98
- Linux (should be unaffected, just to double check for any bug): https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/120
## Related issues

- Closes https://github.com/elastic/logstash/issues/15566

### CODE REVIEW

**Comment by dliappis** [comment]
Blocked by https://github.com/elastic/logstash/issues/15890

**Comment by dliappis** [comment]
I merged [the fix](https://github.com/elastic/logstash/pull/15975) for https://github.com/elastic/logstash/issues/15890 in this PR and triggered a test run in https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/123#_ to verify the fix.

**Comment by dliappis** [comment]
Now that the [fix](https://github.com/elastic/logstash/pull/15975) for the blocker has been merged, I merged main again in this PR and did a final BK re-run that verifies everything's ok: https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/124

**Review by mashhurs — APPROVED** [review]
LGTM!

**Comment by dliappis** [comment]
@logstashmachine backport 8.13

**Comment by dliappis** [comment]
@logstashmachine backport 8.12

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Pull request merged**
