### PR TITLE
Release 2.4.0.snapshot1

### PR DESCRIPTION
**Pull request by suyograo**
This PR moves from 2.4.0.dev1 to snapshot1 in prep for a release. I also published
required gems to RubyGems so it no longer uses locally built gems.

Remember that 2.4.0 core can install 5.x plugins. So, I had to curate the Gemfile to not drag in 5.x plugins. It was pretty easy and I added the version constraints.

<details>
<summary>Gemfile diff between 2.4.0 and 2.3.4</summary>
```
suyog@machine:/tmp$ diff 2.3.4.plugins 2.4.0.plugins
diff --git a/2.3.4.plugins b/2.4.0.plugins
index 9420bec..bae14b9 100644
--- a/2.3.4.plugins
+++ b/2.4.0.plugins
@@ -10,7 +10,7 @@ logstash-codec-json_lines (2.1.3)
logstash-codec-line (2.1.2)
logstash-codec-msgpack (2.0.4)
logstash-codec-multiline (2.0.11)
logstash-codec-netflow (2.1.0)(2.1.1)
logstash-codec-oldlogstashjson (2.0.4)
logstash-codec-plain (2.0.4)
logstash-codec-rubydebug (2.0.7)
@@ -53,8 +53,8 @@ logstash-input-http (2.2.3)
logstash-input-http_poller (2.0.6)
logstash-input-imap (2.0.5)
logstash-input-irc (2.0.5)
logstash-input-jdbc (3.0.2)(3.1.0)
logstash-input-kafka (2.0.8)(2.0.9)
logstash-input-log4j (2.0.7)
logstash-input-lumberjack (2.0.7)
logstash-input-pipe (2.0.4)
@@ -92,7 +92,7 @@ logstash-output-null (2.0.4)
logstash-output-opentsdb (2.0.4)
logstash-output-pagerduty (2.0.4)
logstash-output-pipe (2.0.4)
logstash-output-rabbitmq (3.1.0)(3.1.2)
logstash-output-redis (2.0.5)
logstash-output-s3 (2.0.7)
logstash-output-sns (3.0.4)
suyog@machine:/tmp$
```

</details>

<details>
<summary>Tested update plugin on 2.4.0</summary>

I was surprised that `bin/plugin install --version` will bump to 5.x plugins, but `bin/plugin update` will not.

```
suyog@machine:/tmp/logstash-2.4.0.snapshot1$ bin/logstash-plugin install --version 5.0.3 logstash-input-kafka
Validating logstash-input-kafka-5.0.3
Installing logstash-input-kafka
Installation successful
```
</details>

<details>
<summary>Basic testing on 2.4.0.snapshot1</summary>

```
suyog@machine:/tmp/logstash-2.4.0.snapshot1$ bin/logstash --version
logstash 2.4.0.snapshot1
suyog@machine:/tmp/logstash-2.4.0.snapshot1$ bin/logstash -e 'input { generator { "message" => "this is a bats test for -e" count => 1 }} output { stdout {} }'
Settings: Default pipeline workers: 8
Pipeline main started
2016-08-19T04:21:13.162Z Suyogs-MBP-2 this is a bats test for -e
Pipeline main has been shutdown
stopping pipeline {:id=>"main"}
```
</details>

### CODE REVIEW

**Comment by suyograo** [comment]
@jsvd @ph can you review please?

**Comment by jsvd** [comment]
I tested this pr: the package builds correctly, tests pass, and logstash works..
what I noticed is that we (still have?) plugin update broken:

```
/tmp/logstash-2.4.0.snapshot1 % bin/plugin update logstash-codec-collectd
You are updating logstash-codec-collectd to a new version 3.0.2, which may not be compatible with 2.0.4. are you sure you want to proceed (Y/N)?
Y
Updating logstash-codec-collectd
No plugin updated
/tmp/logstash-2.4.0.snapshot1 % bin/logstash-plugin list --verbose collectd
logstash-codec-collectd (2.0.4)
```

**Comment by ph** [comment]
@jsvd Concerning the update, I think the 2.4 branch doesn't have this PR in https://github.com/elastic/logstash/pull/5729, It was merged in 2.X, we might want to get that in before release 2.4?

**Comment by suyograo** [comment]
@jsvd and @ph merged https://github.com/elastic/logstash/pull/5729 to 2.4

**Comment by ph** [comment]
OK, this PR works on my machine and it successfully build a working artifact.
I have looked at the failing build on Travis; it seems it doesn't invoke `rake test:core` but bundle install.

If you look more closely at the travis job you see where this invocation is wrong.
```
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.12.5
$ gem --version
2.4.8
968.79s$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/WARNING: SSLSocket#session= is not supported
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

**Comment by ph** [comment]
LGTM, and it now work on travis.

**Pull request closed without merging**
