### PR TITLE
Release notes draft for 7.13.2

### PR DESCRIPTION
**Pull request by logstashmachine**
**PREVIEW:** https://logstash_12981.docs-preview.app.elstc.co/guide/en/logstash/7.13/logstash-7-13-2.html

### CODE REVIEW

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by karenzone — APPROVED** [review]
Builds cleanly and LGTM

**Review by kaisecheng — APPROVED** [review]
LGTM 🐇 Thanks for generating the release note :)

**Review by kares — APPROVED** [review]
looking good

**Pull request merged**
