### PR TITLE
Add Client Cert Auth to Lumberjack input.

### PR DESCRIPTION
**Pull request by packplusplus**
Matches with https://github.com/elasticsearch/logstash-forwarder/pull/243

Three options, CA to match, if the system CAs are to be trusted, and if
we want to verify the clients signer. Three options because there may
be a case where someone wants to trust any client certs signed by the
system CAs.

### CODE REVIEW

**Comment by klj613-boxuk** [comment]
status of this?

**Comment by scratch-net** [comment]
Any news?

**Comment by dbrgn** [comment]
This would be great!

**Comment by xaqq** [comment]
Hello,

I'd like to know more about the status of this.
If there a reason why this patch (and the related patch: https://github.com/elastic/logstash-forwarder/pull/243 ) haven't been merged?

This is an important feature for me as it allows safe remote access to the lumberjack server. Currently I have to use ssh tunnel or VPN to achieve this.

**Comment by scratch-net** [comment]
@xaqq https://github.com/driskell/log-courier has the client cert validation and many more features

**Comment by ersushantsood** [comment]
Hi All is this support available in Logstash input lumberjack plugin ?

**Comment by packplusplus** [comment]
@ersushantsood I thought I had closed this PR. We switched to using log-courier (referenced above). Also, looking back at this I wrote code....ewwwww.....

**Pull request closed without merging**
