### PR TITLE
Update logstash.asciidoc

### PR DESCRIPTION
**Pull request by Roshan-Poudel**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by logstashmachine** [comment]
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

**Comment by karenzone** [comment]
jenkins test this please

**Comment by Roshan-Poudel** [comment]
I have signed the contributor agreement (CLA)

**Comment by karenzone** [comment]
Thank you! I'll take a look.

**Review by karenzone — APPROVED** [review]
Looks good to me. Thanks for contributing to our documentation.

**Pull request merged**
