### PR TITLE
Pin `date` dependency to `3.3.3`

### PR DESCRIPTION
**Pull request by robbavey**
Resolves: #16095, #16754

### CODE REVIEW

**Review by donoghuc — APPROVED** [review]
WIll just have to make sure to update to match jruby as they update their defaults 😅

**Comment by robbavey** [comment]
@logstashmachine backport 8.x

**Comment by jsvd** [comment]
@logstashmachine backport 8.16

**Comment by jsvd** [comment]
@logstashmachine backport 8.17

**Pull request merged**
