### PR TITLE
Remove `mem` block from `/node` API response

### PR DESCRIPTION
**Pull request by ph**
Part of https://github.com/elastic/logstash/issues/5732 effort

### CODE REVIEW

**Comment by jsvd** [comment]
After executing `curl localhost:9600/_node?pretty` both in master and with this PR I see no difference in the output response. Is this just an internal cleanup?

**Comment by ph** [comment]
@jsvd Not this PR actually remove a duplicate `mem` key at the root of the json response. The `mem` is now inside the `jvm` key.

See this diff. 
```diff
diff --git a/master_api_node_stats.json b/branch_api_stats.json
index 13993d4..d85cf8a 100644
--- a/master_api_node_stats.json
+++ b/branch_api_stats.json
@@ -1,3 +1,4 @@
+
 {
   "host" : "sashimi",
   "version" : "5.0.0-alpha6",
@@ -5,33 +6,33 @@
   "jvm" : {
     "threads" : {
       "count" : 22,
-      "peak_count" : 25
+      "peak_count" : 23
     },
     "mem" : {
-      "heap_used_in_bytes" : 371243248,
-      "heap_used_percent" : 17,
+      "heap_used_in_bytes" : 346788704,
+      "heap_used_percent" : 16,
       "heap_committed_in_bytes" : 519045120,
       "heap_max_in_bytes" : 2077753344,
-      "non_heap_used_in_bytes" : 155013872,
-      "non_heap_committed_in_bytes" : 163659776,
+      "non_heap_used_in_bytes" : 151513296,
+      "non_heap_committed_in_bytes" : 159367168,
       "pools" : {
         "survivor" : {
           "peak_used_in_bytes" : 8912896,
-          "used_in_bytes" : 12874240,
+          "used_in_bytes" : 13604560,
           "peak_max_in_bytes" : 34865152,
           "max_in_bytes" : 69730304,
           "committed_in_bytes" : 17825792
         },
         "old" : {
-          "peak_used_in_bytes" : 110936616,
-          "used_in_bytes" : 221873232,
+          "peak_used_in_bytes" : 110281904,
+          "used_in_bytes" : 220563808,
           "peak_max_in_bytes" : 724828160,
           "max_in_bytes" : 1449656320,
           "committed_in_bytes" : 357957632
         },
         "young" : {
           "peak_used_in_bytes" : 71630848,
-          "used_in_bytes" : 136495776,
+          "used_in_bytes" : 112620336,
           "peak_max_in_bytes" : 279183360,
           "max_in_bytes" : 558366720,
           "committed_in_bytes" : 143261696
@@ -40,78 +41,47 @@
     }
   },
   "process" : {
-    "open_file_descriptors" : 49,
-    "peak_open_file_descriptors" : 50,
+    "open_file_descriptors" : 47,
+    "peak_open_file_descriptors" : 47,
     "max_file_descriptors" : 10240,
     "mem" : {
-      "total_virtual_in_bytes" : 5199130624
+      "total_virtual_in_bytes" : 5178032128
     },
     "cpu" : {
-      "total_in_millis" : 36380355000,
+      "total_in_millis" : 37138756000,
       "percent" : 1
     }
   },
-  "mem" : {
-    "heap_used_in_bytes" : 371243248,
-    "heap_used_percent" : 17,
-    "heap_committed_in_bytes" : 519045120,
-    "heap_max_in_bytes" : 2077753344,
-    "non_heap_used_in_bytes" : 155013872,
-    "non_heap_committed_in_bytes" : 163659776,
-    "pools" : {
-      "survivor" : {
-        "peak_used_in_bytes" : 8912896,
-        "used_in_bytes" : 12874240,
-        "peak_max_in_bytes" : 34865152,
-        "max_in_bytes" : 69730304,
-        "committed_in_bytes" : 17825792
-      },
-      "old" : {
-        "peak_used_in_bytes" : 110936616,
-        "used_in_bytes" : 221873232,
-        "peak_max_in_bytes" : 724828160,
-        "max_in_bytes" : 1449656320,
-        "committed_in_bytes" : 357957632
-      },
-      "young" : {
-        "peak_used_in_bytes" : 71630848,
-        "used_in_bytes" : 136495776,
-        "peak_max_in_bytes" : 279183360,
-        "max_in_bytes" : 558366720,
-        "committed_in_bytes" : 143261696
-      }
-    }
-  },
   "pipeline" : {
     "events" : {
-      "in" : 3500,
-      "filtered" : 3000,
-      "out" : 3000
+      "in" : 2499,
+      "filtered" : 1999,
+      "out" : 1999
     },
     "plugins" : {
       "inputs" : [ ],
       "filters" : [ {
         "id" : "sleep_510eb569aee937aacd3650e004af8325c08d496e-2",
         "events" : {
-          "duration_in_millis" : 4327,
-          "in" : 3111,
-          "out" : 3111
+          "duration_in_millis" : 2931,
+          "in" : 2062,
+          "out" : 2062
         },
         "name" : "sleep"
       }, {
         "id" : "sleep_510eb569aee937aacd3650e004af8325c08d496e-3",
         "events" : {
-          "duration_in_millis" : 318128,
-          "in" : 3111,
-          "out" : 3107
+          "duration_in_millis" : 209925,
+          "in" : 2062,
+          "out" : 2058
         },
         "name" : "sleep"
       } ],
       "outputs" : [ {
         "id" : "510eb569aee937aacd3650e004af8325c08d496e-4",
         "events" : {
-          "in" : 3000,
-          "out" : 3000
+          "in" : 1999,
+          "out" : 1999
         },
         "name" : "510eb569aee937aacd3650e004af8325c08d496e-4"
       } ]

```

**Comment by jsvd** [comment]
This is what I'm seeing in master now:

```
~/projects/logstash (git)-[master] % git lg | head -n1
* ebed724 - (HEAD -> master, upstream/master) Override default behavior of travis to use `bundle install` and uses rake test:core instead (3 days ago) <Pier-Hugues Pellerin>
~/projects/logstash (git)-[master] % bin/logstash -e ""
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.3 - omit version 2.7.0
Pipeline main started
```

```
% curl localhost:9600/_node?pretty
{
  "host" : "Joaos-MBP.lan",
  "version" : "5.0.0-alpha6",
  "http_address" : "127.0.0.1:9600",
  "pipeline" : {
    "workers" : 4,
    "batch_size" : 125,
    "batch_delay" : 5
  },
  "os" : {
    "name" : "Mac OS X",
    "arch" : "x86_64",
    "version" : "10.11.5",
    "available_processors" : 4
  },
  "jvm" : {
    "pid" : 18092,
    "version" : "1.8.0_20",
    "vm_name" : "Java HotSpot(TM) 64-Bit Server VM",
    "vm_version" : "1.8.0_20",
    "vm_vendor" : "Oracle Corporation",
    "start_time_in_millis" : 1471872617817,
    "mem" : {
      "heap_init_in_bytes" : 268435456,
      "heap_max_in_bytes" : 1038876672,
      "non_heap_init_in_bytes" : 2555904,
      "non_heap_max_in_bytes" : 0
    },
    "gc_collectors" : [ "ParNew", "ConcurrentMarkSweep" ]
  }
}
```

**Comment by jsvd** [comment]
LGTM

**Pull request closed without merging**
