### PR TITLE
 Added test configuration files for #7403

### PR DESCRIPTION
**Pull request by bmhughes**
As requested in issue #7403 added my configuration files that produce the duplicate IDs error on Logstash start up.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this please

**Comment by original-brownbear** [comment]
@bmhughes Seems we have an issue with the CLA, did you sign the CLA with the same email address used in that commit?

**Comment by bmhughes** [comment]
Yes all the same and I've had the confirmation emails come through as well.

**Comment by original-brownbear** [comment]
@bmhughes perfect, now it's green. Just had to trigger it again by adding a space to the PR title :) 
Thanks again!

**Comment by original-brownbear** [comment]
test failure is unrelated, merging this

**Pull request closed without merging**
