### PR TITLE
remove :cluster_uuids gauge

### PR DESCRIPTION
**Pull request by jsvd**
resolves https://github.com/elastic/logstash/issues/10886

### CODE REVIEW

**Comment by yaauie** [comment]
It looks likes this correctly removes the _UNUSED_ gauge, and that the API correctly populates its value from plugin metadata instead of using the gauge ([7.x](https://github.com/elastic/logstash/blob/7.x/logstash-core/lib/logstash/api/commands/node.rb#L107), [master](https://github.com/elastic/logstash/tree/master/logstash-core/lib/logstash/api/commands/node.rb#L107)).

LGTM 👍

**Comment by jsvd** [comment]
@yaauie Unfortunately this broke the direct metric collection, where this metric is expected to exist.
I proposed an alternative way to fetch this metric in https://github.com/elastic/logstash/pull/11777/files#r407426102

**Comment by yaauie** [comment]
:facepalm: I missed that. 

Glad to see the proposed fix has already been approved and merged though 👍🏼

**Comment by jasonperrone** [comment]
Sorry for the stupid question guys, but I downloaded the current logstash 7.6.2 from the download site and this problem exists there. How do I get this fix?

**Comment by anaescagu** [comment]
Same as @jasonperrone

**Comment by jasonperrone** [comment]
It's still in 7.7.0 BTW

**Comment by alter** [comment]
Yeah, I also get it in 7.7

**Pull request merged**
