### PR TITLE
[ci] JDK matrix Buildkite pipelines (part 1)

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

This commit is the first part of the migration of JDK matrix tests
from Jenkins to Buildkite. There will be two separate pipelines, for
Linux and Windows, and this commit only adds the Linux one.

Linux support is currently limited to Ubuntu 22.04 and 20.04, but
additional operating systems will be added seamlessly outside of the Logstash
repository, via through additional VM images.

Pipeline steps are created dynamically and the underlying script is meant to be
common for Linux and Windows. Windows is currently a stub and
will be added in a follow up PR.

## Checklist

- [x] My code follows the style guidelines of this project
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)~
- [x] I have added tests that prove my fix is effective or that my feature works -> see https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/11

## How to test this PR locally

Trigger a build by clicking https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline#new and using `pull/15539/merge` in the `branch` field.

## Related issues

- https://github.com/elastic/ingest-dev/issues/1725
- https://github.com/elastic/ci-agent-images/pull/424

## Screenshots

When the (Linux) job gets triggered manually, it's paused prompting the user to choose:

image

once that's done, it runs the jobs in groups per "OS-JDK".
The steps are dynamically built and [emitted](https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/11#018bb005-fb0c-4a37-9337-f53831c3691e/80) for debugging/reference purposes.
We also display a markdown table per group, with the status of each individual test using annotations like:

image

### CODE REVIEW

**Comment by dliappis** [comment]
@roaksoax see https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/63 for an example of a build.

**Comment by dliappis** [comment]
@roaksoax this is now ready for review. Note that IT tests 1 / PQ IT tests 1 are failing because https://github.com/elastic/logstash/pull/15535 hasn't been merged.
If you want to test it, just click https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline#new , use `pull/15539/merge` in the `branch` field, and choose the OS / JDK in the next step (currently for OS only Ubuntu 22.04 / 20.04 images are available).

**Review by roaksoax — APPROVED** [review]
lgtm! maybe we can make the annotations shorter or links to failed jobs, but we can chat and make those as future improvements.

**Comment by dliappis** [comment]
@logstashmachine backport 8.11

**Comment by dliappis** [comment]
@logstashmachine backport 8.10

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Pull request merged**
