### PR TITLE
Remove obsolete plugin version notice

### LINKED ISSUE #15012: Remove obsolete code that causes incorrect plugin related message
**Logstash information**:

Please include the following information:

1. Logstash version: 8.7.0
2. Logstash installation source: DEB

**Plugins installed**: 

logstash-filter-elastic_integration

**Description of the problem including expected versus actual behavior**:

Logstash is providing a message about an unsupported plugin because of the version.  The specific plugin version is 
 0.1.0, and because of that, Logstash is raising:
 
` Apr 19 20:53:13 andreserl-logstash-performance-ssd logstash[2310]: [2023-04-19T20:53:13,280][INFO ][logstash.filters.elasticintegration] Using version 0.1.x filter plugin 'elastic_integration'. This plugin isn't well supported by the community and likely has no maintainer.`

Code to remove: https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/config/mixin.rb#L277-L304

References: https://github.com/elastic/logstash/blob/main/logstash-core/locales/en.yml#L56-L63

### PR DESCRIPTION
**Pull request by roaksoax**
## What does this PR do?
Removes obsolete plug-in version notice that conveys a plugin under 1.0.0 is badly or not supported.

Closes #15012

### CODE REVIEW

**Review by jsvd — DISMISSED** [review]
Tests about this feature need to be removed now: https://github.com/elastic/logstash/blob/main/logstash-core/spec/logstash/plugin_spec.rb#L158-L194

**Comment by roaksoax** [comment]
Jenkins test this again

**Comment by roaksoax** [comment]
Jenkins test this again please

**Review by jsvd — APPROVED** [review]
LGTM, tests failing due to PR not being rebased against main

**Comment by jsvd** [comment]
@logstashmachine backport 8.8

**Pull request merged**
