### PR TITLE
[Doc]Add guidelines for setting jvm heap size

### LINKED ISSUE #10694: [Doc] Improve content for JVM heap recommendations
Improve and expand content

### PR DESCRIPTION
**Pull request by karenzone**
Resolves #10694 

**PREVIEW:** http://logstash_11716.docs-preview.app.elstc.co/guide/en/logstash/master/heap-size.html

### CODE REVIEW

**Comment by karenzone** [comment]
Comments and suggestions:
* I would make a recall that those settings are configured in jvm.options  file, or a link to the docs where we describe that file - @andsel 
* The "should" 4-8 heap size could maybe be rephrased that the "recommended heap size for" ...
"typical ingestion scenarios" ?  - @kares

**Comment by karenzone** [comment]
Hi @andsel and @kares.  Thanks for your suggestions. I have added them to the docs, and they should be reflected in the preview.  Any other suggestions?

**Comment by andsel** [comment]
LGTM

**Comment by kares** [comment]
:+1: seems to me like a very decent starting point to have

**Comment by yuwtennis** [comment]
Cheked this [onlin](https://www.elastic.co/guide/en/logstash/master/heap-size.html) as well.

>The recommended heap size for typical ingestion scenarios should be no less than 4GB and no more than 8GB.

@karenzone Thank you very much for you work.

**Pull request closed without merging**
