### PR TITLE
add proxy support for monitoring and centralized management

### PR DESCRIPTION
**Pull request by lhuet**
LS monitoring and centralized configuration features currently don't work when there is a proxy between LS and ES. This PR removes this limitation.
Related issues: #9560 and #11343 
@karenzone This PR includes some tiny doc updates that need to be reviewed

### CODE REVIEW

**Comment by andsel** [comment]
@lhuet I think the commit breaks the build, the introduced field make fail the task `runXPackIntegrationTests`.

In your local copy try `./gradlew clean runXPackIntegrationTests`

**Comment by lhuet** [comment]
@andsel The build `./gradlew clean runXPackIntegrationTests` produice an error. As the build is ok in v7.4.2 (version used for the initial development), I need to dig into this build error to understand what is wrong in the master.

**Comment by andsel** [comment]
@lhuet I've rebased to master (7.5.0) because there were some changes that fixed the error

**Comment by lhuet** [comment]
Jenkins test this please

**Comment by ktibi** [comment]
Hello elastic team,

any update for this PR ? @andsel @lhuet

**Comment by andsel** [comment]
as I know @lhuet was working on making the test green

**Comment by jsvd** [comment]
@lhuet there are some changes to the gradle configuration that aren't related to this PR's intent, can you rebase this against master?

**Comment by lhuet** [comment]
@jsvd Local build is OK but jenkins build is KO (https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/773/console). It seems it's an issue not related to this PR (Elasticsearch local instance not reachable).

**Comment by roaksoax** [comment]
Jenkins test this again please

**Comment by kares** [comment]
any objection on closing this one, since https://github.com/elastic/logstash/pull/11799 was merged to master/7.x ?

**Comment by lhuet** [comment]
@kares This PR has been replaced by #11799 and can be closed safely 👍

**Pull request closed without merging**
