### PR TITLE
Obtain file lock through FileLockFactory for DLQ #8124

### LINKED ISSUE #8124: DRY .lock handling in DLQ
I realized that the DLQ code in https://github.com/elastic/logstash/blob/cacc352e94a90e960492891480bc3a97d18ecd2c/logstash-core/src/main/java/org/logstash/common/io/DeadLetterQueueWriter.java#L65-L69 is using its own logic to handle the exclusive locking. 

It should probably be better to reuse the existing `FileLockFactory` https://github.com/elastic/logstash/blob/d1aa2864c667d00cb6b2d3780d50f4a8360226da/logstash-core/src/main/java/org/logstash/FileLockFactory.java

/cc @robbavey

### PR DESCRIPTION
**Pull request by liketic**
Resolves #8124 .

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this please

**Comment by jakelandis** [comment]
@liketic - Can you re-based this PR ? We just changed some of the script names used by Jenkins, hence the logstash-ci failure.

**Comment by liketic** [comment]
@jakelandis Rebase done. I think everything is OK this time. Thanks. 😄

**Comment by robbavey** [comment]
jenkins test this please

**Comment by original-brownbear** [comment]
@robbavey LGTM, any comments from your end? :)

**Comment by original-brownbear** [comment]
Merging this, I can't see how we'd have controversy here :)

**Comment by colinsurprenant** [comment]
version tags were not added. adding.

**Pull request closed without merging**
