### PR TITLE
refactor linux launch scripts per #8261

### LINKED ISSUE #8261: [discuss] unify launch scripts options support
The new Windows launch scripts in #8178 is changing some behaviours from the Linux launch scripts:

- existing `JAVA_OPTS` env var is now ignored, [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L37-L42)
- `JAVA_TOOL_OPTIONS` env var is cleared,  [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L31-L35)
- now only `LS_JAVA_OPTS` env var is supported to append options to parsed options in the `jvm.options` file.
- dropped the support of the `USE_RUBY` and `USE_DRIP` env vars. These not used anymore I believe. 

My proposal is to also apply these changes to the Linux launch scripts. 
WDYT?

### PR DESCRIPTION
**Pull request by colinsurprenant**
fixes #8261

This is a cleanup of the linux launch scripts, with these changes:
- existing `JAVA_OPTS` env var is now ignored, [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L37-L42)
- `JAVA_TOOL_OPTIONS` env var is cleared,  [ES is also doing this](https://github.com/elastic/elasticsearch/blob/33faf5ec70a29177eb50eccded4e2f103f938fc8/distribution/src/main/resources/bin/elasticsearch-env.bat#L31-L35)
- now only `LS_JAVA_OPTS` env var is supported to append options to parsed options from the `jvm.options` file.
- dropped support of the `LS_JVM_OPTS` env var 
- dropped support of the `USE_RUBY` and `USE_DRIP` env vars. These not used anymore I believe.

I tested locally on OSX these scenarios:
- plain `bin/logstash -e ''` to verify that `config/jvm.options` is used
- `bin/logstash -e '' --path.settings ...` to verify that `jvm.options` in that new path is used
- `LS_JAVA_OPTS=-Xmx3g bin/logstash -e ''` overrides the `jvm.options`
- `LS_JAVA_OPTS=-Xmx3g bin/logstash -e '' --path.settings ...` overrides the `jvm.options`

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this please

**Comment by original-brownbear** [comment]
@colinsurprenant LGTM, manually tested that Java_OPTS are still loaded as before from the file and all looks just fine :)

**Comment by colinsurprenant** [comment]
Green? 🍏 📗 💚 🥗 
Let's merge!

**Comment by colinsurprenant** [comment]
actually, we wanted to evaluate the changes to see if we'd merge in 6 or not. @jordansissel @suyograo

**Comment by ph** [comment]
@colin Can you also remove dripmain.rb from the repository?

**Comment by suyograo** [comment]
I am good to merge this to 6.0 if we test on Ubuntu and/or CentOS.

**Comment by colinsurprenant** [comment]
removed `dripmain.rb` ... good call @ph

I just successfully tested the `tar.gz` package from this branch on Ubuntu 14.04 + Java 8 the following:
- plain `bin/logstash -e ''` to verify that `config/jvm.options` is used
- `bin/logstash -e '' --path.settings ...` to verify that `jvm.options` in that new path is used
- `LS_JAVA_OPTS=-Xmx3g bin/logstash -e ''` overrides the `jvm.options`
- `LS_JAVA_OPTS=-Xmx3g bin/logstash -e '' --path.settings ...` overrides the `jvm.options`

**Comment by colinsurprenant** [comment]
Here's the plan for testing LS as a service:
- Ubuntu 14/15 for upstart
- CentOS 7 for systemd
- Debian 7 for sysv

I will do that manually now and take notes to propose how we could automate that in the acceptance tests.

**Comment by jordansissel** [comment]
lgtm based on @colinsurprenant's testing reports.

**Comment by colinsurprenant** [comment]
merged into master, 6.x and 6.0.

**Pull request merged**
