### PR TITLE
Add check to stop messages looping through DLQ

### PR DESCRIPTION
**Pull request by robbavey**
Add check to stop events from being written to the DLQ that have previously been written to the DLQ

### CODE REVIEW

**Comment by suyograo** [comment]
@robbavey can you update the behavior in the docs in this PR? https://github.com/elastic/logstash/blob/master/docs/static/dead-letter-queues.asciidoc

**Comment by robbavey** [comment]
@suyograo What are your thoughts for 6.1+ on loosening this by introducing the notion of a configurable 'dlq depth'? Effectively, we would mark each passage through the DLQ, by adding a metadata filter to the message, including a counter that could be updated each time a message goes through the dlq. We could default this value to 1, but as filters add DLQ capabilities, it may become useful to allow messages to go through the DLQ >1 time

**Comment by suyograo** [comment]
@robbavey I like the idea, but I wonder if we should keep it as is for the short term and make your proposed change of `depth` when we get a concrete usecase from a user?

**Comment by suyograo** [comment]
Anyways, this patch is LGTM

**Comment by robbavey** [comment]
@suyograo Backports all round for this? 5.5, 5.6, 6.0, and 6.x?

**Comment by suyograo** [comment]
@robbavey I think we can skip 5.5. This one is not super critical.

**Pull request closed without merging**
