### PR TITLE
Version bumps for 7.11

### PR DESCRIPTION
**Pull request by yaauie**
## What does this PR do?

Provides a dependencies and plugins lock in anticipation for the 7.11.0 release, as part of our standard release cycle.

Because the 7.x branch does not _have_ a lock file, it is easiest to view the diff commit-by commit:
 - first, we copy the dependencies verbatim from the 7.10.1 release
 - then, we update minor-level changes in plugins

### CODE REVIEW

**Review by kares — APPROVED** [review]
:package: updates looking :gem:

**Comment by yaauie** [comment]
TODO: retarget to 7.10 once branch is cut from 7.x.

**Comment by yaauie** [comment]
Base has been changed to the freshly-cut 7.11 branch. Head commit is the same so no rebuild needed.

**Comment by andsel** [comment]
LGTM

**Pull request merged**
