### PR TITLE
Bump from 5.5.3 -> 5.5.4

### PR DESCRIPTION
**Pull request by andrewvc**

### CODE REVIEW

**Comment by andrewvc** [comment]
Yep, probably the gemfile, will redo

**Comment by suyograo** [comment]
@andrewvc integ tests failed --

```sh
Failures:
  1) CLI > logstash-plugin prepare-offline-pack create a pack from a wildcard successfully create a pack
     Failure/Error: expect(unpacked.plugins.collect(&:name)).to include(*filters)
       expected ["logstash-filter-throttle", "logstash-filter-dissect", "logstash-filter-drop", "logstash-filter-date... "logstash-filter-csv", "logstash-filter-json", "logstash-filter-mutate", "logstash-filter-metrics"] to include "Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m"
```

Can you verify if this is related? If not, you can merge

**Comment by andrewvc** [comment]
This is a tricky one, all the offline integration specs pass locally, but not on travis, where they've failed twice in a row.

We really need the docker build system to troubleshoot things like this.

**Comment by andrewvc** [comment]
This test passes manually locally. I'm in favor of merging and waiting to see what the docker CI utils do to make this debuggable in the future .

**Pull request closed without merging**
