### PR TITLE
Use jruby-9.4.8.0 in exhaustive CIs.

### PR DESCRIPTION
**Pull request by mashhurs**
## Release notes

[rn:skip]

## What does this PR do?
BK Agent recently added a jruby-9.4.8.0 support and we need to use this version in the CI pipelines. This change adds a change to reflect into exhaustive pipeline.

## Why is it important/What is the impact to the user?
N.A

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## Related issues
-

### CODE REVIEW

**Comment by mashhurs** [comment]
@jsvd, FYI: exhaustive CI https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/762

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by jsvd** [comment]
@logstashmachine backport 8.x

**Comment by jsvd** [comment]
@logstashmachine backport 8.15

**Pull request merged**
