### PR TITLE
Add unit test to grant that production aliases correspond to a published RubyGem

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

[rn:skip]

## What does this PR do?

Loads the production plugin_aliases.yml definition file and check that every alias has
a properly published gem on RubyGems.
- add delete of generated `plugin_aliases.yml` to Gradle's clean task
- fix task dependency for copyPluginAlias task

## Why is it important/What is the impact to the user?

Before aliasing a plugin in production that plugin must have an empty gem, this test grant for this during the testing of Logstash.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Review by jsvd — CHANGES_REQUESTED** [review]
Testing this locally I couldn't make the test fail.
My steps:

1. edit `logstash-core/src/main/resources/org/logstash/plugins/AliasRegistry.yml`:
```yml
input:
  elastic_agent: beats
  meh: tcp
```

2. run `./gradlew javaTests --tests org.logstash.plugins.AliasRegistryTest.testProductionConfigAliasesGemsExists`

3. Observe that the test passes

It seems that the YAML isn't being loaded correctly, so the `aliasesDefinitions` Map is empty.

**Review by jsvd — APPROVED** [review]
LGTM

**Pull request merged**
