### PR TITLE
add path.data setting

### PR DESCRIPTION
**Pull request by jsvd**
implements https://github.com/elastic/logstash/issues/5404

delaying until the outcome of https://github.com/elastic/logstash/pull/5537 is decided

### CODE REVIEW

**Comment by jsvd** [comment]
@untergeek can I ask your help in this PR, I've added the `path.data` setting and it gets shipped in the .tar.gz and .zip artifacts.
But for the debs and rpms, what is the correct way to interface this setting to the user? I assume we need to do something similar to the path.settings?

**Comment by untergeek** [comment]
Sure.  The same changes you made to `config/logstash.yml` also need to go in `pkg/logstash.yml`

**Comment by jsvd** [comment]
if pkg/logstash.yml is a direct copy of config/logstash.yml, maybe we should just inject a copy during package creation time.
otherwise maintaining this may become painful.

**Comment by untergeek** [comment]
I already responded to your PR on the other side.  This will need to be thoroughly tested at the package level.  I tried this approach with my non-automated package testing when I created the current packaging setup.  It didn't work right. 😦 

Perhaps you can make something work differently.

**Comment by jsvd** [comment]
thanks for the input, will test thoroughly, my first offline build showed the file there, hence my pr:

```
joaoduarte@Joaos-MBP /tmp/package % tar -zxf ~/projects/logstash/build/logstash-5.0.0-SNAPSHOT.rpm
joaoduarte@Joaos-MBP /tmp/package % wc -l etc/logstash/logstash.yml
     106 etc/logstash/logstash.yml
joaoduarte@Joaos-MBP /tmp/package % rm -rf *
zsh: sure you want to delete all the files in /tmp/package [yn]? y
joaoduarte@Joaos-MBP /tmp/package % tar -zxf ~/projects/logstash/build/logstash-5.0.0-SNAPSHOT.deb
joaoduarte@Joaos-MBP /tmp/package % tar -zxf data.tar.gz
joaoduarte@Joaos-MBP /tmp/package % wc -l etc/logstash/logstash.yml
     106 etc/logstash/logstash.yml
```

**Comment by untergeek** [comment]
I was speaking more of the RPM/DEB packages...

**Comment by jsvd** [comment]
It is what I tested, I just unpacked them with tar.
I'm now running the acceptance tests on ubuntu and centos..

**Comment by untergeek** [comment]
:facepalm:

The RPM/DEB suffixes were cut off in my email.  I only saw the tar... 👀

**Comment by jsvd** [comment]
@untergeek it is now ready for review, I tested the rpm and debs, seem to work fine, even though we have no contents for that folder yet.

**Comment by untergeek** [comment]
LGTM™

Woo!  This is going to make things _very_ nice for plugins that need to keep any kind of state data!

**Pull request closed without merging**
