### PR TITLE
Test fix: Allow slowlog to have >= 1, instead of exactly 2 entries.

### LINKED ISSUE #8322: Integration Test failure: slowlog
Occasionally this test will error:

```
 2) Test Logstash Slowlog should write logs to a new dir
18:51:02      Failure/Error: expect(IO.read(slowlog_file).split("\n").size).to eq(2)
18:51:02      
18:51:02        expected: 2
18:51:02             got: 4
18:51:02      
18:51:02        (compared using ==)
18:51:02      # ./specs/slowlog_spec.rb:44:in `block in (root)'
18:51:02 
18:51:02 Finished in 7 minutes 51 seconds (files took 4.26 seconds to load)
18:51:02 17 examples, 2 failures
```

Looking at the logs it appears that more results were written then expected:
```
18:49:51 [2017-09-19T18:49:51,487][WARN ][slowlog.logstash.filters.sleep] event processing time {:plugin_params=>{"time"=>1, "every"=>2, "id"=>"95215a44d987e9adf837a9e0fedafd17bed40e85bcde713504949cbde12ab79b"}, :took_in_nanos=>1042408553, :took_in_millis=>1042, :event=>"{\"sequence\":1,\"host\":\"0ef6393e3296\",\"@timestamp\":\"2017-09-19T18:49:50.404Z\",\"@version\":\"1\",\"message\":\"Hello world!\"}"}
18:49:51 [2017-09-19T18:49:51,489][WARN ][slowlog.logstash.filters.sleep] event processing time {:plugin_params=>{"time"=>1, "every"=>2, "id"=>"95215a44d987e9adf837a9e0fedafd17bed40e85bcde713504949cbde12ab79b"}, :took_in_nanos=>1041947940, :took_in_millis=>1041, :event=>"{\"sequence\":0,\"host\":\"0ef6393e3296\",\"@timestamp\":\"2017-09-19T18:49:50.360Z\",\"@version\":\"1\",\"message\":\"Hello world!\"}"}
18:49:51 [2017-09-19T18:49:51,489][WARN ][slowlog.logstash.filters.sleep] event processing time {:plugin_params=>{"time"=>1, "every"=>2, "id"=>"95215a44d987e9adf837a9e0fedafd17bed40e85bcde713504949cbde12ab79b"}, :took_in_nanos=>1038075762, :took_in_millis=>1038, :event=>"{\"sequence\":3,\"host\":\"0ef6393e3296\",\"@timestamp\":\"2017-09-19T18:49:50.407Z\",\"@version\":\"1\",\"message\":\"Hello world!\"}"}
18:49:51 [2017-09-19T18:49:51,490][WARN ][slowlog.logstash.filters.sleep] event processing time {:plugin_params=>{"time"=>1, "every"=>2, "id"=>"95215a44d987e9adf837a9e0fedafd17bed40e85bcde713504949cbde12ab79b"}, :took_in_nanos=>1041975246, :took_in_millis=>1041, :event=>"{\"sequence\":2,\"host\":\"0ef6393e3296\",\"@timestamp\":\"2017-09-19T18:49:50.407Z\",\"@version\":\"1\",\"message\":\"Hello world!\"}"}
18:49:51 [2017-09-19T18:49:51,556][INFO ][logstash.pipeline        ] Pipeline terminated {"pipeline.id"=>"main"}
18:49:52   should write logs to a new dir (FAILED - 2)
```

This is just a timing issue and we should grant more allowances for how many lines are present.

### PR DESCRIPTION
**Pull request by jakelandis**
Fixes #8322

### CODE REVIEW

**Comment by jakelandis** [comment]
Jenkins test failure fixed by #8320

**Comment by jakelandis** [comment]
Found a case where it can be `1` instead of `2`.  since the test only cares about if the file was written to (not the exact value), i will update this PR for a fuzzier match.

**Comment by jakelandis** [comment]
Jenkins test this please.

**Comment by original-brownbear** [comment]
@jakelandis as I said already, the deeper issue is https://github.com/elastic/logstash/issues/8073#issuecomment-330681296 but ... **LGTM** still:

1. It'll be a pain updating this plugin version throughout all versions
2. It's not that important to fix the this plugin right now :)

**Pull request closed without merging**
