### PR TITLE
MetricType: Gauge

### LINKED ISSUE #4488: MetricType Gauge
Currently the metric collector only support the Counter type, we need to add support for a Gauge Type to support adhoc values, theses values could be:

- The size of queue 
- an eviction cache
- an uptime
- Number of threads
- a status?

### PR DESCRIPTION
**Pull request by ph**
Add a gauge type for the metric collector, this is useful for values
like size of a queue, actual memory

Fixes #4488

### CODE REVIEW

**Comment by purbon** [comment]
LGTM

**Comment by ph** [comment]
I love how easy it is to add something :D

**Comment by ph** [comment]
@purbon You can change your JVM branch to use that instead.

**Comment by purbon** [comment]
@ph sure.

**Pull request closed without merging**
