### PR TITLE
6.3.2 release notes

### PR DESCRIPTION
**Pull request by colinsurprenant**

### CODE REVIEW

**Comment by karenzone** [comment]
Builds correctly with no errors. 
In the Plugin section, the pull number for Dissect is formatted correctly. 
The next three (Graphic output, http output x2) have an extraneous left paren. If you match the formatting for Dissect, you should be good to go. 
screen shot 2018-07-23 at 1 24 42 pm

**Comment by colinsurprenant** [comment]
@karenzone thanks - fixed the formatting errors!

**Comment by karenzone** [comment]
@colinsurprenant   LGTM. Thanks!

**Comment by colinsurprenant** [comment]
merged in 6.3 and 6.x

**Pull request merged**
