### PR TITLE
add static analysis rake task for i18n usage

### PR DESCRIPTION
**Pull request by jsvd**
This PR adds a task that goes through all logstash-* ruby code, searches uses of `I18n.t("..."` and then checks if such keys exist in the `en.yml` file.

If matches are found, an exception is raised. The purpose of this is to be a pre step for most of the rake tasks to test and build logstash.

### CODE REVIEW

**Comment by ph** [comment]
@jsvd Any reason we dont use rspec for that?

**Comment by jsvd** [comment]
I can, this test wont use many features of rspec since it's just a static analysis task, but I'll give it a go.

**Comment by jsvd** [comment]
@ph refactored to be rspec:

```
% SPEC_OPTS="-e 'I18n' --order=default --format=documentation" rake test:core
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.1 - omit version 2.7.0
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.1 - omit version 2.7.1-1
Using Accessor#strict_set for specs
Run options:
  include {:full_description=>/I18n/}
  exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}

I18n
  when using en.yml
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/agent.rb"
      in line 81 the "logstash.agent.non_reloadable_config_register" key should exist
      in line 95 the "oops" key should exist
      in line 199 the "logstash.agent.non_reloadable_config_reload" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/environment.rb"
      in line 44 the "logstash.environment.jruby-required" key should exist
      in line 53 the "logstash.environment.missing-jars" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/output_delegator.rb"
      in line 46 the "logstash.pipeline.output-worker-unsupported-with-message" key should exist
      in line 48 the "logstash.pipeline.output-worker-unsupported" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/pipeline.rb"
      in line 399 the "logstash.pipeline.worker-error-debug" key should exist
      in line 404 the "logstash.pipeline.worker-error" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/plugin.rb"
      in line 126 the "logstash.pipeline.plugin-loading-error" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/runner.rb"
      in line 19 the "logstash.runner.flag.config" key should exist
      in line 23 the "logstash.runner.flag.config-string" key should exist
      in line 29 the "logstash.runner.flag.pipeline-workers" key should exist
      in line 34 the "logstash.runner.flag.pipeline-batch-size" key should exist
      in line 39 the "logstash.runner.flag.pipeline-batch-delay" key should exist
      in line 44 the "logstash.runner.flag.log" key should exist
      in line 49 the "logstash.runner.flag.verbosity" key should exist
      in line 52 the "logstash.runner.flag.quiet" key should exist
      in line 53 the "logstash.runner.flag.verbose" key should exist
      in line 54 the "logstash.runner.flag.debug" key should exist
      in line 57 the "logstash.runner.flag.debug_config" key should exist
      in line 61 the "logstash.runner.flag.version" key should exist
      in line 64 the "logstash.runner.flag.pluginpath" key should exist
      in line 69 the "logstash.runner.flag.configtest" key should exist
      in line 73 the "logstash.runner.flag.unsafe_shutdown" key should exist
      in line 78 the "logstash.runner.flag.rubyshell" key should exist
      in line 82 the "logstash.runner.flag.node_name" key should exist
      in line 86 the "logstash.runner.flag.auto_reload" key should exist
      in line 90 the "logstash.runner.flag.reload_interval" key should exist
      in line 94 the "logstash.web_api.flag.http_host" key should exist
      in line 98 the "logstash.web_api.flag.http_port" key should exist
      in line 102 the "logstash.runner.flag.allow-env" key should exist
      in line 168 the "logstash.runner.missing-configuration" key should exist
      in line 173 the "logstash.runner.reload-without-config-path" key should exist
      in line 184 the "logstash.runner.invalid-configuration" key should exist
      in line 227 the "oops" key should exist
      in line 279 the "logstash.runner.configuration.plugin_path_missing" key should exist
      in line 321 the "logstash.runner.configuration.log_file_failed" key should exist
      in line 346 the "logstash.runner.short-help" key should exist
      in line 361 the "logstash.runner.invalid-shell" key should exist
      in line 367 the "logstash.agent.sighup" key should exist
      in line 374 the "logstash.agent.sigterm" key should exist
      in line 382 the "logstash.agent.forced_sigint" key should exist
      in line 385 the "logstash.agent.sigint" key should exist
      in line 386 the "logstash.agent.slow_shutdown" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/api/lib/app/commands/stats/hotthreads_command.rb"
      in line 36 the "logstash.web_api.hot_threads.title" key should exist
      in line 39 the "logstash.web_api.hot_threads.thread_title" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/config/config_ast.rb"
      in line 347 the "logstash.runner.configuration.invalid_plugin_settings_duplicate_keys" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/config/loader.rb"
      in line 41 the "logstash.runner.configuration.scheme-not-supported" key should exist
      in line 56 the "logstash.runner.configuration.file-not-found" key should exist
      in line 92 the "logstash.runner.configuration.fetch-failed" key should exist
    in file "/Users/joaoduarte/projects/logstash/logstash-core/lib/logstash/config/mixin.rb"
      in line 89 the "logstash.runner.configuration.obsolete" key should exist
      in line 136 the "logstash.runner.configuration.invalid_plugin_settings" key should exist
      in line 295 the "logstash.plugin.version.0-1-x" key should exist
      in line 300 the "logstash.plugin.version.0-9-x" key should exist
      in line 310 the "logstash.plugin.no_version" key should exist
      in line 352 the "logstash.runner.configuration.setting_missing" key should exist
      in line 379 the "logstash.runner.configuration.setting_invalid" key should exist

Finished in 0.23 seconds (files took 3.92 seconds to load)
58 examples, 0 failures
```

**Comment by ph** [comment]
@jsvd the output look amazing! Better than I could imagine.

**Comment by ph** [comment]
LGTM, test pass,  ship it!

**Pull request closed without merging**
