### PR TITLE
Carry fwd pr #16116: add wolfi to exhaustive tests

### PR DESCRIPTION
**Pull request by jsvd**
On top of #16116, this PR:
* fixes uid of logstash user on the wolfi image (1000, not 10000);
* adds docker acceptance tests for the wolfi image;
* changes how tests are done on the java process, due to "ps -C" not being available on wolfi

replaces and closes https://github.com/elastic/logstash/pull/16116

### CODE REVIEW

**Review by roaksoax — APPROVED** [review]
LGTm!

**Comment by jsvd** [comment]
Exhaustive tests failed for this PR, so it's not ready yet for merging: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/504#018fceac-80b9-4ea4-b73a-4767f223d629

**Comment by jsvd** [comment]
Exhaustive tests are now passing for wolfi image: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/512#018fe8a8-c1bb-4c4f-8aa5-feb715cc1b28

**Comment by jsvd** [comment]
@roaksoax this is ready for a final review

**Review by roaksoax — APPROVED** [review]
LGTM!

**Pull request merged**
