### PR TITLE
6.x: Test stablization: Add timeout sleep.until to prevent infinite loop,resuce error on shutdown

### PR DESCRIPTION
**Pull request by jakelandis**
Forward port of the 5.x https://github.com/elastic/logstash/pull/7736

Please review as isolated PR (not port) since there are many differences here between 6.x and 5.x

### CODE REVIEW

**Comment by jordansissel** [comment]
Timeout.timeout has historically had some problems:

* http://blog.headius.com/2008/02/rubys-threadraise-threadkill-timeoutrb.html
* http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/

These problems may not be relevant to this PR's use of it, though, I haven't evaluated fully. Given we are mostly just waiting for a condition, Timeout.timeout might be safe. Something to keep in mind.

**Comment by jakelandis** [comment]
@jordansissel - thanks for the warning, i was not aware. 

In this case it is just preventing a potential infinite loop (actually had one in a Jenkins test). In the context of this PR I believe it to be a harmless safety-net.

**Comment by jakelandis** [comment]
@jordansissel - are you comfortable with these changes ?

**Comment by jordansissel** [comment]
I would prefer a something similar to `Stud.try` where something is tried for some amount of time (to avoid TImeout.timeout and also to avoid the weird combination of `Timeout.timeout(...) { sleep(...) while ... }`

That said, this PR is ok to continue

**Pull request closed without merging**
