### PR TITLE
Make sure the namespace metric is send to the plugin correctly and MetricType#to_hash wont return all the values

### PR DESCRIPTION
**Pull request by ph**
Fixes: #5529

### CODE REVIEW

**Comment by ph** [comment]
@suyograo Can you check this PR with your grok changes? I am working on adding test concerning the collection of the metric by the plugin.

**Comment by suyograo** [comment]
@ph works. 

```
"id" : "grok_71384a34-da5b-4d87-974a-32928233ddee",
        "events" : {
          "duration_in_millis" : 3,
          "in" : 1,
          "out" : 1
        },
        "matches" : 1,
        "name" : "grok"
```

**Comment by ph** [comment]
Can you give a LGTM @suyograo I have fixed the build.

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
