### PR TITLE
Update docs to reflect Java 8 as minimum

### LINKED ISSUE #5266: Update required java version for Logstash in documentation
According to https://github.com/elastic/logstash/blob/07887f8cf70079b3de0cd1e59ed6fc07b4a9ea74/logstash-core/lib/logstash/runner.rb#L157-L161 we enforce to use java8, however in the documentation we still see java7 requirement (see https://github.com/elastic/logstash/blob/master/docs/static/getting-started-with-logstash.asciidoc#installing-logstash).

this should be updated, including other possible missed old bits.

### PR DESCRIPTION
**Pull request by suyograo**
Fixes #5266

### CODE REVIEW

**Comment by talevy** [comment]
what about all these checks?

```
qa/scripts/windows/acceptance/logstash_release_acceptance.ps1
9:# - Java 7 or newer

qa/scripts/windows/acceptance/logstash_release_default_plugins.ps1
9:# - Java 7 or newer

qa/scripts/windows/integration/logstash_simple_integration.ps1
11:# - Java 7 or newer

qa/scripts/windows/event_log/logstash_event_log_plugin_integration.ps1
11:# - Java 7 or newer
```

**Comment by talevy** [comment]
and
```
rakelib/artifacts.rake
265:        out.attributes[:deb_suggests] = "java7-runtime-headless"
```

**Comment by suyograo** [comment]
@talevy updated

**Comment by talevy** [comment]
LGTM so long as `java8-runtime-headless` works as intended

**Pull request closed without merging**
