### PR TITLE
Adding an ability of being more verbose when setting up netflow module

### PR DESCRIPTION
**Pull request by zentavr**
A proposed pull request to #8547 feature request

### CODE REVIEW

**Comment by andrewvc** [comment]
jenkins, please test this

**Comment by andrewvc** [comment]
Thanks for the patch @zentavr ! Will merge this once we have passing tests.

**Comment by andrewvc** [comment]
@zentavr this is nearly ready to go, would you mind also adding documentation for these changes here: https://github.com/elastic/logstash/blob/master/docs/static/netflow-module.asciidoc ?

**Comment by zentavr** [comment]
@andrewvc: done

**Comment by andrewvc** [comment]
@zentavr this is awesome, thanks! Will merge

**Comment by andrewvc** [comment]
This has been merged into 6.x, which means it will be released in 6.x (unless we have to pull it for some reason)

**Pull request closed without merging**
