### PR TITLE
[7.x] enable agent to stop pipeline by pipeline_id (#12582)

### PR DESCRIPTION
**Pull request by kaisecheng**
Backports the following commits to 7.x:
 - enable agent to stop pipeline by pipeline_id (#12582)

### CODE REVIEW

**Comment by kaisecheng** [comment]
jenkins test this please

**Comment by kaisecheng** [comment]
jenkins test this please

**Comment by kaisecheng** [comment]
jenkins test this please

**Review by andsel — APPROVED** [review]
LGTM

**Pull request merged**
