### PR TITLE
Fix acceptance tests

### PR DESCRIPTION
**Pull request by suyograo**
#6042 broke acceptance tests, so fixing it

### CODE REVIEW

**Comment by andrewvc** [comment]
Does this just fix the test name, or does the described name actually affect the test?

**Comment by jsvd** [comment]
I guess I'm not familiar with the framework, but this pr only changes test descriptions, is that actually a fix?

**Comment by suyograo** [comment]
@andrewvc the test fix was renaming `shared_examples "logstash uninstall" do |logstash|` to `shared_examples "logstash remove" do |logstash|`. I edited the describes to make it more descriptive, since it was confusing (whether it's dealing with LS or LS plugins bin)

**Comment by suyograo** [comment]
This fixes the test: https://github.com/elastic/logstash/pull/6051/files#diff-6f164f39ab48c19f918b531c9192b01cR6

**Comment by andrewvc** [comment]
OIC. LGTM (assuming tests pass)

**Pull request closed without merging**
