### PR TITLE
ensure order of jvm options from file and env vars is respected

### PR DESCRIPTION
**Pull request by jsvd**
fixes https://github.com/elastic/logstash/issues/15996

### CODE REVIEW

**Review by yaauie — APPROVED** [review]

**Comment by jsvd** [comment]
@logstashmachine backport 8.13

**Comment by jsvd** [comment]
@logstashmachine backport 8.13

**Comment by jsvd** [comment]
@logstashmachine backport 8.12

**Comment by jsvd** [comment]
@logstashmachine backport 8.13

**Pull request merged**
