### PR TITLE
Benchmark: Allow setting a repeat count

### PR DESCRIPTION
**Pull request by original-brownbear**
* Adding kind of an important feature, allowing us to run a larger sample size.
* Also trying to move to properties for settings so we can move to specifying a properties file maybe? (we're really starting to have a million settings, I think that would be nice :))

### CODE REVIEW

**Comment by suyograo** [comment]
> Also trying to move to properties for settings so we can move to specifying a properties file maybe? (we're really starting to have a million settings, I think that would be nice :))

+1 on extracting out the settings; they'll blow up :) How about YAML since users are already used to `logstash.yml`?

**Comment by original-brownbear** [comment]
@suyograo sure I'm cool with `yaml` too, next PR on this will contain a quick port to `yaml` then ;)

**Comment by jakelandis** [comment]
nit: Add the repeat factor to the [output](https://github.com/elastic/logstash/pull/7864/files#diff-7f54d28cf5b50548681b76f3a947b542L182). 
```
Running Test Case: baseline (x2)
```

**Comment by suyograo** [comment]
Good point @jakelandis

**Comment by original-brownbear** [comment]
@jakelandis @suyograo guys thought about that, but then I discarded the idea because we show the overall number of events that we ran anyways (so it's just overloading the "UI" needlessly?)?

**Comment by suyograo** [comment]
@original-brownbear I think we'll soon need the `bin/logstash-benchmark` wrapper as well. I wouldn't burden users with the `java -cp ` CLI :)

**Comment by original-brownbear** [comment]
@suyograo sure that's on the radar, I can try and have that + yaml ready for tomorrow (it's like 30min tasks each or so only anyways)

**Comment by jakelandis** [comment]
@suyograo / @original-brownbear - +1 to externalizing config. 

Might just be a personal preference from an old java developer....but I much prefer java properties file over ```yaml``` for key/value pairing.

**Comment by jakelandis** [comment]
LGTM

**Comment by suyograo** [comment]
@original-brownbear back to the repeat count, I think it does make it easier to comprehend the number of runs vs a multiple of events. I'd vote for outputting the runs as well in addition to the events being multiplied. My 2c.

**Comment by original-brownbear** [comment]
Ok you guys win 2 vs.1 and I guess it makes sense to go with the majority opinion when it comes to UI :) Will change in a bit.

**Comment by original-brownbear** [comment]
@jakelandis my master plan was to simply load YAML into a `Properties` object anyways, so you can just use one if you wish via the JVM flag :P

**Comment by original-brownbear** [comment]
here you go guys:

```sh
Logstash Benchmark
------------------------------------------
Benchmarking Version: 5.5.0
Running Test Case: baseline (x2)
------------------------------------------
Start Time: Tue 8 1 18:21:07 2017 CEST
```

**Comment by suyograo** [comment]
Awesome. 🚢

**Pull request closed without merging**
