### PR TITLE
MINOR: Upgrade to Gradle 4.1

### PR DESCRIPTION
**Pull request by original-brownbear**
Gradle 4.1 is out let's update. Gets us close to JDK9 support at the very least :)

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this please

**Comment by jakelandis** [comment]
Jenkins test this please

**Comment by jakelandis** [comment]
LGTM, assuming CI builds success or un-related.

**Comment by original-brownbear** [comment]
@jakelandis tests are broken until https://github.com/elastic/logstash/pull/8017 is merged :(

**Pull request closed without merging**
