### PR TITLE
remove unnecessary argument

### PR DESCRIPTION
**Pull request by changsijay**
fixed “ERROR: too many arguments” when start log stash daemon

### CODE REVIEW

**Comment by purbon** [comment]
Thanks a lot for this fix @changsijay, to move this forward you will need to sign the https://www.elastic.co/contributor-agreement/ , make sure to use the same email used in this PR, this will simplify internal validations procedures.

Looking forward to get this merged.

**Comment by changsijay** [comment]
Hi @purbon, I've signed the agreement, not sure how to make this PR go on.

**Comment by ph** [comment]
@changsijay Did you sign the CLA with the same email that we have in the patch https://patch-diff.githubusercontent.com/raw/elastic/logstash/pull/5083.patch ?

**Comment by changsijay** [comment]
hi @ph, yes, the email is the same. (Although I signed it after the CLA check failed.)

**Comment by ph** [comment]
@changsijay I can't find your record in our database. 
Did it successfully went through on your side?

**Comment by changsijay** [comment]
Hi @ph, yes, I got email with title "Individual Contributor License Agreement between elasticsearch BV and Jay Chang is Signed and Filed!", with pdf attached.

I can try to sign again if needed. thanks.

**Comment by ph** [comment]
@changsijay we have fixed the CLA issue it was on our end!

Changes LGTM

@purbon can you do another review?

**Comment by purbon** [comment]
related to: #5079

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
In general the change looks good, however I still see a few references to agent that might need to be cleanup, see

```
skywalker% grep -rn agent pkg 
pkg/logstash.default:11:# Arguments to pass to logstash agent
pkg/logstash.upstart.ubuntu:1:# logstash - agent instance
pkg/logstash.upstart.ubuntu:4:description     "logstash agent"
```

most are documentation, but just to be consistent with the interface and not confuse people :+1:, can you do this small change @changsijay, then I'm very good to merge this :smile:, thanks a lot for your time an contribution!

- purbon

**Comment by changsijay** [comment]
not very familiar about the git commit process.
can I ignore this PR and make a new PR to include those?

**Comment by purbon** [comment]
@changsijay just do the change and run `git push` to update the PR :+1:, is the easiest path.

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
