### PR TITLE
Release notes draft for 6.8.14

### PR DESCRIPTION
**Pull request by logstashmachine**
**PREVIEW:** https://logstash_12595.docs-preview.app.elstc.co/guide/en/logstash/6.8/logstash-6-8-14.html

### CODE REVIEW

**Review by karenzone — APPROVED** [review]
Builds cleanly and LGTM

**Comment by karenzone** [comment]
@jsvd  I did some clean up and then approved.  Your comments are always welcomed.

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by karenzone** [comment]
Hey @jsvd. I'm guessing that closing this PR without merging it was an administrative glitch. I'm reopening it so that I can merge it.  Apologies is I guessed wrong.

**Pull request merged**
