### PR TITLE
Allow explicitly-specified Java codecs

### PR DESCRIPTION
**Pull request by danhermann**

### CODE REVIEW

**Comment by yaauie** [comment]
Good catch. LGTM 👍

**Comment by danhermann** [comment]
Thank you, @yaauie!

**Comment by w4** [comment]
i've been writing tests for the last couple of days instead of looking into why my codec wasn't working - thought it was because i was exporting it from a plugin with `"logstash_group" => "filter"` but think this might've been it, ta dan :)

**Comment by w4** [comment]
Apparently not, still getting `undefined method 'new' for class c.a.f.codec.QueryLog:Java::JavaClass` when using the `stdin` input for testing, looks like specifying a Java codec for a Ruby input is still broken - is this by design? Just switched to the `java_stdin` input and that seems to work.

**Comment by danhermann** [comment]
@w4, you're correct that Java codecs currently work only with other Java plugins. It's likely possible to make Java codecs work with Ruby plugins and vice versa, but the buffering structures they use are so different that they would be much less efficient.

Also, please feel free to ask if you encounter anything that doesn't appear to be working as expected with Java plugins. We're about to release the beta version of them and I'm sure there are still a few rough edges to sort out. I've created an AMA topic in the Logstash forums for that purpose:

https://discuss.elastic.co/t/ama-java-plugins-in-logstash/171535/2

**Comment by w4** [comment]
Makes sense, we're trying the move to a full Java pipeline because we've had loads of memory problems with our production fleet, we assume because of the context switches between JRuby and Java so your hard work on this has come at the perfect time. Will let you know how it goes. Thanks again @danhermann

**Pull request closed without merging**
