### PR TITLE
Enable packaging tests in exhaustive pipeline

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes

[rn:skip]

## What does this PR do?

This commit adds the packaging tests (that were refactored in #15696 to not rely on Vagrant) in a new "acceptance" group.

## Why is it important/What is the impact to the user?

Once merged, we will have covered the biggest hurdle in migrating from Jenkins providing coverage for package testing. This PR coupled with https://github.com/elastic/logstash/pull/15748 concludes the migration.

## How to test this PR locally

Example triggered runs:

- https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/77 (all groups)
- https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/75 (only acceptance/packaging)
- https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/73 (only acceptance/packaging)

## Related issues

- Depends https://github.com/elastic/logstash/pull/15696
- Relates https://github.com/elastic/ingest-dev/issues/1722

### CODE REVIEW

**Review by roaksoax — APPROVED** [review]
lgtm!

**Comment by dliappis** [comment]
@logstashmachine backport 8.12

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Comment by dliappis** [comment]
A manual backport for `7.17` will be created due to (a few minor) conflicts.

**Pull request merged**
