### PR TITLE
api: avoid 5xx when stats/events not yet populated

### LINKED ISSUE #13258: Logstash monitoring endpoint should handle exceptions if no pipeline is currently running
**Logstash information**:

Please include the following information:

1. **Logstash version (e.g. `bin/logstash --version`)** 7.13+ (but previous versions might be affected, too)
2. **Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)** Not relevant
3. **How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)** Not relevant

**Description of the problem including expected versus actual behavior**:

When using Pipeline central management and no pipeline is found, when we access the Monitoring Endpoint it triggers the exception, returning an invalid response.

Rest API response has error code 500 with the exception:
```
{"status":500,"request_method":"GET","path_info":"/_node/stats","query_string":"","http_version":"HTTP/1.1","http_accept":"*/*","error":"Unexpected Internal Error","class":"LogStash::Instrument::MetricStore::MetricNotFound","message":"For path: events. Map keys: [:reloads]","backtrace":["/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'","org/jruby/ext/thread/Mutex.java:164:in `synchronize'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'","org/jruby/RubyArray.java:1809:in `each'","org/jruby/RubyEnumerable.java:1126:in `inject'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'","org/jruby/RubyMethod.java:115:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'","org/jruby/RubyKernel.java:1189:in `catch'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:718:in `handle_request'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:472:in `process_client'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:328:in `block in run'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"]}%
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Setup Logstash with `xpack.management.enabled: true` and pipeline ID pointing to non-existing pipelines, e.g. `xpack.management.pipeline.id: ["some*"]`
 2. Start Logstash
 3. Run `curl http://localhost:9600/_node/stats

**Provide logs (if relevant)**:

```
[2021-09-30T11:28:36,233][DEBUG][logstash.agent           ] 2021-09-30 11:28:36 - LogStash::Instrument::MetricStore::MetricNotFound - For path: events. Map keys: [:reloads]:
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'
	org/jruby/ext/thread/Mutex.java:164:in `synchronize'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'
	org/jruby/RubyArray.java:1809:in `each'
	org/jruby/RubyEnumerable.java:1126:in `inject'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'
	org/jruby/RubyMethod.java:115:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	org/jruby/RubyKernel.java:1189:in `catch'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	org/jruby/RubyKernel.java:1189:in `catch'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	org/jruby/RubyKernel.java:1189:in `catch'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:718:in `handle_request'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:472:in `process_client'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:328:in `block in run'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
[2021-09-30T11:28:36,236][ERROR][logstash.agent           ] Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats", :query_string=>"", :http_version=>"HTTP/1.1", :http_accept=>"*/*", :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: events. Map keys: [:reloads]", :backtrace=>["/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'", "org/jruby/ext/thread/Mutex.java:164:in `synchronize'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'", "org/jruby/RubyArray.java:1809:in `each'", "org/jruby/RubyEnumerable.java:1126:in `inject'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'", "org/jruby/RubyMethod.java:115:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'", "org/jruby/RubyKernel.java:1189:in `catch'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'", "org/jruby/RubyKernel.java:1189:in `catch'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'", "org/jruby/RubyKernel.java:1189:in `catch'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:718:in `handle_request'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:472:in `process_client'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:328:in `block in run'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"]}
[2021-09-30T11:28:36,237][ERROR][logstash.agent           ] API HTTP Request {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats", :query_string=>"", :http_version=>"HTTP/1.1", :http_accept=>"*/*"}
```

### PR DESCRIPTION
**Pull request by yaauie**
## Release notes

 - Fixes an issue where querying the stats API before any pipelines had been started could result in an HTTP 500 response.

## What does this PR do?

Prevents an HTTP 500 response from being emitted when the event stats had not yet been populated, as is common during start-up, or when Logstash is configured to manage pipelines through Kibana Central Management and no pipelines have been defined.

## Why is it important/What is the impact to the user?

Provide useful stats API output even when no pipelines are yet running.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~

## How to test this PR locally

1. Start up Logstash with Central Management configured, without any (matching) pipelines, and without internal monitoring enabled.
2. Query the `/_node/stats` API endpoint
3. Observe a 2XX-level response and an empty map at top-level `events` key (a populated map indicates that the precondition that previously led to a 5XX was not met).

## Related issues

Fixes #13258

### CODE REVIEW

**Review by andsel — CHANGES_REQUESTED** [review]
I launched Logstash with the following content in `logstash.yml`:
```
xpack.management.enabled: true
xpack.management.pipeline.id: ["test*", "jdbc_input"]
xpack.management.elasticsearch.username: elastic
xpack.management.elasticsearch.password: changeme
xpack.management.elasticsearch.hosts: ["http://localhost:9200"]
```

Issued an HTTP get with:
```
curl http://localhost:9600/_node/stats
```

but received the response:
```
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Content-Length: 6710
< 
{"status":500,"request_method":"GET","path_info":"/_node/stats","query_string":"","http_version":"HTTP/1.1","http_accept":"*/*","error":"Unexpected Internal Error","class":"LogStash::Instrument::MetricStore::MetricNotFound","message":"For path: pipelines. Map keys: [:reloads]","backtrace":["/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'","org/jruby/RubyArray.java:1821:in `each'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'","org/jruby/RubyArray.java:1821:in `each'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'","org/jruby/ext/thread/Mutex.java:164:in `synchronize'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/api/service.rb:41:in `get_shallow'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/api/commands/stats.rb:31:in `queue'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/api/modules/node_stats.rb:52:in `queue'","/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/api/modules/node_stats.rb:41:in `block in GET /?:filter?'".....
```

and same stacktrace appears also on LS console

**Comment by andsel** [comment]
Hi @yaauie I've added the commit https://github.com/elastic/logstash/pull/13424/commits/42b4f214573281b9579df2cecc022ae0bc867e0b to fix the changes I've requested in my review. LMKWDYT

**Comment by andsel** [comment]
Jenkins test this please

**Comment by yaauie** [comment]
@andsel good catch on the one I missed. I've dismissed your "changes requested" review since this incorporates your suggested changes. Can you reapprove?

**Review by andsel — APPROVED** [review]
LGTM!

**Pull request merged**
