### PR TITLE
1.4 - fixes tcp input memory leak

### PR DESCRIPTION
**Pull request by danielsand**
Hey Folks,

quick and dirty imported this commit -> https://github.com/elastic/logstash/commit/7b6ab95124cb1b4107e15ae78aeb2e4e4bb4c6d9

to the 1.4 branch - fixed this ->
https://github.com/elastic/logstash/issues/1509

please check and bump release it. This troubled us on a big 6 cluster installation big time. 
Memory grows fast and kills the servers - without this.

### CODE REVIEW

**Comment by purbon** [comment]
@danielsand could you please update the title with a more descriptive title?

**Comment by danielsand** [comment]
@purbon done

**Comment by suyograo** [comment]
@danielsand can you please sign the CLA? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by jordansissel** [comment]
Specs don't pass:

```
% USE_JRUBY=1 bin/logstash rspec spec/inputs/tcp.rb
Using Accessor#strict_set for specs
LoadError: no such file to load -- logstash/json
          require at org/jruby/RubyKernel.java:1071
          require at /home/jls/projects/logstash/vendor/jar/jruby-complete-1.7.17.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
          require at /home/jls/projects/logstash/vendor/jar/jruby-complete-1.7.17.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
          require at /home/jls/projects/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/polyglot.rb:65
           (root) at /home/jls/projects/logstash/spec/inputs/tcp.rb:5

```

**Comment by jordansissel** [comment]
lib/logstash/json isn't available in 1.4 (e03b67dc7da0c3d654caef9ca1a144d1ab99e580 was never backported). I don't think we should backport LogStash::JSON, but we'll need to fix the specs to pass.

**Comment by jordansissel** [comment]
We're doing a release of 1.4.x today, so this will probably have to wait until the next release of 1.4.x (assuming there is one).

**Comment by jordansissel** [comment]
Delaying 1.4.x release until Weds so we can hopefully fix these tests.

I'll have a go at fixing them today.

**Comment by danielsand** [comment]
@suyograo: sorry will not do - its from a commit of the 1.5 branch. 
I just copied 2 files from the commit because this is fixing a BAD issues in logstash 1.4 tcp input memory leak.
so in total - its not my code. im just the copy monkey :)

**Comment by danielsand** [comment]
@jordansissel: would be awesome if this can be inked into the new release. its really a big show stopper.

**Comment by jordansissel** [comment]
@danielsand I'm going to open a new PR with the cherry-pick and fix.

**Comment by jordansissel** [comment]
@danielsand Have you confirmed that this fixes your problem? Also, what is the cause that you cannot upgrade to 1.5.x?

**Comment by jordansissel** [comment]
https://github.com/elastic/logstash/pull/3696 cherry picks w/ minor patch the original change from #1522

**Comment by jordansissel** [comment]
Closing in favor of #3696

**Comment by danielsand** [comment]
@jordansissel just as feedback. 
It made the memory consumption better - but still there seems to be a hole:
bildschirmfoto 2015-08-11 um 10 43 27
i applied manually the input patch last week and still sometimes this happens. Not sure if it's the same cause though.

cheers

**Pull request closed without merging**
