### PR TITLE
check versions.yml for correct project version

### PR DESCRIPTION
**Pull request by talevy**
- and fix a test

### CODE REVIEW

**Comment by jsvd** [comment]
I'm pretty sure the travis failure `no such file to load -- org/apache/logging/log4j/log4j-1.2-api/2.6.2/log4j-1.2-api-2.6.2 (LoadError)` has nothing to do with this PR
LGTM

**Comment by talevy** [comment]
I will double check

**Comment by talevy** [comment]
@jsvd lol. it is a naming conflict. my `def file` mucked with global variable names. specifically Gradle/groovy's `file` function

**Comment by talevy** [comment]
and

```
> /home/travis/build/elastic/logstash/logstash-core/build/../../versions.yml (No such file or directory)
```

It is there... so this is unexpected

**Comment by talevy** [comment]
this ran locally for me

**Comment by talevy** [comment]
green now!

**Comment by suyograo** [comment]
LGTM

**Comment by jsvd** [comment]
LGTM

**Comment by jsvd** [comment]
@talevy merging this directly to 5.0 5.x and master fails with Jarvis, can you do it manually?

**Comment by colinsurprenant** [comment]
LGTM - any reason this is not merged?

**Comment by talevy** [comment]
@colinsurprenant didn't get to it since other things came up. I will move this forward today for 5.x and master

**Comment by colinsurprenant** [comment]
nice! thanks!

**Pull request merged**
