### PR TITLE
Logging when queue.max_bytes is reached #7491

### LINKED ISSUE #7491: Logging when queue.max_bytes is reached
5.4.1

It will be helpful for admins if we can write a logging entry (that shows up at the default LS logging level, perhaps a WARN), when queue.max_bytes is reached.

### PR DESCRIPTION
**Pull request by liketic**
Resolves #7491 .

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this please

**Comment by original-brownbear** [comment]
@colinsurprenant maybe take a look here, I'm not so sure doing this (logging as suggested in #7491 ) is wise in the first place?
Won't we be spamming the log endlessly here if we have producers outpacing consumers (since in that case, the Queue will oscillate between full and almost full constantly)?

**Comment by original-brownbear** [comment]
Path itself looks fine to me though :)

**Comment by jordansissel** [comment]
I don't think logging is appropriate since a scenario with a nearly-always-full-queue will constantly print this log.

If an operator wants to monitor queue size, we have a monitoring api (http on port 9600) for this purpose.

**Comment by liketic** [comment]
I'm OK to close this. @ppf2 Any thoughts? 😅

**Comment by ppf2** [comment]
As long as this information is recorded somewhere, it should be fine.  If not logging, then the API (outstanding issue: https://github.com/elastic/logstash/issues/6508) :) thx

**Comment by colinsurprenant** [comment]
I believe we can close this? We seems to agree that this should be better handled in though the API.

**Pull request closed without merging**
