### PR TITLE
Explicitely require LogStash::Bundler.setup! make the plugin install process to require internet access

### PR DESCRIPTION
**Pull request by ph**
Fixes: #6386

### CODE REVIEW

**Comment by ph** [comment]
This require an offline test in rats.

**Comment by suyograo** [comment]
LGTM

**Comment by jsvd** [comment]
@ph is there no consequence of removing this? I see it was added with the doc gen v2 tooling https://github.com/ph/logstash/commit/bf2d670d2a3bd7708513bfa7bb55a02748a22876

**Comment by ph** [comment]
@jsvd I will double check that, it should be needed in the logstash-docgen, when I've rebased v2 with an older branch.

**Comment by jsvd** [comment]
@ph this does not seem to fix the issue:
```
joaoduarte@Joaos-MBP-5 /tmp % rm -rf logstash-5.1.1
joaoduarte@Joaos-MBP-5 /tmp % tar -zxf logstash-5.1.1.tar.gz
joaoduarte@Joaos-MBP-5 /tmp % cd logstash-5.1.1
joaoduarte@Joaos-MBP-5 /tmp/logstash-5.1.1 % wget https://patch-diff.githubusercontent.com/raw/elastic/logstash/pull/6388.patch
--2016-12-12 16:42:23--  https://patch-diff.githubusercontent.com/raw/elastic/logstash/pull/6388.patch
Resolving patch-diff.githubusercontent.com... 192.30.253.112, 192.30.253.113
Connecting to patch-diff.githubusercontent.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from patch-diff.githubusercontent.com attempted to set domain to github.com
Length: unspecified [text/plain]
Saving to: '6388.patch'

6388.patch                                 [ <=>                                                                      ]     791  --.-KB/s    in 0s      

2016-12-12 16:42:24 (18.9 MB/s) - '6388.patch' saved [791]

joaoduarte@Joaos-MBP-5 /tmp/logstash-5.1.1 % patch -p1 < 6388.patch
patching file lib/pluginmanager/main.rb
joaoduarte@Joaos-MBP-5 /tmp/logstash-5.1.1 % rm -rf ~/.m2
joaoduarte@Joaos-MBP-5 /tmp/logstash-5.1.1 % bin/logstash-plugin install ../logstash-filter-elapsed-4.0.0.gem
Validating ../logstash-filter-elapsed-4.0.0.gem
Installing logstash-filter-elapsed
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core-event-java (5.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.1.1'` succeeds before bundling.
Error Bundler::InstallError, retrying 2/10
An error occurred while installing logstash-core-event-java (5.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.1.1'` succeeds before bundling.
Error Bundler::InstallError, retrying 3/10
An error occurred while installing logstash-core-event-java (5.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core-event-java -v '5.1.1'` succeeds before bundling.
```

**Comment by ph** [comment]
@jsvd OK, I will take another look, I didn't not include the log from my test will do it and update this thread.

**Comment by colinsurprenant** [comment]
I am not sure how the plugin manager can work if Bundler is not setup?

**Comment by ph** [comment]
@colinsurprenant it was the case before ph@bf2d670, bundler.setup! is only needed when you actually need to remove plugins  to make sure the plugins definition are configured before you try to remove the,

When you install, bundler will get configured just in time in the CLI using the params from the command line.

**Comment by ph** [comment]
As a note, Bundler.setup does a lot more than just reading the definition, it replaces core rubygems classes with bundler's one which is really strict about what is available in the current environmet.

**Comment by ph** [comment]
Also, I think the way we configure the GEM_HOME and how we interact with bundler could be simplified or refactored I think we can do it with #4219, but we should do it for 6.0.

**Comment by suyograo** [comment]
@ph this fixed the x-pack install issue. Can we merge this please?

**Pull request closed without merging**
