### PR TITLE
MODULES: fixes for bad modules and client logging

### PR DESCRIPTION
**Pull request by guyboertje**

### CODE REVIEW

**Comment by ph** [comment]
By looking at the error on travis, I think you need to rebase on top of 5.x?

**Comment by guyboertje** [comment]
Just done that :-)

**Comment by ph** [comment]
@guyboertje I believe the code is good, lets Travis test it and I will take another look. This may sound a bit picky but could you change the commit message? If we have to look through the git commit history It will be hard to understand what this commit is about.

**Comment by guyboertje** [comment]
After Suyog told me off for merging with a not meaningful commit message I will henceforth always adjust the squash commit message.

**Comment by ph** [comment]
code look good, test look good, doing a real world simple test.

**Comment by ph** [comment]
I have tried to run it with the CEF module and it failed?

```
 ⚙  ph@sashimi  ~/es/logstash   pr/7378  bin/logstash --modules cef
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /Users/ph/es/logstash/logs which is now configured via log4j2.properties
[2017-06-08T11:48:03,299][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/Users/ph/es/logstash/data/queue"}
[2017-06-08T11:48:03,304][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/Users/ph/es/logstash/data/dead_letter_queue"}
[2017-06-08T11:48:03,823][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::ConfigLoadingError: Failed to parse the module configuration: [[401] ]>, :backtrace=>["/Users/ph/es/logstash/logstash-core/lib/logstash/config/modules_common.rb:61:in `pipeline_configs'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/ph/es/logstash/logstash-core/lib/logstash/config/modules_common.rb:36:in `pipeline_configs'", "/Users/ph/es/logstash/logstash-core/lib/logstash/runner.rb:277:in `execute'", "/Users/ph/es/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/Users/ph/es/logstash/logstash-core/lib/logstash/runner.rb:209:in `run'", "/Users/ph/es/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/Users/ph/es/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

**Comment by ph** [comment]
Forget my previous comment, It work. I was targeting a elasticsearch instance with x-pack installed since the cef pipeline by default doesn't use any credentials it was failling.

**Comment by ph** [comment]
Can we create an issue or another PR to improve the error message?

` Failed to parse the module configuration: [[401] `

its not obvious that I had a permission denied.

**Comment by guyboertje** [comment]
This was the passing build before manual squash

**Pull request merged**
