### PR TITLE
Only use rspec for tests5x

### PR DESCRIPTION
**Pull request by andrewvc**
5.x version of #7140

### CODE REVIEW

**Comment by suyograo** [comment]
@andrewvc this needs a rebase with 5.x. Can you directly cherry-pick and push upstream since this is a backport? Don't need reviews here

**Comment by andrewvc** [comment]
Done!

**Comment by suyograo** [comment]
@andrewvc there's still some issues with this, I think a clean cherry-pick or copy-paste would be better.

**Comment by andrewvc** [comment]
@suyograo ohhhh, I see. This PR was an accident. I already merged into 5x hours ago . It's currently the head commit here: https://github.com/elastic/logstash/tree/5.x

Closing this issue.

**Pull request closed without merging**
