### PR TITLE
Update pluginbody.asciidoc

### PR DESCRIPTION
**Pull request by juliusl**
Updated the link for asciidoc formatting

### CODE REVIEW

**Comment by suyograo** [comment]
can you please perform step 2 of https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by juliusl** [comment]
I tried but the link appears to be broken.
http://www.elasticsearch.org/contributor-agreement/
http://www.elastic.co/contributor-agreement/

**Comment by untergeek** [comment]
Hmmm.  It pulls up for me (the 2nd link is the correct one) when I try right now.  It should pull up an embedded Adobe EchoSign document when you click through to the next page.

**Comment by juliusl** [comment]
OOO it's because I was using http:// in the 2nd link and not https://. Doh.

**Comment by juliusl** [comment]
Okay I have signed the CLA.

**Comment by suyograo** [comment]
@juliusl did you sign the CLA with the same email you used in your commit? 
I can see the email here: https://github.com/elastic/logstash/pull/3415.patch

If so, can you `git push -f <branch_name>`

this will force push your commit

**Comment by juliusl** [comment]
Yup used the same email. Okay I'll try that.

**Comment by juliusl** [comment]
Didn't work with a "make sure you have correct access rights". I'm guessing it'll just take some time for the CLA to propagate?

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
