### PR TITLE
avoid using duplicate logstash.yml for rpm/deb

### PR DESCRIPTION
**Pull request by jsvd**
Currently https://github.com/elastic/logstash/blob/master/config/logstash.yml and https://github.com/elastic/logstash/blob/master/pkg/logstash.yml are the same, so until they start to diverge I'd suggest using the same file.

### CODE REVIEW

**Comment by untergeek** [comment]
Hmmm.  Make sure this gets tested.  I had issues when I used the approach you went with, which is why I ended up "duplicating" it. Perhaps I just did something wrong.

**Comment by untergeek** [comment]
And by tested, I mean by the package testing infrastructure.

**Comment by jsvd** [comment]
Tested both RPM and DEB packages..all is fine. Reviews welcome.

**Comment by untergeek** [comment]
LGTM™

Thanks for chasing down the weirdness.

**Pull request closed without merging**
