### PR TITLE
Add memorize plugin

### PR DESCRIPTION
**Pull request by alcanzar**
This is a plugin that lets you use data from previous events on future events.

### CODE REVIEW

**Comment by alcanzar** [comment]
I signed the CLA on October 14th, 2014 -- transaction id XFB3R9IX53C4TXY

**Comment by purbon** [comment]
Good morning @alcanzar, I notice this contribution has been here for too long without much of feedback, and I'm sorry for this, so easy to get drawn in lots of stuff.

To move this forward I have a couple of questions, todos, let me know how do you feel about it.

First of all there is the CLA issue, you signed the CLA with your personal email (this is an important way of identity we check nowadays), but your commit comes with your work email. Here we've two way to make this happen, or you change your identity in your commit, or either you sign the CLA with your work email. I know this might seem a hassle, but is how it works by now.

On the other side, are you aware from 1.5 on plugins life in their own house in the logstash-plugins organization or in your own repo. Next move in here would be to follow what the documentation says about adding a new filter, https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html

Makes sense to you?

**Comment by alcanzar** [comment]
Can you point out where my "work" email shows up?  Because I can't seem to find it.  I also no longer work for that company, so signing it as that address isn't possible now.

Thanks,
Adam

**Comment by purbon** [comment]
Hi,
 if you take a look at https://patch-diff.githubusercontent.com/raw/elastic/logstash/pull/1999.patch, you will see in the second line. As this should go into somewhere else I suggest you redo the PR setting the author data as your private ones.

Here https://help.github.com/articles/changing-author-info/ there is more intel on how to change author info.

/cheers

**Comment by alcanzar** [comment]
closing this pull request because I messed it up.  I will repackage as a 1.5 plugin

**Pull request closed without merging**
