### PR TITLE
move ackedqueue specific classes into ackedqueue package

### PR DESCRIPTION
**Pull request by colinsurprenant**
this is a namespace cleanup to move non-common, ackedqueue specific classes into the `org.logstash.ackedqueue` package.

### CODE REVIEW

**Comment by jordansissel** [comment]
I haven't tested, but I like the namespace change. LGTM once travis passes.

**Comment by colinsurprenant** [comment]
The failures are agent and monitoring related - I believe these are known issues being worked on.

**Comment by colinsurprenant** [comment]
since the build errors are not related I will go ahead and merge.

**Comment by colinsurprenant** [comment]
rebased and merged in master, 5.x and 5.4.

**Pull request merged**
