### PR TITLE
Backport for 5.x: Enhance ingest convert to add input/output (#7456)

### PR DESCRIPTION
**Pull request by original-brownbear**
* Add input/output to converter

* update CLI help

* remove newline and use join on array

### CODE REVIEW

**Comment by original-brownbear** [comment]
@jakelandis this fixes https://github.com/elastic/logstash/issues/7683, someone missed backporting their patch to 5.x here :)

**Comment by jakelandis** [comment]
LGTM

**Comment by original-brownbear** [comment]
@jakelandis thanks just waiting for Travis to pass these tests then :)

**Comment by original-brownbear** [comment]
merged because ingest converter tests passed

**Pull request closed without merging**
