### PR TITLE
Update arcsight architecture images

### PR DESCRIPTION
**Pull request by dedemorton**
closes https://github.com/elastic/logstash/issues/8348

### CODE REVIEW

**Comment by dedemorton** [comment]
@acchen97 When I exported the svg images to png, I get a transparent image. Maybe this is intentional? If not, can you get a png version of the images?

**Comment by dedemorton** [comment]
@acchen97 You can ignore my request for the PNG. The SVG is not very big and probably better, so I'll use that.

**Comment by dedemorton** [comment]
@acchen97 I've added the latest images from here: https://github.com/elastic/Design/issues/609#issuecomment-333555348

**Comment by acchen97** [comment]
@dedemorton thanks, I left a comment in the other issue. The smart connector image doesn't look correct.

**Comment by dedemorton** [comment]
Ah...good catch!

**Comment by acchen97** [comment]
@dedemorton we're good to go on the images. Please excuse the delay. :)

[Event broker diagram](https://elasticsearch.app.box.com/s/psc07klbgl0ekcko4bim3z5u6rrj0442)
[Smart connectors diagram](https://elasticsearch.app.box.com/s/s5pes1xg91szq3ovaaacpovvwrd9nf55)

**Comment by acchen97** [comment]
Thanks @dedemorton you rock! See you soon in Berlin. :)

**Pull request closed without merging**
