### PR TITLE
Ruby event API fix to support non-ASCII keys

### PR DESCRIPTION
**Pull request by maxirmx**
Fix for https://github.com/elastic/logstash/issues/9789

### CODE REVIEW

**Comment by maxirmx** [comment]
Ups ...  
One more method to fix:  event.include?

**Comment by yaauie** [comment]
@maxirmx General approach makes sense 👍

Feel free to ping me when you've got `Event#include?(String)` fixed and I'll push it through Jenkins and get it merged/backported to all the right places.

**Comment by maxirmx** [comment]
@yaauie   It is ready

**Comment by jsvd** [comment]
+1 on backporting https://github.com/elastic/logstash/pull/9764 to 6.3 + 6.2

**Comment by danhermann** [comment]
This has been fixed in #9825 and #9821.

**Pull request closed without merging**
