### PR TITLE
Pin minitar

### PR DESCRIPTION
**Pull request by jordansissel**
. Works around https://github.com/halostatue/minitar/issues/23

### CODE REVIEW

**Comment by halostatue** [comment]
This particular change should *not* be necessary; `minitar` does not require `minitar-cli`; only `archive-tar-minitar` does. However, this should be changed to `~> 0.5` because when I release 1.0 (eventually), there will be breaking changes (I plan on dropping everything below Ruby 2.0).

**Comment by talevy** [comment]
@halostatue 

it is not the dependency on `minitar-cli` that is causing an issue here at the moment. it is this: https://github.com/elastic/logstash/pull/6657#issue-206033272

**Comment by halostatue** [comment]
@talevy Can I get an issue opened on halostatue/minitar for this? If possible, a minimal repro would be useful, because none of my tests (and I do have tests *mostly* around compressed tar streams) have shown an error like this.

**Comment by talevy** [comment]
@halostatue do you test with JRuby? maybe it is specific to that platform?

**Comment by halostatue** [comment]
@talevy My travis matrix is pretty extensive, including JRuby 9k and jruby-19mode, neither of which is allowed to fail in the current mode. I’d like to get this fixed, but I’m at a loss. I’ve also added a comment to #6657. A `--trace` output for this would be more useful than what I’m seeing.

**Comment by halostatue** [comment]
Copying from #6657: Is there a recommended Vagrantfile for testing this so I can try to debug?

I won’t be able to look at it until tomorrow, but this should not be happening (as far as I know, *that* code didn’t change beyond formatting).

**Comment by jordansissel** [comment]
@halostatue i'll try to come up with something and will follow up on  https://github.com/halostatue/minitar/issues/24 with any additional details.

**Comment by ph** [comment]
I've did some testing with this branch and I can build the artifact without any problem.
```
mkdir -p build/bootstrap
[bootstrap] Fetching and installing gem: minitar (0.5.4)
Fetching: minitar-0.5.4.gem (100%)
Successfully installed minitar-0.5.4
Installing minitar 0.5.4 because the build process needs it.
[bootstrap] Fetching and installing gem: minitar (0.5.4)
Fetching: minitar-0.5.4.gem (100%)
Successfully installed minitar-0.5.4
Installing bundler ~> 1.9.4 because the build process needs it.
```

**Comment by jordansissel** [comment]
Merging for now and I'll update the pin to 0.6.1 when time permits maybe later this week.

**Comment by halostatue** [comment]
I recommend considering upgrading to 0.6 now that things are fixed, as I had to fix a CVE in tarball extraction.

**Pull request closed without merging**
