### PR TITLE
Add Info About Commands Used / Test Config Files

### PR DESCRIPTION
**Pull request by kkirsche**
Provide more information about what each flag for each command we are running to help a new user to the services understand them better.

Also include how to test a configuration file.

### CODE REVIEW

**Comment by kkirsche** [comment]
Wanted to follow up about this.

**Comment by kkirsche** [comment]
Wanted to follow up on this @jordansissel as I haven't heard anything about this from the project yet..

**Comment by jordansissel** [comment]
@kkirsche Very sorry about the delay in reviewing.

**Comment by jordansissel** [comment]
Content LGTM. Thank you for helping improve Logstash!

**Comment by kkirsche** [comment]
No worries. Thanks!!

**Pull request closed without merging**
