### PR TITLE
Bump Gemfile.jruby-2.3.lock.release to 6.6.1

### PR DESCRIPTION
**Pull request by guyboertje**
I'm not sure why some plugins jumped a major version.

logstash-codec-cef (6.0.0-java) from 5.0.6
logstash-filter-geoip (6.0.0-java) from 5.0.3
logstash-input-kafka (9.0.0) from 8.3.1
logstash-input-tcp (6.0.0-java) from 5.2.0
logstash-output-kafka (8.0.0) from 7.3.1
logstash-output-redis (5.0.0) from 4.0.4
logstash-output-sqs (6.0.0) from 5.1.2
logstash-output-tcp (6.0.0) from 5.0.4

But the redis input went backwards

logstash-input-redis (3.1.4) from 3.4.0

### CODE REVIEW

**Comment by jsvd** [comment]
oh..I see what's wrong...the script isn't correctly aborting if it can't find the reference lock file, so it compares against nothing, so there's no limits..
It can't find the reference lock file because we haven't tagged v6.6.0 yet

**Comment by guyboertje** [comment]
I need to push a tag?

**Comment by jsvd** [comment]
@guyboertje yeah please do

**Comment by guyboertje** [comment]
I'll close this and try again after the tag

**Pull request closed without merging**
