### PR TITLE
Allow opt. space between device-id and colon.

### PR DESCRIPTION
**Pull request by roderickm**
fix elasticsearch/logstash#2101

### CODE REVIEW

**Comment by roderickm** [comment]
CLA signed.

**Comment by roderickm** [comment]
The CLA Check is failing despite my signing it over a week ago.

This issue report and contribution were done on my employers' time. After my employer submitted the CLA as a company wanting employees to contribute, I signed the CLA last week using my work address.  However, my personal address the primary one on my github account. Perhaps the cla_check verifies only the primary github email address?
screen shot 2015-01-15 at 9 50 17 am

**Comment by untergeek** [comment]
Yes, the check depends on your github account email.


—Aaron

**Comment by roderickm** [comment]
Thanks, @untergeek. To be clear, the work email address with which I signed the CLA is a secondary address on my github account.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins (and grok patterns) to individual repositories. Can you move this pull request to https://github.com/logstash-plugins/logstash-patterns-core?

This sequence of steps _may_ help you do this migration:

1. Fork this repository
2. Clone your fork

  ```shell
  git clone https://github.com/roderickm/logstash.git
  ```

3. Create a branch:

  ```shell
  git checkout -b my-branch-name
  ```

4. Apply the patches from this PR into your branch:

  ```shell
  curl -s https://github.com/elastic/logstash/pull/2102.patch | git am
  ```

  This should take your commits from this PR and commit them to your new local branch.

5. Push!

  ```shell
  git push origin my-branch-name
  ```

6. Open a new PR against https://github.com/logstash-plugins/logstash-patterns-core
7. Sign the CLA

  Our CLA check indicates that some commit authors have not signed the CLA or are not members of Elasticsearch. See our [contributor agreement](http://www.elasticsearch.org/contributor-agreement/) for more details. :)

**Pull request closed without merging**
