### PR TITLE
Release 5.6.10 - 2nd PR Create Gemfile.jruby-1.9.lock.release

### PR DESCRIPTION
**Pull request by guyboertje**

### CODE REVIEW

**Comment by guyboertje** [comment]
Do you mean changes to our plugin minors or all gems?

**Comment by jsvd** [comment]
I'd say both, we're not better or worse at messing up in minor releases as third party libraries, but I'm open to suggestions otherwise.

**Comment by webmat** [comment]
Part of our plan here was for me to review what these version bumps brought with them by poring over changelogs. I'll write the summary here, to feed this discussion.

**Comment by webmat** [comment]
### Plugins

* ❓ logstash-codec-netflow 3.11.4 to 3.14.0: seems to add support for more of the spec, plus a few bug fixes. Not familiar enough to know if this is safe or not: [Commits · logstash-plugins/logstash-codec-netflow · GitHub](https://github.com/logstash-plugins/logstash-codec-netflow/commits/v3.14.0)
* ✅ logstash-filter-dns 3.0.9 to 3.0.10 is tweaks to the logging level, plus the excellent performance improvement allowing the DNS filter to make concurrent queries: [Pull Request #42](https://github.com/logstash-plugins/logstash-filter-dns/pull/42). I would include
* ✅ logstash-filter-kv 4.1.1 to 4.1.2: missing doc & fix around unambiguous separators. I would include.
* ✅ logstash-filter-mutate 3.3.1 to 3.3.2: doc fixes & better handling of non-strings. I would include.
* ❓ logstash-input-file 4.0.5 to 4.1.2: 4.1.0 seems like a lot of changes, not sure I would include. However 4.1.1 and 4.1.2 were important fixes. Should we backport those to 4.0,x or let the bump to 4.1.x happen here?
* ❌ logstash-input-http 3.0.10 to 3.2.0-java: Rewrite from Ruby/Rack to Java/Netty. I would definitely **not** include.
* ✅ logstash-input-s3 3.3.2 to 3.3.5: a few straightforward bug fixes, fix to license name in gemspec. I would include.
* ✅ logstash-input-udp 3.3.1 to 3.3.3: missing require and João's memory leak fix. I would include.
* ❓ logstash-output-elasticsearch 7.4.2-java to 7.4.3-java: quite a few changes, not familiar with the 7.x branch. I'm deferring to João on this one.
* ✅ logstash-output-s3 4.1.1 to 4.1.2: doc fixes and bug fixes wrt symbol keys in hashes. I would include.

### Non-plugin Gems

* ✅ AWS-sdk 2.11.33 to 2.11.54: looks purely like generated code: [Commits · aws/aws-sdk-ruby · GitHub](https://github.com/aws/aws-sdk-ruby/commits/v2.11.54)
* ✅ domain_name update is a one commit change, an update to a database file: [Commits · knu/ruby-domain_name · GitHub](https://github.com/knu/ruby-domain_name/commits/v0.5.20180417)
* ❓ dotenv: not familiar enough with the gem. Quite a few commits, and 2.4.0 reverts an addition from 2.3.0: [dotenv/Changelog.md at v2.4.0 · bkeepers/dotenv · GitHub](https://github.com/bkeepers/dotenv/blob/v2.4.0/Changelog.md) -- ** Were may want to freeze this one at 2.2.2 for now? **
* ❓ elasticsearch-ruby: I'll defer to gem contributor João on this one ;-) [elasticsearch-ruby/CHANGELOG.md at master · elastic/elasticsearch-ruby · GitHub](https://github.com/elastic/elasticsearch-ruby/blob/master/CHANGELOG.md)
* ❓ filewatch removal from change to logstash-input-file: defer to Guy.
* ✅ jls-grok: 0.11.4 to 0.11.5 is the addition of the license. A must. [Commits · jordansissel/ruby-grok · GitHub](https://github.com/jordansissel/ruby-grok/commits/master)
* ❌ sequel: 42 commits since 3.7.1. Not a dependency of any plugin. I would stick to previous version.
* ✅ tzinfo-data: I would include. This version is 1 small tweak & one data update: [Commits · tzinfo/tzinfo-data · GitHub](https://github.com/tzinfo/tzinfo-data/commits/v1.2018.5)

**Comment by guyboertje** [comment]
Fine work @webmat.

Sequel is (should be) a dep of the `logstash-input-jdbc` plugin. We use a very small portion of the library. Most updates have been flawless in the past - we are more interested in new adapters being added that increase our coverage of DB technologies. Sadly, the list has shrunk in the past, so we should make sure that we are not "cutting off" users should this be the case.

The netflow codec is maintained by Jorrit Folmer, a Community Maintainer, who is usually rather good at testing his changes. He is way more expert than any of us at Netflow. This change is the only one likely to affect us `Add ConnectionPool#connection_expiration_random_delay to connection_expiration extension, to avoid thundering herd if preallocating connections (hex2a, jeremyevans) (#1503)`  Vote include.

Of course, the file input changes are supposed to be BWC. I'll have to be Switzerland on this one 😃 .

**Comment by jsvd** [comment]
Thanks for taking the time to compile the list Mat

> logstash-codec-netflow 3.11.4 to 3.14.0: seems to add support for more of the spec, plus a few bug fixes. Not familiar enough to know if this is safe or not: Commits · logstash-plugins/logstash-codec-netflow · GitHub

I vote on including. Changes are typically small and consist of supporting new devices.

> ❓ logstash-input-file 4.0.5 to 4.1.2: 4.1.0 seems like a lot of changes, not sure I would include. However 4.1.1 and 4.1.2 were important fixes. Should we backport those to 4.0,x or let the bump to 4.1.x happen here?

I vote not including, for the same reasons as the http input: too many changes for a patch release. if a user wants these features we support updating the plugin.

> ❓ logstash-output-elasticsearch 7.4.2-java to 7.4.3-java: quite a few changes, not familiar with the 7.x branch. I'm deferring to João on this one.

These are backports of bugfixes, and they all include tests that pass, so I vote including.

> ❓ dotenv: not familiar enough with the gem. Quite a few commits, and 2.4.0 reverts an addition from 2.3.0: dotenv/Changelog.md at v2.4.0 · bkeepers/dotenv · GitHub -- ** Were may want to freeze this one at 2.2.2 for now? **

Let's not include this

> ❓ elasticsearch-ruby: I'll defer to gem contributor João on this one ;-) elasticsearch-ruby/CHANGELOG.md at master · elastic/elasticsearch-ruby · GitHub

Let's skip this one too, there's a lot of changes and no known bugs we'd like to fix through this bump

> ❌ sequel: 42 commits since 3.7.1. Not a dependency of any plugin. I would stick to previous version.

Guy called it, let's include it.

**Comment by webmat** [comment]
I've updated my previous entry to be much more useful. Don't just read the email notification it generated, updated version is better ^ 🙃

**Comment by guyboertje** [comment]
I pinned the gems as agreed. Some patch level updates to other gems sneaked in since the last review round.

```
aws-sdk (2.11.56) # from 2.11.54
logstash-codec-netflow (3.14.1) # from 3.14.0
docile (1.3.1) # from 1.3.0
```

**Comment by webmat** [comment]
My opinion is that all 3 should be fine.

* aws-sdk is probably just more generated code updates
* logstash-codec-netflow is a patch release, and you both seem to trust Jorit. So I trust by transitivity, because I trust you both :-)
* docile is a simplecov dependency, which is a dev dependency.

**Comment by guyboertje** [comment]
@webmat thanks!!

**Pull request merged**
