### PR TITLE
Doc:Add section to security docs for API key information

### PR DESCRIPTION
**Pull request by karenzone**
**PREVIEW:**  https://logstash_11974.docs-preview.app.elstc.co/guide/en/logstash/master/ls-security.html#ls-api-keys

### CODE REVIEW

**Comment by karenzone** [comment]
cc:/ @colinsurprenant

**Comment by colinsurprenant** [comment]
since we have both the monitoring/management in logstash and the plugins use cases maybe we could keep the doc mostly generic and unlike the beats doc which has a section "Create an API key for publishing" and another for "Create an API key for monitoring" maybe we could have just a single "Create an API key" section with the same structure as either of the above?

**Comment by colinsurprenant** [comment]
link to beats docs https://www.elastic.co/guide/en/beats/filebeat/master/beats-api-keys.html

**Comment by karenzone** [comment]
Sounds good. I'll take this forward. Will you approve this PR so we can have a valid link in place for the release notes? I'll continue work from there.

**Comment by colinsurprenant** [comment]
LGTM

**Pull request merged**
