### PR TITLE
[wip] Add `http_proxy` support back

### PR DESCRIPTION
**Pull request by ph**
We are using the Gem's fetcher to verify if a gem is a logstash plugin or not so we need to make sure the gem configuration uses the `http_proxy`. 

Bundler is better citizen and uses the environment variable to configure the proxy correctly, but jar-dependencies is using the wrong key to access the proxy configuration.

http_proxy bundle install logstash-ouput-elasticsearch
Fixes: https://github.com/elastic/logstash/issues/2851

### CODE REVIEW

**Comment by ph** [comment]
@electrical Can you give me a hand to test this correctly?

**Comment by ph** [comment]
OKAY:

Ruby side:
* Rubygems and bundler uses my proxy
* Ruby-Maven receive my arguments send them to a weird java class but mvn doesn't uses the http_proxy. Computers :tophat:

**Comment by wiibaa** [comment]
Sorry cannot help but just out of curiosity, is it related to https://github.com/mkristian/jar-dependencies/issues/6
and https://github.com/mkristian/jar-dependencies/commit/fc441e41db2c921c22e50abf352495ec733b5038 or is bundler trying to go another path ?

**Comment by ph** [comment]
@wiibaa Yes this seem related, I am trying to run the test suite of `jar-dependencies` Sadly it's not as easy as `rake test`. The suite hang for me.. for some reason.

I was able to track down all the calling chain to the maven call, all the args are there now but maven doesn't use them.

**Comment by wiibaa** [comment]
@ph do you know if the ENV variable JARS_MAVEN_SETTINGS is pointing to some weird default/autogenerated settings.xml has from this spec it seems to bypass the Gem proxy setting: https://github.com/mkristian/jar-dependencies/blob/master/specs/maven_exec_spec.rb#L63-L69

**Comment by ph** [comment]
@wiibaa I've checked that route and added a trace down to the ruby-maven gem, maven seems to receive the appropriate proxy option but ignore them (I dont know why), I am trying to isolate the issue outside of logstash using only the `logstash-output-elasticsearch` and see If I can make jars download with a proxy using:

1. A environment variable for the proxy
2. A the `JARS_MAVEN_SETTINGS` env variable referencing a `settings.xml` with a valid proxy configuration.

**Comment by ph** [comment]
@wiibaa concerning the bundler, all the gems are actually downloaded via the proxy, I use squid locally to make sure it does.

**Comment by ph** [comment]
closing this PR #2954 will make this obsolete, since bundler already support http proxy natively.

**Pull request closed without merging**
