### PR TITLE
[8.0] handle fully acked 0 byte PQ pages (#13692)

### PR DESCRIPTION
**Pull request by kaisecheng**
Backports the following commits to 8.0:
 - handle fully acked 0 byte PQ pages (#13692)

### CODE REVIEW

**Comment by kaisecheng** [comment]
CI red is because a new version of jruby-openssl 0.12.1 was released, while the lock file pin to 0.11.0. 
bumping lock file solves the issue.

**Comment by jsvd** [comment]
@kaisecheng can you open an issue to track this version bump of jruby-openssl? ping @kares there too, who may have something to say on upgrading to 0.12.1.

**Comment by kares** [comment]
opened: https://github.com/elastic/logstash/issues/13781 I am going to investigate the CI failure as well as the regression mentioned in the issue (I do not think it affects LS but still).

8.0 has jruby-openssl locked to 0.11.0 so it kind of seems like an issue with installing the latest and than starting wout a bundler/setup.

**Review by kares — APPROVED** [review]
LGTM :red_circle: CI isn't related to the back-port and will be followed upon separately

**Pull request merged**
