### PR TITLE
KILL_ON_STOP_TIMEOUT fix

### PR DESCRIPTION
**Pull request by samuraiii**
Possible way to fix unary error ...

### CODE REVIEW

**Comment by purbon** [comment]
Hi, 
   thanks a lot for your contribution, at my understanding the idea of this var is that people can actually set it on the environment, with this it will be always be set, isn't?

On the other side, to continue you will need to sign the CLA process: https://www.elastic.co/contributor-agreement/

/cheers

**Comment by samuraiii** [comment]
Yes it will be set but (default as I uderstand should be this value), it is by default set in /etc/sysconfig/logstash but there should be just differences from default ... (file should be commented whole on clean install and all defaults should be set in /etc/init.d/logstash and possible overridden by in  /etc/sysconfig/logstash as you do it now with all other variables).

**Comment by samuraiii** [comment]
You can commit that fix yourself I am not going to sign that for one-liner fix...

**Comment by purbon** [comment]
Oh sorry to read that, I would be very happy to merge your fix, but can not do without the CLA, I hope you understand. I will close this PR, but keep the issue open to implement and think about this issue. thanks a lot for your time and understanding.

**Pull request closed without merging**
