### PR TITLE
Update serverless tests to include product origin header

### PR DESCRIPTION
**Pull request by donoghuc**
## Release notes
[rn:skip]

## What does this PR do?

This commit updates the curl scripts that interact with Kibana's
`api/logstash/pipeline/*` endpoints.

### CODE REVIEW

**Comment by robbavey** [comment]
cc @jsvd, @kaisecheng

**Comment by jsvd** [comment]
I don't think we'll have much success in knowing the outcome of this effort given we can't see serverless' logs from the management page. But otherwise this was indeed the goal. @kaisecheng can we trigger the serverless testing bk pipeline using this branch?

**Comment by kaisecheng** [comment]
I triggered buildkite [job](https://buildkite.com/elastic/logstash-serverless-integration-testing/builds?branch=pull%2F16766%2Fmerge) for this pr
Screenshot 2024-12-12 at 11 23 10

It is green :) need to add the header to other eg. CPM, es-integration-filter, es-output...

**Comment by robbavey** [comment]
> It is green :) need to add the header to other eg. CPM, es-integration-filter, es-output...

@kaisecheng I believe all of the places we need to add these should have been captured in https://github.com/elastic/ingest-dev/issues/4279 and https://github.com/elastic/ingest-dev/issues/4278.

If you see a place that we have missed, please update these issues and let me know.

**Comment by kaisecheng** [comment]
@robbavey The serverless tests call API of [CPM](https://github.com/elastic/logstash/blob/main/ci/serverless/cpm_tests.sh#L10) , [_ingest pipeline](https://github.com/elastic/logstash/blob/main/ci/serverless/elastic_integration_filter_tests.sh#L7) and [_count](https://github.com/elastic/logstash/blob/main/ci/serverless/metricbeat_monitoring_tests.sh#L43), which should add the header.

Plugins are fine.

**Comment by robbavey** [comment]
Gotcha. Thank you @kaisecheng!

**Comment by donoghuc** [comment]
I can add headers to those as part of this PR. Thanks!

**Comment by donoghuc** [comment]
Updated all interaction i saw with ES and Kibana. Kicked off a build of serverless tests: https://buildkite.com/elastic/logstash-serverless-integration-testing/builds/595 Will keep an eye on the status of that build.

**Review by kaisecheng — APPROVED** [review]
LGTM

**Comment by donoghuc** [comment]
Looks like https://buildkite.com/elastic/logstash-serverless-integration-testing/builds/595 went green. Thanks for the help!

**Comment by donoghuc** [comment]
@logstashmachine backport 8.x

**Pull request merged**
