### PR TITLE
update to jruby-1.7.20 and cleanup legacy patches

### PR DESCRIPTION
**Pull request by colinsurprenant**

### CODE REVIEW

**Comment by colinsurprenant** [comment]
solves #3271 and relates to #2747 #2817

**Comment by purbon** [comment]
I wonder if there is a way to test that the patch is no longer need with the new jruby? 

for the rest the patch looks good to me (LGTM).

/cheers

- purbon

**Comment by colinsurprenant** [comment]
I manually ran specs for core and default-plugins. Also, this is related to an older version of jar-dependencies and we don't dynamically install jar dependencies into our plugins. Exception is kafka through jruby-kakfa, and tests/specs passed.

**Comment by suyograo** [comment]
+1.. would like to get this baking on Jenkins

**Pull request merged**
