### PR TITLE
JAVAFICATION: Move remaining Logstash::Timestamp Ruby Code to Java

### PR DESCRIPTION
**Pull request by original-brownbear**
Just resolving the todos here :)

Notes:
* Had to keep the `timestamp.rb` file, otherwise at least the date filter breaks
* I know there is an inconsistency between the `+` and `-` methods, I simply ported this 100% and it should probably be fixed. Didn't want to change behavior in this step though so I left it as is or easier reviewing :)
* Other than that the approach is pretty standard for JRuby I think, including `Comparable` doesn't actually inherit any methods => had to code the comparisons manually and did so exactly the same way it's done in `RubyString`

### CODE REVIEW

**Comment by jsvd** [comment]
What if we just make this for 7.0 and break the behaviour?

**Comment by original-brownbear** [comment]
@jsvd we could I guess :) I'm not opposed to doing that, though it does introduce some divergence between `6.x` and `7.x`. Maybe merge this to both, then break behaviour in another PR just in `master`?

**Comment by jsvd** [comment]
+1 on merging as is and discussing the breaking change separately

**Comment by original-brownbear** [comment]
@jsvd thanks :)

**Pull request closed without merging**
