### PR TITLE
Fixes a filing test

### PR DESCRIPTION
**Pull request by andsel**
On master a test fails due to some strings coming out on log that before wasn't present. This PR fixes that test

### CODE REVIEW

**Comment by jsvd** [comment]
@andsel please write a more descriptive commit message, and maybe add a link to a failed CI test.

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Seems a case of "don't work on my machine", because on my laptop fails with:
`
Failures:

      1) CLI > logstash-plugin prepare-offline-pack create a pack from a wildcard successfully create a pack
         Failure/Error: expect(unpacked.plugins.collect(&:name)).to include(*filters)
           expected ["logstash-filter-prune", "logstash-filter-aggregate", "logstash-filter-jdbc_static", "logstash-filte...ash-filter-clone", "logstash-filter-anonymize", "logstash-filter-cidr", "logstash-filter-memcached"] to include "2019-11-27T12:20:25.380+01:00 [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch" and "Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable."
         # ./specs/cli/prepare_offline_pack_spec.rb:56:in `block in <main>'
         # /home/andrea/workspace/logstash_andsel/build/qa/integration/vendor/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in <main>'
         # ./rspec.rb:17:in `<main>'
`

so that I've filtered out from the list the strings that start with `sun.nio.ch`

**Comment by andsel** [comment]
This warning seems to happen only with JDK >=9 and JRuby 9.2.9.0. I close this PR, because is not a problem in the test, but related to config vars to pass to JRuby

**Pull request closed without merging**
