### PR TITLE
Fix system unit TimeoutStopSec on older version. 

### LINKED ISSUE #12453: Handle `TimeoutStopSec=infinity` corretly for `Centos-7` systemd init script
Logstash installation scripts, executed when deb or rpm are installed, generate init scripts for various service managers, like sysv/sysytemd/upstrart.
This init script contains the definition `TimeoutStopSec=infinity` ([generated by pleaserun](https://github.com/jordansissel/pleaserun/blob/972cff10fab32703303fd26c4c97d21ce2a1eedf/templates/systemd/default/program.service#L27)) for `systemd` that's not accepted by any systemd's version, so it happens that on `Centos-7` which uses a version before 229, the scripts doesn't wait the termination of Logstash for infinity, but it kills it immediately, after a `service logstash stop`.

More details on jordansissel/pleaserun#146

This issue related to pleaserun, there is a PR #12415 to move away from pleaserun, so we have to be sure that `TimeoutStopSec=infinity` is handled correctly by the new scripts.

### PR DESCRIPTION
**Pull request by roaksoax**
## What does this PR do?
Starting from systemd 229, `TimeoutStopSec` supports using 'infinity' to prevent the service manager from sending a SIG Kill when stopping the service. This effectively allows logstash to shutdown gracefully including possibly long-running operations such as draining the queue (or other operations).

However, on Operating Systems with older versions of Systemd, such as CentOS7 or Debian Jessie, the setting didn't support the infinity option, and instead used the number 0.

As such, this PR introduces a post-installation change in which it fixes the Systemd Unit in the event of it being installed in an older, soon to be deprecated operating system.

## Why is it important/What is the impact to the user?

This change is important because otherwise, users who stop the Logstash service using a very old service manager would potentially loose data.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## How to test this PR locally

 - Build the package
 - Install the package or upgrade the package.

## Related issues

- Closes #12453

### CODE REVIEW

**Review by andsel — APPROVED** [review]
LGTM
Tested on Debian 8

**Comment by roaksoax** [comment]
@andsel can you confirm that it overwrites the systemd with a new file and then updates accordingly. I came across an issue in both Debian 9 and Centos 8 that if I do the following, it won't work as expected.

1. Install older version of Logstash - 8.6
2. Manually modify /lib/systemd/system/logstash.service to change TimeoutStopSec=0
3. Install the newer version of the package.
4. Found out that the "new" systemd service file being shipped in the package doesn't automatically override the "old" manually modified one.

Can you confirm this happens to you as well?

**Comment by andsel** [comment]
@roaksoax I tested with a fresh environment, not tried the update of an existing Logstash, I'll do

**Comment by roaksoax** [comment]
@logstashmachine backport 8.7

**Pull request merged**
