### PR TITLE
fix filter flushing regression and event cancellation bug

### LINKED ISSUE #3100: [1.5.0-RC3] filters: undefined local variable or method `event`
As reported by @wjimenez5271 using 1.5.0-RC3 while debugging https://github.com/elastic/logstash/issues/3092

```
$ sudo /opt/logstash/bin/logstash -f /etc/logstash.d/lumberjack.conf
Exception in filterworker {"exception"=>#<NameError: undefined local variable or method `event' for #<LogStash::Pipeline:0x51a97faa>>, "backtrace"=>["(eval):111:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:309:in `flush_filters'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:308:in `flush_filters'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:317:in `flush_filters_to_output!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:223:in `filterworker'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:223:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:156:in `start_filters'"], :level=>:error}
Logstash startup completed
cx^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
Exception in lumberjack input {:exception=>#<LogStash::ShutdownSignal: LogStash::ShutdownSignal>, :level=>:error}
```

Config: https://gist.github.com/wjimenez5271/d145cf8906752b5a5cbe

### PR DESCRIPTION
**Pull request by colinsurprenant**
Fixes #3100 

The filter flushing problem is a regression caused by be the removal of the `multi_filter` method by commit 3eb5ba6450a2c241d469cc1740c5c46cc7509f02 from PR #2943 - this "optimization" was in fact not correct and we failed to realize it :P but most importantly there was no spec covering this case. 

@jordansissel also identified another problem with the event cancellation in 7d35dad46082ec938546116ca83db310ab736459. With the `multi_filter` method, the fix is simply to skip over cancelled events so I added this condition in `multi_filter`

I added specs for all these cases.

### CODE REVIEW

**Comment by jsvd** [comment]
code LGTM, ran tests :ship: it

**Comment by ph** [comment]
code lgtm, test ran, also tried @wiibaa's config with that PR with success.

**Comment by rtoma** [comment]
Seems fixed in rc4 (says the changelog). Could someone please release rc4?
The buggy rc3 release is still latest on https://www.elastic.co/downloads/logstash.

**Comment by ph** [comment]
The official package aren't out yet, should be later today.

**Pull request merged**
