### PR TITLE
Update default plugins for 5.0

### PR DESCRIPTION
**Pull request by suyograo**
5.0 is a chance for us to review and remove any plugins that we don't have to bundle by default. These plugins are still supported and maintained, but the default package should only contain most popular, most used plugins. 

**Removed plugins:**

logstash-filter-anonymize: Replaced with newer logstash-filter-fingerprint
logstash-input-zeromq/output: Not a lot of users. Most users seem to prefer rabbitmq, redis, kafka as broker
logstash-codec-netflow: not sure about this.
logstash-filter-multiline: deprecated
logstash-output-hipchat: not maintained. Still at v1 of API.
logstash-output-juggernaut: less usage

Please comment if you'd like to remove more/less

/cc @acchen97 @jordansissel

### CODE REVIEW

**Comment by ph** [comment]
Concerning `logstash-codec-netflow`, we have a new community maintainer for it, and I can say he is really active.

`logstash-output-hipchat` Was completely rewritten by me a few month ago and It does support the v2 api and we use the official hipchat gem for it.

**Comment by suyograo** [comment]
@ph we also need to measure if folks are actively using it. Remember these plugins can still be installed via `bin/logstash-plugin install`

**Comment by ph** [comment]
@suyograo Agree, we need to find a way to make the rubygems stats meaningful, right now theses stats are obfuscated by our build process.

**Comment by acchen97** [comment]
@suyograo I'm +1 on keeping netflow codec in for now.  You've removed most of the ones I had in mind, here's a few others proposals.

Remove:
- ganglia output
- gelf output
- nagios output
- nagios_nsca output
- null output

Add:
- translate filter
- webhdfs output

**Comment by ph** [comment]
@acchen97 I am +1 with your proposed changes

**Comment by jsvd** [comment]
I know this has been discussed already but I'm a bit on the fence with removing the multiline filter, as we don't have an alternative solution to dealing with multiline after codec, even if it means using a single input and -w 1

Do we have any statistics on how much this plugin is still used today?

Also, I suggest removing the checksum filter, should have been gone a long time ago https://github.com/logstash-plugins/logstash-filter-checksum/issues/2

**Comment by acchen97** [comment]
@jsvd this is just for removing multiline filter from default package.

> Also, I suggest removing the checksum filter, should have been gone a long time ago logstash-plugins/logstash-filter-checksum#2
+1 on removing this from logstash-plugins org, removing [output-elasticsearch_http](https://github.com/logstash-plugins/logstash-output-elasticsearch_http) makes sense too.

**Comment by suyograo** [comment]
@jsvd we are removing multiline filter from the defaults. Since it is deprecated, if someone has the edge case of using it, then can always install it

**Comment by suyograo** [comment]
@ph @acchen97 can you guys take another look? Updated

**Comment by acchen97** [comment]
LGTM

**Comment by ph** [comment]
LGTM

**Pull request closed without merging**
