### PR TITLE
Migrate remaining PR jobs to Buildkite

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

This commit adds the remaining steps for the Buildkite pull request pipeline i.e.

- `IT Persistent Queues / part 1`
- `IT Persistent Queues / part 2`
- `x-pack unit tests`
- `x-pack integration`

Once merged we will be able to retire the corresponding Logstash pull request multijob.

## Related issues

- https://github.com/elastic/logstash/pull/15438
- https://github.com/elastic/logstash/pull/15437
- https://github.com/elastic/ingest-dev/issues/1721
- https://github.com/elastic/logstash/pull/15279

### CODE REVIEW

**Comment by dliappis** [comment]
We can see the jobs run successfully as part of the checks in this PR: https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/50

This PR concludes the migration of all nine PR jobs from Jenkins.

**Review by roaksoax — APPROVED** [review]
lgtm!

**Comment by dliappis** [comment]
@logstashmachine backport 8.11

**Comment by dliappis** [comment]
@logstashmachine backport 8.10

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Pull request merged**
