### PR TITLE
support unix directory paths with '='

### PR DESCRIPTION
**Pull request by mnikhil-git**
unix directory paths can have '='

### CODE REVIEW

**Comment by mnikhil-git** [comment]
I do not know about CLA stuff, so not sure how can I get my patch here

**Comment by purbon** [comment]
Hi, it would be great if you reopen this PR at https://github.com/logstash-plugins/logstash-patterns-core ... since the 1.5 release all components of logstash have their own home, and that repo is for the patterns.

Thanks,

/purbon

**Comment by mnikhil-git** [comment]
sure thanks @purbon I have opened a pr over there..

may be its worth to get logstash-patterns-core under elastic home too?

**Comment by jsvd** [comment]
This was moved to https://github.com/logstash-plugins/logstash-patterns-core/pull/81

**Pull request closed without merging**
