### PR TITLE
valid variable expansion for the batch files

### PR DESCRIPTION
**Pull request by 111andre111**
Looking at documentation https://ss64.com/nt/delayedexpansion.html
for local variable expansion under Windows should be used only one exclamation mark not two.
In a test proved it that with 2 exclam. marks it didn't work under Windows.

### CODE REVIEW

**Comment by 111andre111** [comment]
@robbavey  I have a question. benchmark.bat and benchmark.sh make only sense with `tools\benchmark-cli\build\libs\benchmark-cli.jar` in the distributable - which isn't contained in the whole logstash artifact. So either we should remove these 2 scripts from the resulting artifact, or add that the jar file will be added. However I am not sure where to add this artifact would that be under logstash-dev somewhere?

**Comment by robbavey** [comment]
@111andre111 That probably warrants a separate issue not tied to this one. 

I agree that we should either remove the scripts or include the benchmark artifacts in the release, but let's talk about that in a new issue. We have a [meta issue](https://github.com/elastic/logstash/issues/12785) related to work around the benchmark tool (which we can link the new issue to). That tool hasn't had a lot of love for quite a while, and isn't really publicized enormously

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by 111andre111** [comment]
@robbavey Added new issue https://github.com/elastic/logstash/issues/12920 and added this one to the metaissue as well.

**Review by robbavey — APPROVED** [review]
LGTM!

**Pull request merged**
