### PR TITLE
Fix typo of tail unix command

### PR DESCRIPTION
**Pull request by DerekRoth**
Same issue as #1927 and same fix.

### CODE REVIEW

**Comment by DerekRoth** [comment]
I have signed the CLA just after the creation of this PR, so the merge should be possible now.

**Comment by untergeek** [comment]
This PR is unfortunately behind.  Can you rebase it against master, please?

**Comment by DerekRoth** [comment]
OK, done it!

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
