### PR TITLE
Avoid to create and upload AARCH64 Docker images for UBI8

### PR DESCRIPTION
**Pull request by andsel**
## Release notes

[rn:skip]

## What does this PR do?

On ARM architecture UBI8 Docker images aren't created, so avoid to create empty tar.gz files.

## Why is it important/What is the impact to the user?

As a CI user I don't want that non expected artifacts blocks the job.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by kaisecheng — APPROVED** [review]
LGTM

**Comment by andsel** [comment]
@logstashmachine backport 8.6

**Comment by andsel** [comment]
@logstashmachine backport 8.6

**Comment by andsel** [comment]
@logstashmachine backport 8.5

**Comment by andsel** [comment]
@logstashmachine backport 7.17

**Pull request merged**
