### PR TITLE
bump to 5.1.3

### PR DESCRIPTION
**Pull request by ph**
Working on making this branch work with the unified build.

### CODE REVIEW

**Comment by ph** [comment]
nevermind wrong version ;) let me repush

**Comment by ph** [comment]
should be fine for review.

**Comment by ph** [comment]
These two error seems legit, will look into it.
```
  2) Test removal of plugin when other plugins depends on this plugin refuses to remove the plugin and display the plugin that depends on it.
     Failure/Error: expect(execute.stderr_and_stdout).to match(/Failed to remove "logstash-codec-json"/)
       expected "Gem::LoadError: You have already activated json 1.8.6, but your Gemfile requires json 1.8.3. Prepend...at /home/travis/build/elastic/logstash/build/logstash-5.1.3-SNAPSHOT/lib/pluginmanager/main.rb:44\n" to match /Failed to remove "logstash-codec-json"/
       Diff:
       @@ -1,2 +1,14 @@
       -/Failed to remove "logstash-codec-json"/
       +Gem::LoadError: You have already activated json 1.8.6, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this.
       +    setup at /home/travis/build/elastic/logstash/build/logstash-5.1.3-SNAPSHOT/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
       +     each at org/jruby/RubyArray.java:1613

``

**Comment by suyograo** [comment]
Fixed via https://github.com/elastic/logstash/commit/8f39da19b809bb9ce23a02043816e1d87b339109

**Pull request closed without merging**
