### PR TITLE
Added double quotations to command for Windows

### PR DESCRIPTION
**Pull request by catonice**
Single quotations cause errors, should be double quotes

## What does this PR do?

Update the documentation for getting started with logstash

Replaced single quotes with double quotes because single quotes cause unknown command errors

## Why is it important/What is the impact to the user?

Allows the correct command to be used and for the user to progress with getting started with Logstash

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[] I have commented my code, particularly in hard-to-understand areas~~
- ~~[] I have made corresponding changes to the documentation~~
- ~~[] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~[] I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [x] Double check syntax

## How to test this PR locally

Run the command with the double quotes through logstash

### CODE REVIEW

**Comment by logstashmachine** [comment]
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

**Comment by jsvd** [comment]
@catonice thanks for your contribution, do you mind targetting this PR to master instead of 7.11 branch? thank you!

**Comment by catonice** [comment]
> @catonice thanks for your contribution, do you mind targetting this PR to master instead of 7.11 branch? thank you!

Done

**Comment by karenzone** [comment]
Hi @catonice Your original change is a good one. It's important that we present info for Windows while maintaining content for other platforms. I'm flagging this PR so that we don't lose it.  Thank you for helping us make our documentation better.

**Comment by catonice** [comment]
> Hi @catonice Your original change is a good one. It's important that we present info for Windows while maintaining content for other platforms. I'm flagging this PR so that we don't lose it. Thank you for helping us make our documentation better.

I created a newer one with fewer merge issues from the master branch here: https://github.com/elastic/logstash/pull/12706#issuecomment-788730619

**Pull request closed without merging**
