### PR TITLE
[ci] Add testing phase to exhaustive tests suite

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

This is the second part of the migration of the exhaustive/main Jenkins Job to Buildkite. So far we've migrated the "compatibility phase" and this commit adds the "testing phase"[^1], which is essentially the same amount of tests that we ran on PR jobs.

For more details, refer to the sequence diagram in https://github.com/elastic/ingest-dev/issues/1722#issuecomment-1824378635

## Why is it important/What is the impact to the user?

This runs the usual set of unit + IT tests in the [exhaustive test pipeline](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline), e.g. triggered by push events.

## How to test this PR locally

See triggered BK job: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/41#_

## Screenshots

Once triggered e.g. [in this link](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/41#_) in the structure looks like:

image

## Related issues

- Relates https://github.com/elastic/ingest-dev/issues/1722
- Depends https://github.com/elastic/logstash/pull/15708

### CODE REVIEW

**Review by robbavey — APPROVED** [review]
Assuming that the windows test permissions failures while attempting to run DLQ tests are unrelated to this change, LGTM

**Comment by dliappis** [comment]
> Assuming that the windows test permissions failures while attempting to run DLQ tests are unrelated to this change, LGTM

@robbavey yes it's unrelated as the Windows failure is in the Compatibility group, which we don't touch here.
For background, the test failure is known and logged in: https://github.com/elastic/logstash/issues/15562
and we can see it reproducing in other jobs too e.g. the Windows JDK matrix weekly: https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/55#018c7f97-b89e-4a38-93fb-26b37f7bd9af
Downloading the [build_reports.zip](https://buildkite.com/organizations/elastic/pipelines/logstash-windows-jdk-matrix-pipeline/builds/55/jobs/018c7f97-b89e-4a38-93fb-26b37f7bd9af/artifacts/018c7fa0-b0ee-4f2a-980c-e69e6cbc13dd) artifact, we can confirm it's the same issue:

image

We are currently missing collecting the failure report in the compat job of this suite (which we do in the JDK matrix ones as I said above), so I'll tackle this unrelated issue in a follow up PR.

**Comment by dliappis** [comment]
@logstashmachine backport 8.12

**Comment by dliappis** [comment]
@logstashmachine backport 8.11

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Pull request merged**
