### PR TITLE
Update hello-search.conf to avoid Version Mismatch

### PR DESCRIPTION
**Pull request by manavkataria**
Update hello-search.conf to avoid ES <-> Logstash Version Mismatch Error

### CODE REVIEW

**Comment by manavkataria** [comment]
I've signed the CLA now.

**Comment by suyograo** [comment]
@manavkataria you can force push an update using `git push origin -f <branch_name>`

**Comment by jordansissel** [comment]
I think this file only is used in 1.4 branch, 1.5+ uses asciidoc only and this tutorial was merged into others.

**Comment by manavkataria** [comment]
@jordansissel Is this update required in 1.5 as well?

**Comment by jordansissel** [comment]
@manavkataria the documentation doesn't refer to that anymore. In 1.5 and master we should probably just delete the old content.

**Comment by manavkataria** [comment]
@jordansissel Agreed, that should avoid any confusion.

**Pull request closed without merging**
