### PR TITLE
[6.0] Bump version to RC1

### PR DESCRIPTION
**Pull request by suyograo**

### CODE REVIEW

**Comment by ph** [comment]
LGTM

**Comment by jordansissel** [comment]
I found one instance of 6.0.0-beta stil hanging around: docs/index-shared1.asciidoc

**Comment by ph** [comment]
@jordansissel you are correct, I've looked at the rendered content, I think the rake's set version that we use could that care of that.

**Comment by ph** [comment]
I've create this https://github.com/elastic/logstash/issues/8114

**Comment by suyograo** [comment]
@jordansissel @ph the docs version only gets updated on the day of release, so we're good here.

**Pull request merged**
