### PR TITLE
Allow dependabot to keep gradle packages up-to-date

### PR DESCRIPTION
**Pull request by jlosito**
## What does this PR do?

This change allows dependabot to check any dependency managed via gradle weekly and submit PRs with version bumps in order to keep packages up-to-date.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

## Why is it important/What is the impact to the user?

It's good to update packages for various reasons such as performance, security, feature, bug fixes, etc.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by logstashmachine** [comment]
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

**Comment by andsel** [comment]
Hi @jlosito 
thanks to have submitted this, to effectively take care of this and review it you should sign the  CLA, please

**Comment by jlosito** [comment]
@andsel I've just signed the CLA. 

I'm assuming that it takes some time for a job to kick off again to verify it's signed now.

**Comment by jlosito** [comment]
Closing due to inactivity.

**Pull request closed without merging**
