### PR TITLE
Unify logging properties across distributions

### LINKED ISSUE #9066: Use newer log retention policy in rpm/deb packages.
Reference: https://github.com/elastic/logstash/pull/8815

The [log4j2.properties file](https://github.com/elastic/logstash/blob/master/pkg/log4j2.properties) used in rpm and deb packages should be updated to use the same policy as implemented in #8815.

### PR DESCRIPTION
**Pull request by danhermann**
Removes `pkg/log4j2.properties`, `pkg/jvm.options`, and `pkg/startup.options` and copies the corresponding files from `config` during execution of the `rake artifact:rpm/deb` tasks so two separate copies of those files don't have to be kept in sync.

Fixes #9066, #8499.

### CODE REVIEW

**Comment by jakelandis** [comment]
@jordansissel - should we put this into the up-coming `6.2.0` release to avoid odd messaging w/r/t ZIP vs. RPM/DEB packaging ?

**Comment by danhermann** [comment]
@jakelandis, sorry for the delay on this one. I removed the symlinks, modified the `rake artifact` tasks to copy the config files from a single location in the `config` folder, removed the duplicate files in the `pkg` folder, and verified that both `rpm` and `deb` files are generated with the appropriate config files.

**Comment by jakelandis** [comment]
LGTM - i also verified the `deb` is correct _(had un-related issues with my `rpm` build environment)_

**Comment by danhermann** [comment]
Thanks, @jakelandis!

**Pull request closed without merging**
