### PR TITLE
Refactor rats

### PR DESCRIPTION
**Pull request by wainersm**
Following PR is a first step towards getting rid of shell scripts to manage services on integration tests.

### CODE REVIEW

**Comment by suyograo** [comment]
@wainersm you rock! thanks for this!

**Comment by wainersm** [comment]
Hello @suyograo  ! Please let me know if this changes have a good design because I plan to get rid of the other scripts (for kafka, httpd..etc) using this change as blueprint.

Ah, the failure in travis-ci are not related with my changes. It's more likely an intermittent error in logstash core tests.

**Comment by suyograo** [comment]
@wainersm yes this is a good approach. this should be portable to windows now.

**Comment by suyograo** [comment]
@wainersm actually please hold off. we are rethinking our services strategy. We may use a docker based approach here. I will be able to write more details soon.

**Comment by wainersm** [comment]
Hi @suyograo , roger that! Indeed a container approach seems perfect fit for integration tests. I look forward more details.

**Comment by ph** [comment]
I have also created this simple helper library https://github.com/ph/belzebuth that could help refactor some of the test. It help to synchronize external process, look a the suite for example, I still need to write some documentation for it.

**Comment by suyograo** [comment]
@wainersm I'm gonna close this given the docker direction. If you'd like to help out you could take https://github.com/elastic/logstash/issues/7097

**Comment by wainersm** [comment]
Hi @suyograo #7097 is already set to @original-brownbear . I made a comment there.

**Pull request closed without merging**
