### PR TITLE
Remove dependency:bundler task

### PR DESCRIPTION
**Pull request by robbavey**
Already done on master in #12017, this is unnecessary as it is already being done
by installBundler.

## Release notes
[rn:skip]

## What does this PR do?

Removed the `dependency:bundler` task, it is no longer necessary, and caused build issues if the version was not kept in sync with that in the `installBundler` gradle task

## Why is it important/What is the impact to the user?

Fixes release manager builds

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~

## How to test this PR

Acceptance test kicked off [here](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/288/)

### CODE REVIEW

**Comment by robbavey** [comment]
jenkins test this please

**Comment by robbavey** [comment]
jenkins test this please

**Comment by robbavey** [comment]
Note: The integration test that was failing (before the version bump to `7.16.0` which will always fail at this time due to lack of stack artifacts) was also failing on the `7.x` branch prior to this PR - 
https://logstash-ci.elastic.co/job/elastic+logstash+7.x+multijob-integration-1/545

**Review by andsel — APPROVED** [review]
LGTM

**Pull request merged**
