### PR TITLE
Chore: fetch merge commit automatically with backport dev tool

### PR DESCRIPTION
**Pull request by kares**
Some minor usability improvements I've been using for a while.
Please double check if anything got messed up, sample usage:

`devtools/backport 7.16 13481` (without having to copy and specify commits)

sample PR created (notice the updated formatting - to visually differentiate the "copied PR desc"): https://github.com/elastic/logstash/pull/13484

## Release notes

[rn:skip]

### CODE REVIEW

**Comment by yaauie** [comment]
Although we have squash commits enabled currently, is it possible for this to hit a pull-request that has been fast-forward merged (and if so, how bad would it be to silently auto-select the head commit)?

**Comment by kares** [comment]
> Although we have squash commits enabled currently, is it possible for this to hit a pull-request that has been fast-forward merged (and if so, how bad would it be to silently auto-select the head commit)?

Only cared about "Squash and Merge" here esp. since it's unnecessary extra work having to lookup the commit hash.

For "Create a Merge Commit" strategy this would fail (due the missing `git cp -m` option), but for "Reabase and Merge" it is going to pick the HEAD commit after the rebase - and thus might miss older commits if they were independent of each other.

Likely the backport would fail on picking the HEAD commit due conflicts (missing previous commits from the PR). 
In case it does not fail it's up to the user to notice the missing commits, not sure we want to do any heuristics here trying to avoid that (given only "Squash and Merge" is enabled for the repository atm)? 
Does the merge_commit auto-detection feel rather dangerous? (Happy to continue looking up the SHA if anyone feels so).

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by jsvd** [comment]
wrt to @yaauie's point:
> Although we have squash commits enabled currently, is it possible for this to hit a pull-request that has been fast-forward merged (and if so, how bad would it be to silently auto-select the head commit)?

I believe this is a valid concern but at the end of the day the result of this tool is that a PR is created, so anyone can check that the result isn't useful and rerun it with an explicit commit hash.

**Pull request merged**
