### PR TITLE
[Doc] Add monitoring/management SSL regression note on release 8.8.0

### PR DESCRIPTION
**Pull request by edmocosta**
## Release notes

[rn:skip]

## What does this PR do?

Add a release note explaining the monitoring/management xpack SSL regression fixed by: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1142 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jsvd — APPROVED** [review]
overall LGTM but I haven't tested the workaround, so pinging @yaauie to confirm

**Comment by jeanfabrice** [comment]
Hi Team, any ETA for this doc update to be merged and published?

**Comment by edmocosta** [comment]
The `ca_trusted_fingerprint` wasn't modified by the SSL standardization so it should work properly as an alternative to the `ssl_certificate_authorities`. A few customers already confirmed that this workaround works so maybe we can go ahead and merge it. Any thoughts, @yaauie?

**Comment by robbavey** [comment]
@logstashmachine backport 8.9

**Pull request merged**
