### PR TITLE
Fixes #6417 force reload issues

### LINKED ISSUE #6417: Reload configuration not working
Hello,

I recently updated from 5.0.2 to 5.1.1 of logstash. I have been using the reload configuration feature for a while now but it seems that in 5.1.1 it has stopped working. Logstash acknowledges in the logs that it received a SIGHUP
`[2016-12-14T08:03:00,226][WARN ][logstash.runner          ] SIGHUP received.`
but it doesn't seem to actually reload the configuration. If I restart the service then it loads the new configuration correctly. I just tried doing a simple output to stdout, `stdout { codec => rubydebug }`, then reload the configuration but nothing is outputted to `/var/log/messages`.
I have used the reload configuration feature consistently since it's release. But with the latest Logstash release, 5.1.1, it seems to be broken.

Thanks in advanced!

- Version: 5.1.1 via yum repository
- Operating System: CentOS 7

### PR DESCRIPTION
**Pull request by driverpt**
Backmerge to 5.5 . 

Should i open a PR for 5.6 as well ?

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this please

**Comment by driverpt** [comment]
@original-brownbear , it failed due to unknown error on Windows

**Comment by original-brownbear** [comment]
@driverpt sorry I missed this when reading the initial PR description. I don't think we'll merge any more fixes like this one to `5.5` or `5.6`.
Please target this to `master` and `6.x` (shouldn't require separate PRs, the two are almost equal).

Thanks, and sorry again for missing this point!

**Comment by driverpt** [comment]
@original-brownbear , this has already been fixed in 6.x . No backport was made available because the whole SIG TRAP was rewritten. This is the quickest fix for older versions.

**Comment by original-brownbear** [comment]
@driverpt oh sorry didn't know that then I have to defer this to @suyograo @jordansissel (ping you guys :)).

**Comment by jsvd** [comment]
I'm ok with merging this to both 5.5 and 5.6, as we're in feature freeze for 5.6.0, so we can get bugfixes in. If we ever do a 5.5.2, it will ship there too.

@driverpt please squash the commits and I'll merge the PR

**Comment by driverpt** [comment]
@jsvd , done! 👍 

Thanks

**Comment by jsvd** [comment]
fixed in 5.5 and 5.6 branches, thanks for the contribution @driverpt

**Pull request closed without merging**
