### PR TITLE
Refactor qa/acceptance tests to get away from vagrant

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

This commit modernized the qa/acceptance (packaging) test framework by moving away from Vagrant and having the tests operate locally.

As we are migrating to Buildkite, the expectation is that those tests will run on dedicated vms thus removing the necessity of vagrant.

Relates: https://github.com/elastic/ingest-dev/issues/1722

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works -> this is the next step with the BK pipeline, but they can be tested successfully using custom vm images and https://github.com/elastic/ingest-dev/blob/main/engineer-productivity/tools/launch_linux_vm.sh

## How to test this PR locally

To test this locally, launch a VM using https://github.com/elastic/ingest-dev/blob/main/engineer-productivity/tools/launch_linux_vm.sh e.g.

`./launch_linux_vm.sh --image-family platform-ingest-logstash-multi-jdk-ubuntu-2204 --vm-name <my-username>-linux-logstash-jdk`

and then ssh there using the instructions. After that:

```
sudo -iu buildkite-agent /bin/bash
# clone into this PR
git clone https://github.com/elastic/logstash.git
cd logstash
git fetch origin pull/15696/head:localized_acceptance_tests
git switch localized_acceptance_tests

# EITHER

ci/acceptance_tests.sh

# OR
./gradlew clean bootstrap
# build deb artifacts
rake artifact:deb
cd qa
bundle install
# run acceptances tests for built artifacts
rake qa:acceptance:all
```

## Screenshots

After running the above command on a Debian 11 VM we see:

```
buildkite-agent@dl-linux-logstash-jdk:~/logstash/qa$ rake qa:acceptance:all

artifacts composition
  prohibited gem dependencies
    does not vendor any version of kramdown
  necessary gem dependencies (sanity check)
    vendors concurrent-ruby

artifacts operation
  behaves like installable_with_jdk
    is installed on [Debian GNU/Linux 11]
    is running on [Debian GNU/Linux 11]
    is removable on [Debian GNU/Linux 11]
  behaves like updated
    can be updated and run on [Debian GNU/Linux 11]

CLI operation
  behaves like logstash version
    logstash --version
      on [Debian GNU/Linux 11]
        returns the right logstash version
        when also using the --path.settings argument
          returns the right logstash version
  behaves like logstash install
    on [Debian GNU/Linux 11]
      with a direct internet connection
        when the plugin exist
          from a local `.GEM` file
            successfully install the plugin
          when fetching a gem from rubygems
            successfully install the plugin
            successfully install the plugin when verification is disabled
            fails when installing a non logstash plugin
            allow to install a specific version
        when the plugin doesnt exist
          fails to install and report an error
  behaves like logstash list
    logstash-plugin list on [Debian GNU/Linux 11]
      without a specific plugin
        display a list of plugins
        display a list of installed plugins
        list the plugins with their versions
      with a specific plugin
        list the plugin and display the plugin name
        list the plugin with his version
  behaves like logstash uninstall
    logstash-plugin uninstall on [Debian GNU/Linux 11]
      when the plugin isn't installed
        fails to uninstall it
      when the plugin is installed
        successfully uninstall it
  behaves like logstash remove
    logstash-plugin remove on [Debian GNU/Linux 11]
      when the plugin isn't installed
        fails to remove it
      when the plugin is installed
        successfully removes it
  behaves like logstash update
    logstash-plugin update on [Debian GNU/Linux 11]
      update a specific plugin
        has executed successfully
      update all the plugins
        has executed successfully
  behaves like integration plugins compatible
    logstash-plugin install on [Debian GNU/Linux 11]
      when the integration is installed
        trying to install an inner plugin separately
          fails to install
      when the integration is not installed
        if an inner plugin is installed
          installing the integrations uninstalls the inner plugin (PENDING: Temporarily skipped with xcontext)
    logstash-plugin uninstall on [Debian GNU/Linux 11]
      when the integration is installed
        trying to uninstall an inner plugin
          fails to uninstall it
    logstash-plugin list on [Debian GNU/Linux 11]
      when the integration is installed
        listing an integration
          shows its inner plugin
        listing an inner plugin
          matches the integration that contains it

Pending:
  CLI operation behaves like integration plugins compatible logstash-plugin install on [Debian GNU/Linux 11] when the integration is not installed if an inner plugin is installed installing the integrations uninstalls the inner plugin
    # Temporarily skipped with xcontext
    # ./acceptance/spec/shared_examples/cli/logstash-plugin/integration_plugin.rb:50

Finished in 15 minutes 33 seconds (files took 1.9 seconds to load)
30 examples, 0 failures, 1 pending
```

## Related issues

https://github.com/elastic/ingest-dev/issues/1722

### CODE REVIEW

**Comment by dliappis** [comment]
This is now ready for review.

I have already worked on the [corresponding Buildkite job](https://github.com/elastic/logstash/pull/15699) that builds on top of this PR and adds the acceptance phase to our current exhaustive tests pipeline, and we can see successful results for many os distros here: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/31#_ (RHEL-8 failure I believe is transient and not related to this PR).

Note to reviewers: I am sorry for the size of this PR, but as you will see it's mostly deletions. The background of what we implemented here is captured in this comment from @jsvd https://github.com/elastic/ingest-dev/issues/1722#issuecomment-1825830997 i.e. we remove the vagrant dependency on the acceptance qa framework and expect that it runs locally on the desired OS.

**Comment by jsvd** [comment]
As I'm testing the changes, I noticed that with the current instructions, the environment of the linux VM doesn't default to UTF8, causing many tests to fail. For example
```
buildkite-agent@jsvd-linux-logstash-jdk:~/logstash/qa$ SPEC_OPTS="-e 'display a list of plugins'" rake qa:acceptance:all
Run options: include {:full_description=>/display\ a\ list\ of\ plugins/}

CLI operation
  behaves like logstash list
    logstash-plugin list on [Debian GNU/Linux 11]
      without a specific plugin
US-ASCII
        display a list of plugins (FAILED - 1)

Failures:

  1) CLI operation behaves like logstash list logstash-plugin list on [Debian GNU/Linux 11] without a specific plugin display a list of plugins
     Failure/Error: expect(result.stdout.split("\n").size).to be > 1
     ArgumentError:
       invalid byte sequence in US-ASCII
     Shared Example Group: "logstash list" called from ./acceptance/spec/lib/cli_operation_spec.rb:36
     # ./acceptance/spec/shared_examples/cli/logstash-plugin/list.rb:39:in `block in <main>'
     # ./Rakefile:30:in `block in <main>'

Finished in 13.13 seconds (files took 1.04 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./acceptance/spec/shared_examples/cli/logstash-plugin/list.rb:36 # CLI operation behaves like logstash list logstash-plugin list on [Debian GNU/Linux 11] without a specific plugin display a list of plugins

```

Only after I ran `sudo dpkg-reconfigure locales` and selected "en_US.UTF-8" as the default, I could run the test successfuly:

```
buildkite-agent@jsvd-linux-logstash-jdk:~/logstash/qa$ SPEC_OPTS="-e 'display a list of plugins'" rake qa:acceptance:all
Run options: include {:full_description=>/display\ a\ list\ of\ plugins/}

CLI operation
  behaves like logstash list
    logstash-plugin list on [Debian GNU/Linux 11]
      without a specific plugin
UTF-8
        display a list of plugins

Finished in 13.44 seconds (files took 1.04 seconds to load)
1 example, 0 failures
```

**Comment by dliappis** [comment]
> Only after I ran `sudo dpkg-reconfigure locales` and selected "en_US.UTF-8" as the default, I could run the test successfuly:

@jsvd I had a chance to look at this into a little more depth. There are two things going on here:

1. (main issue) on macOS, `iterm2` defaults to setting the locale on the remote. It can be disabled using [this tip](https://askubuntu.com/questions/599808/cannot-set-lc-ctype-to-default-locale-no-such-file-or-directory#comment1640977_778672) or, alternatively, once you switch to the desired account `buildkite-user`, just `export LC_ALL=C.UTF-8`.

    By default, all images are configured and default to the `C.UTF-8` locale which is the usual minimalistic locale with UTF-8 enabled. 

2. As you discovered, the base images for debian don't seem to have `en_US.UTF-8` configured. As mentioned above, this is not uncommon, because for most generic images are intended for non-desktop uses that `C.UTF-8` suffices, but I can raise a PR to add this to our custom debian images.

**Review by jsvd — APPROVED** [review]
LGTM, great work, glad to see us finally dropping the use of vagrant ❤️

**Comment by dliappis** [comment]
@logstashmachine backport 8.12

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Pull request merged**
