### PR TITLE
Use the timestamp from the original log4j logevent as the timestamp for ...

### PR DESCRIPTION
**Pull request by fdrueke**
...the logstash event

See also: https://groups.google.com/forum/#!topic/logstash-users/JGr8zXcJ5RY

### CODE REVIEW

**Comment by fmeiser** [comment]
Would be great if you can apply this patch.

**Comment by chrisjschultz** [comment]
nice trick (dividing by 1000.0) to preserve millis, better than my casting to double gymnastics that I have been doing ;)
Please merge this request, this is quite a nasty defect.

**Comment by jordansissel** [comment]
I apologize for the extreme delays in reviewing this patch.

If this is still an issue that needs solving, let's move this patch to the new plugin repo (http://github.com/logstash-plugins/logstash-input-log4) and we can discuss further.

Additionally, I haven't looked at the code so I don't have comments there, but I don't see a signed cla on file for the author.

**Comment by wiibaa** [comment]
@jsvd @jordansissel an equivalent implementation is now part of the log4j plugin, so this PR could be closed as obsolete. Thanks

**Comment by jordansissel** [comment]
Yeah if this is still an issue, let's move the PR to https://github.com/logstash-plugins/logstash-input-log4j/

:Heart:

**Pull request closed without merging**
