### PR TITLE
fix jruby bigdecimal handling in Time.at

### PR DESCRIPTION
**Pull request by colinsurprenant**
required to pass specs under #5023

### CODE REVIEW

**Comment by andrewvc** [comment]
LGTM

**Comment by talevy** [comment]
should this also make its way into master?

**Comment by talevy** [comment]
LGTM

**Comment by colinsurprenant** [comment]
@talevy yes, actually everywhere. master, 2.* 5.*

**Comment by colinsurprenant** [comment]
rebasing & merging

**Comment by colinsurprenant** [comment]
merged into 2.x, 2.3, 2.2 and 5.0

**Comment by colinsurprenant** [comment]
merged into master

**Pull request merged**
