### PR TITLE
Add a retry mechanism around the integration test for the es ouput

### PR DESCRIPTION
**Pull request by ph**
Fix: #6959

### CODE REVIEW

**Comment by suyograo** [comment]
Does a `try` block retry until all `expect` statements are successful?

**Comment by ph** [comment]
@suyograo yes, it will retry until all the expection are successful.

**Comment by suyograo** [comment]
LGTM

**Comment by colinsurprenant** [comment]
For my education, is there a limit to the retries with the rspec `try` block?

**Comment by ph** [comment]
@colin it default to 5 https://github.com/elastic/logstash-devutils/blob/master/lib/logstash/devutils/rspec/logstash_helpers.rb#L14

**Comment by ph** [comment]
I will kill this PR, I believe its another issue than just that.

**Pull request closed without merging**
