### PR TITLE
Version-independent license check

### PR DESCRIPTION
**Pull request by danhermann**
The license check tool no longer considers different versions of a dependency to be distinct. This makes it easier to accommodate frequently-updated dependencies.

One functional difference as a consequence of this change is that while the license mapping file still accepts multiple version entries for a single dependency, all entries for a given dependency must have the same license specification since the version can no longer be used when matching against identified dependencies. Should a conflicting license specification be found for any dependency, the license check tool will flag it and abort.

### CODE REVIEW

**Comment by danhermann** [comment]
Jenkins, test this please

**Comment by jsvd** [comment]
@danhermann do you mind splitting off this commit into code changes and notice file changes? it will make it easier to merge across branches

**Comment by danhermann** [comment]
Jenkins, test this please

**Comment by danhermann** [comment]
The notice file changes for 6.8 are here: https://github.com/elastic/logstash/pull/11101

**Comment by jsvd** [comment]
LGTM merged this as 1d7df01df
took 6 months, but we got there :D thanks @danhermann

**Pull request closed without merging**
