### PR TITLE
First Logstash project level cleanup and code organization

### PR DESCRIPTION
**Pull request by purbon**
This is mostly a housekeeping PR, including a few relocations and some old scripts being delated (not used anymore). The main benefit here is to have cleaner first level, including cleaning up a bit the current dir layout.

### CODE REVIEW

**Comment by purbon** [comment]
@ph @suyograo your thoughts here are welcome.

**Comment by suyograo** [comment]
nice. thanks for the cleanup. What about nuking `LS_HOME/bot` and  `LS_HOME/tools`? @jordansissel any reason to keep `tools` around? hasn't been updated in years

**Comment by suyograo** [comment]
also https://github.com/elastic/logstash/blob/master/.tailor. been stale for 4 years!

**Comment by purbon** [comment]
@suyograo I decided to keep tools as it have inside now:

* benchmarks: the small tool that @ph added to run micro benchmarks.
* ca: our custom CA files for the windows bug in rubygems (the only thing that is not really a tool)
* check_pull_changelog.rb: The scrip that was inside bot, not sure who uses this and how to use it, according to the commit history, it was added by @wiibaa a long time ago.

> .tailor been stale for 4 years!

I remove it in https://github.com/elastic/logstash/pull/5268/commits/105db3797ff9a0dc21d3614af38f2e29b882b151

happy to clean up and organize more stuff. I love PR's with more red than green 👍 

- purbon

**Comment by jsvd** [comment]
awesome pr!
tests run, LGTM

**Comment by jsvd** [comment]
maybe hold off merging until we get a response for https://github.com/elastic/logstash/pull/5268#issuecomment-218373982?

**Comment by suyograo** [comment]
@purbon lets remove `check_pull_changelog.rb` and `bot`. we can always add it back to `tools` if @wiibaa is still using it

**Comment by purbon** [comment]
@suyograo done

**Comment by suyograo** [comment]
LGTM

**Comment by jordansissel** [comment]
+1 I haven't used anything in tools or bot in a while

**Comment by wiibaa** [comment]
@purbon @suyograo  bot was an experiment in the old days to automate some pull request checks  when Jordan was the single maintainer. Now that elastic-bot(jarvis), the split in plugins,the Community Maintainer Guide and the "LGTM" by the core team this can be removed indeed :smile:

**Comment by suyograo** [comment]
@wiibaa awesome. Thanks for the explanation!

**Pull request closed without merging**
