### PR TITLE
Doc: Add SNMP integration to breaking changes

### PR DESCRIPTION
**Pull request by karenzone**
Reference: https://www.elastic.co/guide/en/logstash/master/plugins-integrations-snmp.html
Fixes: #16373

**PREVIEW:** https://logstash_bk_16374.docs-preview.app.elstc.co/guide/en/logstash/master/breaking-changes.html

### CODE REVIEW

**Review by edmocosta — APPROVED** [review]
LGTM

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by karenzone** [comment]
12434 (or sooner)

**Comment by karenzone** [comment]
@logstashmachine backport 8.15

**Pull request merged**
