### PR TITLE
added snmptrap v2c output

### PR DESCRIPTION
**Pull request by DanielRedOak**
Added a working implementation of a snmp v2c trap.

### CODE REVIEW

**Comment by DanielRedOak** [comment]
Someone mind moving this to logstash-output-snmptrap or the like?  Would love to see this exist still :smiley:

**Comment by purbon** [comment]
Moin moin, I think this would be a good complement to  https://github.com/logstash-plugins/logstash-input-snmptrap, @DanielRedOak how do you feel about having this move to logstash-plugins? I you are still ok, I can create a new repo for you and then you can move this code as a PR there. Makes sense to you?

**Comment by DanielRedOak** [comment]
@purbon that sounds great

**Comment by suyograo** [comment]
Please move this to a new [plugin](https://www.elastic.co/guide/en/logstash/current/contributing-to-logstash.html) if there is still interest.

**Pull request closed without merging**
