### PR TITLE
Doc: Fix java filter example unit test code link

### PR DESCRIPTION
**Pull request by occidere**
## What does this PR do?

- Fix the link of test code for Java filter plugin example docs

## Why is it important/What is the impact to the user?

- Many people follow official documents when developing logstash plugin
- But there is an incorrect link in java filter example's test code docs
-  So, it must be fixed to correct link to make others developing easily

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files (and/or docker env variables)
- [x] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- None

## How to test this PR locally

- Simply click the link and check it whether leading the correct example code or not

## Related issues

- None

### CODE REVIEW

**Comment by logstashmachine** [comment]
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

**Review by kares — APPROVED** [review]
good catch!

**Comment by kares** [comment]
@occidere in general we target the `master` branch and than back-port docs fixes to `7.x` and branches such as `7.14`
do you think you could re-target the PR? if not that is fine as well - we might try doing so on our own ...

**Comment by occidere** [comment]
@kares 
Alright, I'll create new PR (`occidere:master` -> `elastic:master`) after close this.
Is it good to proceed?

**Comment by kares** [comment]
oh right, yeah I think we want to cherry-pick that commit to `7.x` / `7.14`

**Comment by occidere** [comment]
Yup, that'll be good. Please, change anything if needed. I totally rely on your decision :)

**Comment by kares** [comment]
Opened https://github.com/elastic/logstash/pull/13123 and https://github.com/elastic/logstash/pull/13124, thanks for bringing this up!

**Pull request closed without merging**
