### PR TITLE
Update lock file to use 1.5.3 version

### PR DESCRIPTION
**Pull request by suyograo**

### CODE REVIEW

**Comment by colinsurprenant** [comment]
LGTM LGTM
:shipit:

**Comment by colinsurprenant** [comment]
do we know why the `rack` gem is not required anymore?

**Comment by suyograo** [comment]
@colinsurprenant re:rack https://github.com/puma/puma/commit/537bc21593182cd9c4c0079a3936d05b1f91fe14

**Comment by colinsurprenant** [comment]
peeeeeerrrrrfect, thanks.

**Pull request closed without merging**
