### PR TITLE
 #7784 Cleanup Metric Collection in Benchmarks

### PR DESCRIPTION
**Pull request by original-brownbear**
Just some cleanup of compiler warnings and duplication to prepare for introducing optional ES output in #7784.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@jakelandis @suyograo so I was going to implement the ES output real quick this morning, but I wanted to run an idea by you guys first (PR here is just some cleanup to be able to implement this in 30min).

How about this for an instant win on ES integration + gathering more stats:

* just add an optional flag `--elasticsearch=127.0.0.1:9200`
   * If the flag is set, we (in addition to collecting the few quick metrics we currently extract from the JSON) simply start appending all raw JSON strings we get to a log, enriching each entry with the timestamp of its collection and the timestamp of the start of the benchmark run.
* After the run is over, we simply ship the raw JSON metric values straight to ES.

Then we can do whatever analysis we want on them right away and have all the other stats about GC and memory and all that in a nice time-series.
There isn't really much point in implementing further analysis in this tool then is there, much better to leverage ES here right?

**Comment by suyograo** [comment]
> just add an optional flag --elasticsearch=127.0.0.1:9200
If the flag is set, we (in addition to collecting the few quick metrics we currently extract from the JSON) simply start appending all raw JSON strings we get to a log, enriching each entry with the timestamp of its collection and the timestamp of the start of the benchmark run.

@original-brownbear this sounds good to me. Nit pick: I would make the flag `--elasticsearch-export`=http://127.0.0.1:9200` :) Make sure you can take the full URL here with basic auth as well..

Also, the only system stat that would be really useful in the terminal output would be CPU usage. Anything else can go in the advanced stat collection which as you suggested is enabled by default when `--elasticsearch-export` is used.

**Comment by suyograo** [comment]
LGTM.

**Comment by original-brownbear** [comment]
@suyograo alright sounds good, merging this one then and implementing in the next PR (probably later today :))

**Pull request closed without merging**
