### PR TITLE
[WIP] feature/persistent_queue

### PR DESCRIPTION
**Pull request by colinsurprenant**
make sure to run `rake bootstrap` first. 

when you run logstash the following queue files will be created:
```
filter_to_output_queue
filter_to_output_queue.0
input_to_filter_queue
input_to_filter_queue.0
```
`filter_to_output_queue` is the metadata file and `filter_to_output_queue.0` is the paged data file.

for now most of the code lives in:
- https://github.com/colinsurprenant/jruby-mmap
- https://github.com/colinsurprenant/jruby-mmap-queues

### CODE REVIEW

**Comment by hmrm** [comment]
What's the status on this?

**Comment by suyograo** [comment]
@hmrm this feature was moved out of LS 1.5...we are targeting this to the next release (2.x)

**Comment by hmrm** [comment]
Thanks!

**Comment by robertsmarty** [comment]
Will this be available in Logstash 2.0.0? Currently losing syslogs when logstash queues internally. Hoping this will solve the problem.

**Comment by suyograo** [comment]
@robertsmarty this is definitely on our [roadmap](https://www.elastic.co/guide/en/logstash-roadmap/current/index.html), but not in the 2.0 release. We had to move our next release from 1.6 to 2.0 as we described [here](https://www.elastic.co/blog/logstash-2-0-0-beta1-released). These features will land in releases post 2.0

**Pull request closed without merging**
