### PR TITLE
Rename bin/plugin to bin/logstash-plugin

### LINKED ISSUE #4871: Create bin/logstash-plugin to replace bin/plugin
## Intro
Starting in 5.0, we want to align the plugin managers across the Elastic stack. This has (at least) two goals - having a consistent syntax and behavior for installing extensions (plugins) across the Elastic Stack, and to introduce the concept of "Packs" - a single zip that contains 0 or 1 plugin for each system.

## Packs 
Packs is more than just a plugin for a specific system, and extends the whole stack, rather than making a single extension for a single system. A pack is a zip that contains 0 or 1 plugins for each of Elasticsearch, Logstash, Kibana. Since LS uses RubyGems to host plugins, and is heavily based on gem infrastructure, we'll continue to support RubyGems and existing plugins in addition to new packs.

## Common interface to install Packs and Plugins
The plugin manager should support both packs and plugins. 

`bin/plugin <plugin>` which is the current way of install packs/plugins is problematic because it pollutes the global namespace if it is put in the path. Users had already raised this issue (https://github.com/elastic/logstash/issues/3498). Also, for v5.0 when there exists a central script to install pack, each component should automatically pick the pack from download.elastic.co and install it. See https://www.elastic.co/v5

## Proposed Change

```
bin/logstash-plugin.sh install <pack name or plugin> 
```

## Examples

```
bin/logstash-plugin.sh install x-pack-5.1
```

```
bin/logstash-plugin.sh install logstash-output-pagerduty
```

The plugin manager will continue to support `remove` and `list`.

## Plan

Deprecate `bin/plugin` in 2.3.0 and remove it in 5.0.0-alpha1 in favor of `bin/logstash-plugin`. This behavior will make it consistent with [Elasticsearch](https://github.com/elastic/elasticsearch/pull/16454) and [Kibana](https://github.com/elastic/kibana/pull/6252).

### PR DESCRIPTION
**Pull request by suyograo**
This adds support for packs and fixes the problem where bin/plugin
pollutes the PATH namespace

Fixes #4871

### CODE REVIEW

**Comment by suyograo** [comment]
All tests pass, even the rake:integration ones which have the plugin tests

**Comment by purbon** [comment]
Hi, to be consistent with the issue, we should have used ```bin/logstash-plugin.sh``` as script name, this could be done just wrapping the actual `logstash-plugin`, what do you think?

**Comment by purbon** [comment]
@suyograo `rake test:integration:local` fails due to `./integration/plugin_manager/plugin_update_spec.rb` not being properly updated to use the new plugin command.

**Comment by purbon** [comment]
Do we have to update also reference in:

```
skywalker% grep -rn "bin/plugin" docs 
docs/static/breaking-changes.asciidoc:26:`bin/plugin install --version 1.5.x logstash-output-elasticsearch_java`
docs/static/breaking-changes.asciidoc:28:`bin/plugin install --version 2.0.0 logstash-output-elasticsearch_java`
```

**Comment by purbon** [comment]
`bin/plugin.bat` should be renamed too.

**Comment by suyograo** [comment]
@purbon I checked Elasticsearch alpha1 release, and they use `bin/elasticsearch-plugin` not `bin/elasticsearch-plugin.sh`.

See 

```
suyog@machine:/tmp/elasticsearch-5.0.0-alpha1$ ls -lrt bin/
total 656
-rw-r--r--  1 suyog  wheel    6480 Mar 21 02:29 service.bat
-rwxr-xr-x  1 suyog  wheel    2951 Mar 21 02:29 elasticsearch.in.sh
-rw-r--r--  1 suyog  wheel    3434 Mar 21 02:29 elasticsearch.in.bat
-rw-r--r--  1 suyog  wheel     916 Mar 21 02:29 elasticsearch.bat
-rwxr-xr-x  1 suyog  wheel     221 Mar 21 02:29 elasticsearch-systemd-pre-exec
-rw-r--r--  1 suyog  wheel   80896 Mar 21 02:29 elasticsearch-service-x86.exe
-rw-r--r--  1 suyog  wheel  103936 Mar 21 02:29 elasticsearch-service-x64.exe
-rw-r--r--  1 suyog  wheel  104448 Mar 21 02:29 elasticsearch-service-mgr.exe
-rw-r--r--  1 suyog  wheel    1297 Mar 21 02:29 elasticsearch-plugin.bat
-rwxr-xr-x  1 suyog  wheel    2985 Mar 21 02:29 elasticsearch-plugin
-rwxr-xr-x  1 suyog  wheel    5268 Mar 21 02:29 elasticsearch
```

**Comment by suyograo** [comment]
@purbon updated. 

Also, no need to update `breaking-changes.asciidoc` since it is effective for old version of LS (< 5.0)

**Comment by purbon** [comment]
:+1: on https://github.com/elastic/logstash/pull/4874#issuecomment-200412840, good we check up to be consistent.

**Comment by purbon** [comment]
LGTM

**Pull request closed without merging**
