### PR TITLE
Revert "MINOR: Adjust Ruby Version File"

### PR DESCRIPTION
**Pull request by jakelandis**
This reverts commit 3b545b261d3052e555466c2cc27abbb1ea96c389.

The build system still needs to use .12 due some issues we found with clean environments and rake bootstrap and JRuby 9.1.13.0

### CODE REVIEW

**Comment by jakelandis** [comment]
Note - this should be blocked till Jenkins passes since some changes there are needed there too.

**Comment by original-brownbear** [comment]
@jakelandis sort of annoying but makes sense :) => LGTM

**Comment by jakelandis** [comment]
Root cause of why this needs to be reverted : https://github.com/elastic/logstash/issues/8220

**Comment by jakelandis** [comment]
Reverts PR: https://github.com/elastic/logstash/pull/8165

**Pull request closed without merging**
