### PR TITLE
Update log4j dependencies

### PR DESCRIPTION
**Pull request by robbavey**

### CODE REVIEW

**Review by jsvd — APPROVED** [review]
Tested locally and LGTM, please merge after CI finishes

**Review by jsvd — CHANGES_REQUESTED** [review]
Actually, the license mapping file needs to be updated due to the log4j2 version change:

```
23:32:39 Add complying licenses (using the SPDX license ID from https://spdx.org/licenses) with URLs for the libraries listed below to tools/dependencies-report/src/main/resources/licenseMapping.csv:
23:32:39 "org.apache.logging.log4j:log4j-api:2.15.0"
23:32:39 "org.apache.logging.log4j:log4j-core:2.15.0"
23:32:39 "org.apache.logging.log4j:log4j-slf4j-impl:2.15.0"
```

**Comment by robbavey** [comment]
Up again @jsvd

**Review by jsvd — APPROVED** [review]
The license check test is now passing and the rest of the tests passed in the previous ci run, so LGTM

**Comment by mdennehy** [comment]
Query folks; when are we likely to see 6.8.21 released?

**Comment by zoeller-freinet** [comment]
> Query folks; when are we likely to see 6.8.21 released?

ES and logstash 6.8.21 are released mow:
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-notes-6.8.21.html
https://www.elastic.co/guide/en/logstash/6.8/logstash-6-8-21.html

**Comment by kakoni** [comment]
This still includes logstash-input-http-3.3.7 + logstash-input-beats-5.1.9 
which have dependencies to log4j-api-2.11.1.jar

**Comment by jsvd** [comment]
This is ok, the issue is in log4j-core, and it's the jar in logstash core that is loaded. We can confirm that 6.8.21 won't perform jndi lookups anymore:

```
/tmp/test/6.8.21
❯ cat Dockerfile 
FROM docker.elastic.co/logstash/logstash:6.8.21

# script to test if Logstash is vulnerable https://gist.github.com/jsvd/dbbdca8c309405484401da8223742353#file-script-rb
COPY script.rb /usr/share/logstash

/tmp/test/6.8.21
❯ wget -q https://gist.githubusercontent.com/jsvd/dbbdca8c309405484401da8223742353/raw/156efc98a1eb93dee947115d66da3d1da95acdb5/script.rb

/tmp/test/6.8.21
❯ docker build . -q --rm -t test_6_8_1                                                                                                   
sha256:4fd01f1d967b5e1e00fe075bad13ac21091e27998ad8c62f27951ae754be1250

/tmp/test/6.8.21
❯ docker run test_6_8_1 bin/ruby script.rb
Sending Logstash logs to /tmp/log4j.test.log which is now configured via log4j2.properties
[2021-12-14T11:20:33,086][INFO ][object                   ] ${jndi:ldap://127.0.0.1:2000/obj} {"structured"=>"message"}
[2021-12-14T11:20:34,103][INFO ][object                   ] This instance is NOT vulnerable to JNDI Lookups.
[2021-12-14T11:20:34,105][INFO ][object                   ] Cleaning up leftover log file {:path=>"/tmp/log4j.test.log"}

```

**Comment by jzhao13** [comment]
Hey releases page for 6.8.21 is returning 404, https://www.elastic.co/downloads/past-releases/logstash-6-8-21

**Comment by jzhao13** [comment]
> > Hey releases page for 6.8.21 is returning 404, https://www.elastic.co/downloads/past-releases/logstash-6-8-21
> 
> Returns 200 on my end (the files themselves as well).

Thanks. I just cleaned my cache and it appears.

**Pull request merged**
