### PR TITLE
Force RPM OS to be set to linux. 

### LINKED ISSUE #5147: RPM when built on OSX should target 'linux' not 'darwin'
If you do `rake artifact:rpm` on OSX, you'll get something like this when you try to install:

```
package logstash-1:5.0.0~dev-1.noarch is intended for a darwin operating system```
```

### PR DESCRIPTION
**Pull request by purbon**
Fixes #5147

### CODE REVIEW

**Comment by ph** [comment]
LGTM

**Comment by purbon** [comment]
did you tested the rpm?

**Comment by ph** [comment]
I looked at the code I am building one right now. updated the comment to reflect that.

**Comment by purbon** [comment]
good, me doing the same :-P

**Comment by ph** [comment]
LGTM
Working on Centos 7.1
```
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Examining ./logstash-5.0.0.dev.noarch.rpm: 1:logstash-5.0.0~dev-1.noarch
Marking ./logstash-5.0.0.dev.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package logstash.noarch 1:5.0.0~dev-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================================================================================================================================================================
 Package                                                                 Arch                                                                  Version                                                                      Repository                                                                                 Size
============================================================================================================================================================================================================================================================================================================================
Installing:
 logstash                                                                noarch                                                                1:5.0.0~dev-1                                                                /logstash-5.0.0.dev.noarch                                                                165 M

Transaction Summary
============================================================================================================================================================================================================================================================================================================================
Install  1 Package

Total size: 165 M
Installed size: 165 M
Is this ok [y/d/N]: Y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:logstash-5.0.0~dev-1.noarch                                                                                                                                                                                                                                                                            1/1
  Verifying  : 1:logstash-5.0.0~dev-1.noarch                                                                                                                                                                                                                                                                            1/1

Installed:
  logstash.noarch 1:5.0.0~dev-1

Complete!
[vagrant@localhost vagrant]$
```

**Comment by purbon** [comment]
LGTM, tested with centos-6

**Pull request closed without merging**
