### PR TITLE
Clean up left over scripts after CI migration

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

Following the CI migration from Jenkins to Buildkite, this commit removes a number of left over helper scripts that aren't needed anymore.

## Author's Checklist

Executed the following CI runs using this PR, to ensure nothing is breaking:

- [x] PR checks: https://buildkite.com/elastic/logstash-pull-request-pipeline/builds/843 ✅
- [x] Exhaustive pipeline: https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/217 ✅
- [x] aarch64 pipeline: https://buildkite.com/elastic/logstash-aarch64-pipeline/builds/45 ✅
- [x] Linux JDK matrix pipeline: https://buildkite.com/elastic/logstash-linux-jdk-matrix-pipeline/builds/127 ✅
- [x] Windows JDK matrix pipeline: https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/102 ✅
- [x] DRA snapshot (main): https://buildkite.com/elastic/logstash-dra-snapshot-pipeline/builds/506 ✅

## Related issues

- Closes https://github.com/elastic/ingest-dev/issues/2850

### CODE REVIEW

**Review by andsel — APPROVED** [review]
LGTM

**Comment by dliappis** [comment]
Thank you for the quick review @andsel ! Will merge this first thing on Monday. (I apply a no merge policy for larger things on Fridays :) )

**Review by roaksoax — APPROVED** [review]

**Comment by dliappis** [comment]
@logstashmachine backport 8.12

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Pull request merged**
