### PR TITLE
bump gems for 5.6.9

### PR DESCRIPTION
**Pull request by danhermann**
Supersedes https://github.com/elastic/logstash/pull/9175 as that one had a bad Gemfile.

### CODE REVIEW

**Comment by jakelandis** [comment]
There are two changes that should land in the next patch release that still requires a bit more time. 

* Grok memory leak (5.x only)
* Jackson version bump across core and beats

Can we hold off 1-2 days on this bump to allow for the changes to land ?

**Comment by danhermann** [comment]
@jakelandis, will those changes land this week? I'd like to have all the release issues closed before Elasticon.

**Comment by jakelandis** [comment]
@danhermann - yes all PRs submitted, waiting on reviews.

**Comment by jakelandis** [comment]
@danhermann - would you mind updating the lock file ?  I know have the Jackson changes done across the board, and the grok plugin has been released.

**Comment by danhermann** [comment]
@jakelandis, gems bumped again to pick up grok and beats.

**Comment by jakelandis** [comment]
@danhermann - thanks for holding up the merge.  Changes LGTM.

**Pull request merged**
