### PR TITLE
bump versions for next 5.6 release

### PR DESCRIPTION
**Pull request by yaauie**
bumps version variables to 5.6.7 for next 5.6 release

### CODE REVIEW

**Comment by jakelandis** [comment]
LGTM (assuming Gemfile .lock coming soon...)

**Comment by yaauie** [comment]
jenkins test this again please

**Comment by yaauie** [comment]
jenkins test this please

**Comment by yaauie** [comment]
prior integration test failure looks to be unrelated; I've seen this particular test be a bit flappy in the past and will file a follow-up ticket if the rebuild succeeds
~~~
22:59:15 Failures:
22:59:15 
22:59:15   1) Test Dead Letter Queue using logstash.yml and separate config file behaves like it can send 1000 documents to and index from the dlq should index all documents
22:59:15      Failure/Error: expect(result["hits"]["total"]).to eq(1000)
22:59:15      
22:59:15        expected: 1000
22:59:15             got: 957
22:59:15      
22:59:15        (compared using ==)
22:59:15      Shared Example Group: "it can send 1000 documents to and index from the dlq" called from ./specs/dlq_spec.rb:64
22:59:15      # ./specs/dlq_spec.rb:49:in `(root)'
22:59:15      # ./specs/dlq_spec.rb:47:in `(root)'
~~~

**Comment by yaauie** [comment]
@jakelandis the PR has been updated to include the post-version-bump Gemfile.lock changes too; can you review again?

**Comment by robbavey** [comment]
@yaauie There is already an issue for the DLQ tests - #8142, which I need to get to

**Comment by jakelandis** [comment]
@yaauie - sorry i missed the request for re-review...  LGTM

**Pull request merged**
