### PR TITLE
Missing Command line flags from the documentation

### PR DESCRIPTION
**Pull request by ph**
With the addition of the API we have added 2 options to control the
behavior of the webserver, the port and IP address to bind. This PR add
them to the documentation.

### CODE REVIEW

**Comment by ph** [comment]
When doing a code review I found out that theses options were not in the documentation.

**Comment by purbon** [comment]
@ph test are being dancing funky here, what do you think the reason might be? the mass update?

**Comment by purbon** [comment]
LGTM, is just a doc change.

**Comment by purbon** [comment]
Actually the problem is due to us testing with JDK7 and having some only JDK8 code loaded, changed the PR test to be testing with JDK8 for now.

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
