### PR TITLE
Option to disable SonarQube with Java Tests

### PR DESCRIPTION
**Pull request by dliappis**
## Release notes
[rn:skip]

## What does this PR do?

This commit introduces a way to optionally disable SonarQube scanning and coverage reports when running Java unit tests.

Disabling can be achieved by setting the env var `ENABLE_SONARQUBE` to `false`.

## Why is it important/What is the impact to the user?

The integration was introduced in #15279, however, there are cases (e.g. running Java unit tests outside of PRs) where we don't want this integration.

## Checklist

- ~~[ ] My code follows the style guidelines of this project~~
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- [x] I have added tests that prove my fix is effective or that my feature works

## How to test this PR locally

```shell
ci/unit_tests.sh java
```
should fail by default as it expects sonarqube credentials.

```shell
export ENABLE_SONARQUBE=false
ci/unit_tests.sh java
```

should succeeed.

We will also test this with Buildkite as it allows defining env vars.

## Related issues

- https://github.com/elastic/logstash/pull/15279
- https://github.com/elastic/ingest-dev/issues/1724#issuecomment-1767984852

### CODE REVIEW

**Comment by dliappis** [comment]
@logstashmachine backport 8.10

**Review by robbavey — APPROVED** [review]
LGTM

**Comment by dliappis** [comment]
@logstashmachine backport 8.10

**Comment by dliappis** [comment]
@logstashmachine backport 7.17

**Comment by dliappis** [comment]
@logstashmachine backport 8.10

**Comment by dliappis** [comment]
This PR will only be backported to `8.11` since the integration work: https://github.com/elastic/logstash/pull/15279 only landed in `main` and is now part of `8.11` only.

**Pull request merged**
