### PR TITLE
Code cleanup for the collector observer

### PR DESCRIPTION
**Pull request by ph**
We have more the responsability of watching the collector inside the
input itself, this feature might come back when we have a new execution
model that can be improved in watching metrics. But this would require
more granular watchers.

No tests were affected by this changes since the code that required that
features was already removed.

Fixes: #6447

### CODE REVIEW

**Comment by suyograo** [comment]
@ph I don't see where we are providing a way for consumers to use a different polling interval? I thought there would be a register_listener method or something that takes polling interval and other params.

**Comment by ph** [comment]
@suyograo I thought we were reversing the responsability and make the input responsable of creating the threads?

**Comment by suyograo** [comment]
LGTM

**Comment by jsvd** [comment]
+5 −47 ❤️ 



LGTM

**Pull request closed without merging**
