### PR TITLE
update bundler to 2.x

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Comment by yaauie** [comment]
That's it? I'm not complaining, but IIRC we relied pretty heavily on Bundler internals for `bin/logstash-plugins` and hit prior conflicts there when Bundler went 2.x, so I'm surprised that the diff is now so small.

It looks like CI didn't get kicked off because the PR was opened as WIP.

Jenkins test this please

**Comment by jsvd** [comment]
I ran some tests locally and it all worked, was surprised as well, so I created this PR to throw it at CI, I didn't realise tests didn't ran on draft prs 😕

**Comment by jsvd** [comment]
> LGTM! Will this be backported?

I was thinking of only merging this to master.

**Comment by jsvd** [comment]
jenkins test this please

**Pull request merged**
