### PR TITLE
Deps: bump lock for 7.15.0

### PR DESCRIPTION
**Pull request by kares**
Generated using 7.14.0's lock file as a base line, **[diff](https://github.com/kares/logstash/commit/1093df1b776e26b620a0b86bd4c675cda2af03cd)**.

- [x] **TODO re-target to 7.15 branch once available!**

## Release notes

[rn:skip]

## What does this PR do?

Updates (gem) dependencies for next minor version (7.15.0) of LS.

### CODE REVIEW

**Comment by kaisecheng** [comment]
Have I misunderstood the flow? You are pushing the lockfile to `7.x` which is a new file. 
This is a minor release, so this lockfile (Gemfile.jruby-2.5.lock.release) is for `7.15` branch. 
For the `7.x`, the core version bump to `7.15`

**Comment by kares** [comment]
@kaisecheng correct we just haven't created the **7.15** branch yet - there's a TODO in the desc to re-target

**Review by kaisecheng — APPROVED** [review]
LGTM. thank you 💟

**Comment by kaisecheng** [comment]
need to double check the red CI.

**Comment by kares** [comment]
hmm, branch was cut off 7.x but still got:
```
08:27:59 BUILD FAILED in 8s
08:27:59 "faraday-em_synchrony:1.0.0"
08:27:59 "faraday-excon:1.1.0"
08:27:59 "faraday-httpclient:1.0.1"
08:27:59 "faraday-net_http:1.0.1"
08:27:59 "faraday-net_http_persistent:1.2.0"
08:27:59 "faraday-patron:1.0.0"
08:27:59 "faraday-rack:1.0.0"
08:27:59 "ruby2_keywords:0.0.5"
08:27:59 The following NOTICE.txt entries are missing, please add them:
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-em_http-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-em_synchrony-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-excon-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-httpclient-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-net_http-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-net_http_persistent-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-patron-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/faraday-rack-NOTICE.txt
08:27:59 LS_HOME/tools/dependencies-report/src/main/resources/notices/ruby2_keywords-NOTICE.txt
```
... believe the base branch should have included: https://github.com/elastic/logstash/commit/84dbf3e310659f9dde81a1942a132810f4279d0b as fix for these

**Comment by kares** [comment]
merged with 7.15 manually - waiting for CI

**Pull request merged**
