### PR TITLE
Introduces basic logging back

### LINKED ISSUE #4575: Implement basic logging in the api
The current implementation of the logging inside the api is not linked with the default cabin logger and it basically does is own thing. We need to fix that to use the default configured log output and log level. There is no reason to have a separate logger for this part of the application and this will make things a lot easier to tests.

**What should be logged?**

- All errors generated from system calls should be catch.
- Errors shouldn't bring down logstash
- Sinatra errors should show up in the logs.

**What should not be logged?**
- Access logs (apache like log) shouldnt not be saved.

### PR DESCRIPTION
**Pull request by purbon**
Introduce basic logging, including basic access logging. This PR introduces basic access and error logging, booths serve the purpose of knowing:

* When something goes wrong, why it's going wrong (aka exception and error handling).
* Know usage of resources, including status code monitoring.

Fixes #4575 and supersede #4617 by poiting it to the new_metrics branch.

### CODE REVIEW

**Comment by purbon** [comment]
@ph @jsvd this is the up to date PR vs the new branch, happy to see what do you think guys? keep in mind for testing this answers now to 9292 port.

**Comment by ph** [comment]
I have found two issue with this PR.

We currently see the access log in the log, can we only return errors/exception like described in #4574? This could add a lot of noise in the log from automated scripts. We can implement it later like as an option see issue #4576
```
{:timestamp=>"2016-02-05T09:33:17.109000-0500", :message=>"0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:33:17 -0500] \"GET / HTTP/1.1\" 200 85 0.0420\n"}
{:timestamp=>"2016-02-05T09:33:17.929000-0500", :message=>"0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:33:17 -0500] \"GET /favicon.ico HTTP/1.1\" 404 18 0.0040\n"}
{:timestamp=>"2016-02-05T09:34:26.540000-0500", :message=>"0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:34:26 -0500] \"GET /_stats HTTP/1.1\" 200 33 0.0060\n"}
```

Also if I start logstash with the following command `bin/logstash -e "" --log hello.log` I will get the access log in two places in the terminal where I started logstash and in the log file?

**Comment by purbon** [comment]
@ph I know it also adds the access logs, I added this because it was easier to archive through using common rack logger, and actually give a lot of nice information that people can use to monitor the usage of the apis himself. So I think we should keep it.

to answer your question, it basically call push to the logger, so it will output everything to all outputs cabin got registered. Are your expectations somehow different.

**Comment by ph** [comment]
> to answer your question, it basically call push to the logger, so it will output everything to all outputs cabin got registered. Are your expectations somehow different.

Well my expectations are not different, but I believe there is a bug since I was not seeing all the logs in the terminal, only the access log and some rubydebug I was testing.

Output in the terminal.
```
sdfs
{
    "@timestamp" => 2016-02-05T14:32:49.737Z,
      "@version" => "1",
          "host" => "sashimi",
       "message" => "sdfs",
          "type" => "stdin"
}
0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:33:17 -0500] "GET / HTTP/1.1" 200 85 0.0420
0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:33:17 -0500] "GET /favicon.ico HTTP/1.1" 404 18 0.0040
0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:34:26 -0500] "GET /_stats HTTP/1.1" 200 33 0.0060
```

Output in our log.
```
{:timestamp=>"2016-02-05T09:33:17.109000-0500", :message=>"0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:33:17 -0500] \"GET / HTTP/1.1\" 200 85 0.0420\n"}
{:timestamp=>"2016-02-05T09:33:17.929000-0500", :message=>"0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:33:17 -0500] \"GET /favicon.ico HTTP/1.1\" 404 18 0.0040\n"}
{:timestamp=>"2016-02-05T09:34:26.540000-0500", :message=>"0:0:0:0:0:0:0:1 - - [05/Feb/2016:09:34:26 -0500] \"GET /_stats HTTP/1.1\" 200 33 0.0060\n"}
```

Different format, one in a hash structure, the other is pure stdout.

**Comment by purbon** [comment]
At my understnding, we pass the logger instance (aka Cabin) to RackCommonLogger at https://github.com/elastic/logstash/pull/4635/files#diff-d864d0ef3a1d5aa82410a27e93c80a65R26

then rack commonlogger is going to send to cabin whatever he things to log, for sinatra access logs ... how internally cabin is doing that i don't think is a blame to sintra, should be something the we misunderstand in cabin.

**Comment by purbon** [comment]
@ph access logging has been removed with the last commit.

**Comment by ph** [comment]
Tested a 1 / on the "root" ressource and I only see the error in the logfile now +1
It is possible to add a bit more context to the error to help us with the upcoming bugs report will get?

Stacktrace, url called, params? Without theses informations this will be really complicated to find the issues and fix it. Its the only thing missing for a lgtm

**Comment by purbon** [comment]
@ph I would not add the stacktrace, might be too much info

**Comment by purbon** [comment]
@ph well I amend myself, I would add only a very small of it.

**Comment by ph** [comment]
Discussed with @purbon And the current message LGTM.

**Pull request closed without merging**
