### PR TITLE
[DOC] precedence between environment variables and yml in docker

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Review by andsel — CHANGES_REQUESTED** [review]
There is an `are` that doesn't fit as per comment https://github.com/elastic/logstash/pull/12198/files#r474645544

**Review by andsel — APPROVED** [review]
LGTM

**Comment by jsvd** [comment]
@logstashmachine backport 8.1

**Comment by jsvd** [comment]
@logstashmachine backport 7.17

**Pull request merged**
