### PR TITLE
bump to 5.0.0.dev

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Comment by ph** [comment]
LGTM

**Comment by jordansissel** [comment]
Jenkins failed - http://build-eu-00.elastic.co/job/Logstash_PR/2354/console

Snippet of output:

```
Plugin not found, aborting
rake aborted!
Could not find gem 'logstash-core (= 3.0.0.dev) java' in source at ./logstash-core.
Source contains 'logstash-core' at: 5.0.0.dev
```

**Comment by jsvd** [comment]
It's normal, it will fail until we generate logstash-core and logstash-core-event-java gems for 5.0.0.dev

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
