### PR TITLE
Since concurrent-ruby 0.9.2 this patch isnt necessary.

### LINKED ISSUE #4141: concurrent-ruby gem pin is not precise enough
```
# From a plugin
% bundle exec rspec
RuntimeError: Logstash expects concurrent-ruby version 0.9.1 and version 0.9.2 is installed, please verify this patch: /Users/
jls/.rvm/gems/jruby-1.7.22/gems/logstash-core-2.0.0-java/lib/logstash/patches/silence_concurrent_ruby_warning.rb
```

The problem is that `bundle install` fetched 0.9.2 because our dependency on `~> 0.9.1` and our concurrent ruby warning thingy patch barfs if we are using anything but 0.9.1

### PR DESCRIPTION
**Pull request by ph**
The team behind concurrent ruby will now support JDK 7 in the 1.x
release

Fixes #4141

### CODE REVIEW

**Comment by purbon** [comment]
@ph error in CI report

```
Please report a bug if this causes problems.
rake aborted!
LoadError: no such file to load -- logstash/patches/silence_concurrent_ruby_warning
/home/jenkins/workspace/Logstash_PR/lib/logstash/patches.rb:6:in `(root)'
/home/jenkins/workspace/Logstash_PR/lib/logstash/environment.rb:1:in `(root)'
/home/jenkins/workspace/Logstash_PR/lib/logstash/environment.rb:114:in `(root)'
/home/jenkins/workspace/Logstash_PR/vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.18-java/lib/logstash/devutils/rspec/spec_helper.rb:1:in `(root)'
/home/jenkins/workspace/Logstash_PR/vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.18-java/lib/logstash/devutils/rspec/spec_helper.rb:16:in `(root)'
/home/jenkins/workspace/Logstash_PR/spec/spec_helper.rb:1:in `(root)'
```

**Comment by purbon** [comment]
forgotten require to be removed.

**Comment by ph** [comment]
rebased with the require.

**Comment by purbon** [comment]
code LGTM, waiting for Jenkins to be happy.

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
LGTM

@ph :shipit: ^ 100k

**Pull request closed without merging**
