### PR TITLE
pin logstash-output-elasticsearch to 6.x

### PR DESCRIPTION
**Pull request by jsvd**
fixes https://github.com/elastic/logstash/issues/6986

### CODE REVIEW

**Comment by ph** [comment]
@jsvd should  we update the lock file also?

**Comment by ph** [comment]
nevermind its already set to 6.3. https://github.com/elastic/logstash/blob/5.4/Gemfile.jruby-1.9.lock#L427

**Comment by jsvd** [comment]
after further investigation, I think logstash 5.4 should be allowed to upgrade to 7.x at will, the actual problem is described in https://github.com/elastic/logstash/issues/6986#issuecomment-297743327
@ph what do you think of fixing the es output and closing this issue?

**Comment by ph** [comment]
@jsvd I also agree that we need to fix the es output 7.x to make sure its installable in Logstash. 2, we need to make sure the x-pack doesn't ship with that version if we ship logstash with 6.x.

**Pull request closed without merging**
