### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ebuildy**
Not sure "logstash" gem exists, right?

### CODE REVIEW

**Comment by andrewvc** [comment]
Thanks for the patch @ebuildy . I'm thinking we need to fix this page further, it should recommend the `logstash-plugin-api` gem really.

**Comment by ebuildy** [comment]
ha! Also,  the versionning of this gem is not clear at all (where as elastic has just aligned all products to same version), and what is doing really:

https://github.com/elastic/logstash/tree/master/logstash-core-plugin-api

?

**Comment by ebuildy** [comment]
very nice!

I am not a ruby developper, and I found very hard the way to build a logstash plugin, especially as soon as we need extra Java libraries etc...

**Comment by kares** [comment]
still an issue (in latest 7.x docs) but since the repo is gone we need to address this in a new PR

**Pull request closed without merging**
