### PR TITLE
Validate deprecated/obsolete options after sanitization

### PR DESCRIPTION
**Pull request by andrewvc**
The old order made no sense since Password / SafeURI objects were not wrapped in their to_s suppressing containers.

This ensures we always log the wrapped values (passwords as password=><password> instead of the plaintext)

### CODE REVIEW

**Comment by original-brownbear** [comment]
@andrewvc seems we have a non-transient spec failure here:

```sh
 1) LogStash::Config::Mixin obsolete settings when using an obsolete setting should cause a configuration error
22:52:32          Failure/Error:
22:52:32            expect {
22:52:32              plugin_class.new("foo" => "hello")
22:52:32            }.to raise_error(LogStash::ConfigurationError)
22:52:32          
22:52:32            expected LogStash::ConfigurationError but nothing was raised
22:52:32          # ./logstash-core/spec/logstash/config/mixin_spec.rb:301:in `block in (root)'
22:52:32          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
22:52:32          # ./lib/bootstrap/rspec.rb:13:in `<main>'
22:52:32 
22:52:32       2) LogStash::Config::Mixin obsolete settings when using an obsolete settings from the parent class should cause a configuration error
22:52:32          Failure/Error:
22:52:32            expect {
22:52:32              plugin_class.new("debug" => true)
22:52:32            }.to raise_error(LogStash::ConfigurationError)
22:52:32          
22:52:32            expected LogStash::ConfigurationError but nothing was raised
22:52:32          # ./logstash-core/spec/logstash/config/mixin_spec.rb:309:in `block in (root)'
22:52:32          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
22:52:32          # ./lib/bootstrap/rspec.rb:13:in `<main>'
22:52:32 
22:52:32     Finished in 4 minutes 59.5 seconds (files took 12.56 seconds to load)
22:52:32     2740 examples, 2 failures, 4 pending
22:52:32 
22:52:32     Failed examples:
22:52:32 
22:52:32     rspec ./logstash-core/spec/logstash/config/mixin_spec.rb:300 # LogStash::Config::Mixin obsolete settings when using an obsolete setting should cause a configuration error
22:52:32     rspec ./logstash-core/spec/logstash/config/mixin_spec.rb:308 # LogStash::Config::Mixin obsolete settings when using an obsolete settings from the parent class should cause a configuration error
22:52:32 
22:52:32     Randomized with seed 14032
```

**Comment by andrewvc** [comment]
please test this

**Comment by andrewvc** [comment]
@original-brownbear weirdly this spec failure happens with `gradlew rubyTests` but not with `bin/rspec`

**Comment by andrewvc** [comment]
Actually, NM, my bad. Found the issue, pushed a new commit.

**Comment by original-brownbear** [comment]
Jenkins test this please (tests are stuck some are red, looks like it might be Jenkins fault though)

**Comment by original-brownbear** [comment]
@andrewvc hmm no seems to still go red every time.

**Pull request closed without merging**
