### PR TITLE
Allow default value for sprintf interpolation

### LINKED ISSUE #4416: Default value for sprintf interpolation (Feature)
In a lot places, Logstash allows to reference fields with the *sprintf format*(https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#sprintf). Unfortunately if the referenced field does not exist, *sprintf* defaults to leave the the reference untouched, which may lead to very unsatisfactory results. Therefore I suggest to allow a default value for the sprintf interpolation, e.g.

    output {
      file {
        path => "/var/log/%{type:-default}.%{+yyyy.MM.dd.HH}"
      }
    }

As delimiter between the field reference and the default value I suggest `:-` (taken from bash, unlikely to exist in a Logstash event field name).

### PR DESCRIPTION
**Pull request by breml**
Important thing is to agree on `KEY_NODE_DEFAULT_DELIMITER`

Closes #4416

### CODE REVIEW

**Comment by suyograo** [comment]
Closing this based on discussion in https://github.com/elastic/logstash/issues/4416. @breml let me know if you disagree :)

Thanks for making Logstash awesome!

**Comment by breml** [comment]
@suyograo I agree in the way that this PR might not be the best solution (from an architecture point of view). But on the other hand I'm not sure if we get somewhere with #4416. The discussion didn't move forward after my last comment on beginning of January.

**Comment by suyograo** [comment]
@breml Excellent. We'll get this reviewed in a week. Trying to close out alpha-1 for 5.0 and 2.3 releases :)

**Comment by breml** [comment]
@suyograo What about this PR? Has this been reviewed yet?

**Comment by boernd** [comment]
What's the status of this PR? Coming any time soon?

**Comment by rptete** [comment]
Hi, i want do this:
      add_field => [ "message", "AutoID=%{autoid}, AutoGUID=%{autoguid}, ServerID=%{serverid}, ReceivedUTC=%{receivedutc}, DetectedUTC=%{detectedutc}, AgentGUID=%{agentguid}, Analyzer=%{analyzer}, AnalyzerName=%{analyzername}, AnalyzerVersion=%{analyzerversion}, AnalyzerHostName=%{analyzerhostname}, AnalyzerIPV4=%{analyzeripv4}, AnalyzerIPV6=%{analyzeripv6}, AnalyzerMAC=%{analyzermac}, AnalyzerDATVersion=%{analyzerdatversion}, AnalyzerEngineVersion=%{analyzerengineversion}, AnalyzerDetectionMethod=%{analyzerdetectionmethod}, SourceHostName=%{sourcehostname}, SourceIPV4=%{sourceipv4}, SourceIPV6=%{sourceipv6}, SourceMAC=%{sourcemac}, SourceUserName=%{sourceusername}, SourceProcessName=%{sourceprocessname}, SourceURL=%{sourceurl}, TargetHostName=%{targethostname}, TargetIPV4=%{targetipv4}, TargetIPV6=%{targetipv6}, TargetMAC=%{targetmac}, TargetUserName=%{targetusername}, TargetPort=%{targetport}, TargetProtocol=%{targetprotocol}, TargetProcessName=%{targetprocessname}, TargetFileName=%{targetfilename}, ThreatCategory=%{threatcategory}, ThreatEventID=%{threateventid}, ThreatSeverity=%{threatseverity}, ThreatName=%{threatname}, ThreatType=%{threattype}, ThreatActionTaken=%{threatactiontaken}, ThreatHandled=%{threathandled}, TheTimestamp=%{thetimestamp}, TenantId=%{tenantid}"]

This works fine, but i must show a clean field when the field doesn't exist in a event, i read that i can with default value:
      add_field => [ "message", "AnalyzerMAC=%{analyzermac:'-'}"]

but this doesnt work for me...

**Comment by kares** [comment]
officially the oldest PR stuck ... anyhow, changes seem no longer relevant due (internal) changes in LS

**Comment by breml** [comment]
@kares Cleaning up is a good thing, but there might be users, who have similar requirements and they end up on this PR. Therefore I suggest to provide some more details, how this can be resolved by using the new capabilities, that the (internal) changes in LS provide. I am the author of this PR but I am not the one, how blocked this PR from being merged or improved. Also the original issue #4416 is still open and as far as I can tell, it is not addressed.

**Comment by kares** [comment]
appreciate you're feedback @breml ... myself only read the original issue's discussion now.
believe the team still did not decide on what to do, myself would lean towards https://github.com/elastic/logstash/issues/4416#issuecomment-477454299 (LS 8)

... going to look into options but will take me a while to be able to make a good architectural decision, anyhow due the Java pipeline rewrite the code presented here got outdated, so we pretty much need to start with a new implementation.

Lucas' work presented here was excellent but there's simply no agreement on #4416 ... yet

**Pull request closed without merging**
