### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/elasticsearch/logstash-contrib | https://github.com/elastic/logstash-contrib 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://www.elastic.co/guide/en/kibana/current/index.html | https://www.elastic.co/guide/en/kibana/current/index.html 
http://www.elastic.co/guide/en/elasticsearch/reference/current/index.html | https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html 
http://www.elastic.co/guide/en/logstash/current/index.html | https://www.elastic.co/guide/en/logstash/current/index.html

### CODE REVIEW

**Comment by wiibaa** [comment]
@ReadmeCritic hoping this message will reach a human. This account need to sign the Elastic CLA for its commits to be eligible for merging. Can you please proceed

**Comment by ReadmeCritic** [comment]
Signed

**Comment by jordansissel** [comment]
@ReadmeCritic I'm still seeing the CLA check fail. If I check our CLA database for the email address that committed this patch (see [the patch](https://patch-diff.githubusercontent.com/raw/elastic/logstash/pull/4200.patch) for the email), it is not found.

**Comment by ReadmeCritic** [comment]
Ah got it

**Comment by ReadmeCritic** [comment]
Signed

**Pull request closed without merging**
