### PR TITLE
Add a micro benchmark runner

### PR DESCRIPTION
**Pull request by ph**
Add `rake benchmark:run` task to run micro benchmark on specific part of
the code, it's uses the benchmark-ips gem to generate them.
See https://github.com/evanphx/benchmark-ips for usage

### CODE REVIEW

**Comment by andrewvc** [comment]
@ph Tested this with the benchmark file below

```ruby
require 'benchmark/ips'

Benchmark.ips do |x|
  x.config(:time => 5, :warmup => 2)

  # These parameters can also be configured this way
  x.time = 5
  x.warmup = 2

  # Typical mode, runs the block as many times as it can
  x.report("addition") { 1 + 2 }
end
```

It worked.

LGTM

**Comment by purbon** [comment]
I like this very much, good idea!!

**Comment by jordansissel** [comment]
Proposal + code LGTM. @andrewvc [tested](https://github.com/elastic/logstash/pull/3457#issuecomment-113655232) it and all looks well.

LGTM :)

**Comment by ph** [comment]
small typo in the commit message i'll update it.

**Comment by andrewvc** [comment]
@ph it might be good to include the example test I posted, just so that people have an idea of how to use this functionality. ¯\_(ツ)_/¯

**Comment by ph** [comment]
yes ^ I'll add my other tests too :)

**Comment by ph** [comment]
I've cleaned the PR a bit, removed the `.gitkeep` added an example test run and fixed the dependencies in the `Gemfile` / `Gemfile*.lock`

**Pull request closed without merging**
