### PR TITLE
 6.2 release notes (undo revert)

### PR DESCRIPTION
**Pull request by jakelandis**
@dedemorton - The original merge seemed to cause an issue with doc build. Can you please assist in troubleshoot why this may have caused a failure. 

This PR re-introduces the reverted commit.

### CODE REVIEW

**Comment by jakelandis** [comment]
Note the content here has already been reviewed via https://github.com/elastic/logstash/pull/9085.

**Comment by jakelandis** [comment]
This looks like the issue:
```
21:46:52 Bad cross-document links:
21:46:52   html/en/logstash/6.2/logstash-6-2-0.html:
21:46:52    - en/logstash/current/keystore.html
21:46:52    - en/logstash/current/plugins-filters-jdbc_static.html
21:46:53 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
```

**Comment by jakelandis** [comment]
@dedemorton - Can you review https://github.com/elastic/logstash/pull/9090/commits/accbe58fbaa5234fd43f24280e08017212c280d0, builds fine locally, and should keep the central build from breaking.

**Comment by dedemorton** [comment]
The link changes LGTM. I'll look at 9044 next...you're right...we do want to merge the two PRs at the same time.

**Comment by jakelandis** [comment]
I removed the link that coupled #9044 to this PR, I will re-add that link to #9044 once this gets merged.

**Pull request closed without merging**
