### PR TITLE
Backport of PR #11541 to 7.7

### PR DESCRIPTION
**Pull request by andsel**
Backport of PR #11541 to 7.7

> Adaptations to internal collector to send data directly to monitoring cluster Close 11573
> 
> Fixes #11541

### CODE REVIEW

**Comment by robbavey** [comment]
Jenkins test this please

**Comment by robbavey** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
@robbavey I've added a commit to this backport that fixed the flaky test. It was due to time format, and this explained the intermittent errors

**Comment by robbavey** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
@robbavey I don't why keep failing on `Failure/Error: "http_address" => stats.get_shallow(:http_address).value,` but that code was already present, before the PR. Do you have any hint why it started failing?
https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-unit/1077/consoleFull

**Comment by robbavey** [comment]
@andsel The `http_address` metric is only populated when the webserver running inside Logstash starts. I suspect there is a race between the webserver starting up and the test being run which expects the `http_address` metric to be present

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
@robbavey I simply added a more long waiting (with timeout) condition on the availability of `:http_address`, is not so nice, but it's on the same model used in the lines above

**Comment by robbavey** [comment]
Jenkins test this please

**Comment by robbavey** [comment]
@andsel Just want to run this through CI another time to make sure we are stable, and not introducing a new flaky test

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
@robbavey I changed the wait condition to look at not throwing exception

**Comment by andsel** [comment]
Yes, we need to port that change also to master, but other PR on master after I've integrated this one on 7.7 :-)

**Comment by andsel** [comment]
Jenkins test this please

**Comment by andsel** [comment]
Jenkins test this please

**Pull request merged**
