### PR TITLE
bump jdk to 11.0.14.1+1

### PR DESCRIPTION
**Pull request by jsvd**
https://www.oracle.com/java/technologies/javase/11-0-14-relnotes.html

### CODE REVIEW

**Comment by yaauie** [comment]
It's a little ironic that we're getting an HTTP 404 in CI when attempting to download version 4.0.4 of a gradle plugin for... downloading?

> ~~~
> 02:48:32       > Could not get resource 'https://plugins.gradle.org/m2/de/undercouch/download/de.undercouch.download.gradle.plugin/4.0.4/de.undercouch.download.gradle.plugin-4.0.4.jar'.
> 02:48:32          > Could not HEAD 'https://plugins.gradle.org/m2/de/undercouch/download/de.undercouch.download.gradle.plugin/4.0.4/de.undercouch.download.gradle.plugin-4.0.4.jar'.
> ~~~

**Comment by jsvd** [comment]
jenkins test this please

**Comment by jsvd** [comment]
@logstashmachine backport 8.0

**Comment by jsvd** [comment]
@logstashmachine backport 8.0

**Comment by jsvd** [comment]
@logstashmachine backport 8.0

**Review by andsel — APPROVED** [review]
LGTM

**Comment by jsvd** [comment]
@logstashmachine backport 8.0

**Comment by jsvd** [comment]
@logstashmachine backport 8.0

**Comment by jsvd** [comment]
@logstashmachine backport 8.0

**Comment by jsvd** [comment]
test

**Comment by kares** [comment]
@logstashmachine backport 8.1

**Comment by robbavey** [comment]
@logstashmachine backport 8.1

**Comment by jsvd** [comment]
@logstashmachine backport 8.1

**Comment by lucabelluccini** [comment]
Do you think there's chance for this to be backported to 7.17?

**Pull request merged**
