### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by cyberplant**

### CODE REVIEW

**Comment by untergeek** [comment]
@cyberplant Thanks for catching the typo.  Please [sign the CLA](https://www.elastic.co/contributor-agreement/) (or inform if you have already) and we'll merge this soon.

**Comment by cyberplant** [comment]
I already did that, but I did after I made the PR. What should I do now?

**Comment by untergeek** [comment]
No worries.  I should be able to look it up manually.

**Comment by untergeek** [comment]
Verified.

**Comment by cyberplant** [comment]
Thanks, @untergeek !

**Pull request closed without merging**
