### PR TITLE
Remove the doc rake task and the documentation generator

### PR DESCRIPTION
**Pull request by ph**
Remove the rake task and the tooling to generate documentation that was inline in the code.
We are now using an asciidoc in the plugin repository.

### CODE REVIEW

**Comment by ph** [comment]
@jakelandis I am aware of the `logstash-docgen` directory I prefer to make a specific PR to remove it, it still useful in some case.

**Comment by ph** [comment]
In retrospec, I can update the README.

**Comment by ph** [comment]
@jakelandis I've decided to it in one PR.

- remove the rake task
- remote the logstash-docgen

**Comment by jakelandis** [comment]
@ph - LGTM ....but I also don't know what I am looking at :)  I can can confirm that you successfully delete a bunch of stuff, if you need a more through review, you may want to ask someone else to review too.

**Comment by suyograo** [comment]
LGTM. I've used this part of the code and good to see it being cleaned up

**Pull request closed without merging**
